COMP442 Compiler: ASTNode Class Reference
ASTNode Class Reference abstract
Base class for all AST nodes.
#include <AST.h>
Public Member Functions
virtual void accept (ASTVisitor &visitor)=0
Accept a visitor (double-dispatch entry point).
ASTNode (int line=0)
Construct base AST node with source line metadata.
std::shared_ptr< ASTNode > getLeft () const
Get left child pointer (binary/unary shared convention).
int getLineNumber () const
Get source line number for diagnostics and tracing.
std::shared_ptr< ASTNode > getRight () const
Get right child pointer (binary/shared convention).
virtual std::string getValue () const =0
Return compact textual label for diagnostics/printers.
void setLeft (std::shared_ptr< ASTNode > leftNode)
Set left child pointer.
void setRight (std::shared_ptr< ASTNode > rightNode)
Set right child pointer.
virtual ~ASTNode ()=default
Virtual destructor for polymorphic ownership safety.
Private Attributes
std::shared_ptr< ASTNode > left
int lineNumber
std::shared_ptr< ASTNode > right
Detailed Description
Base class for all AST nodes.
Provides source line metadata and optional left/right child slots used by many unary/binary/shared structural nodes.
Definition at line 96 of file AST.h.
Constructor & Destructor Documentation
ASTNode()
ASTNode::ASTNode (int line = 0) inline
Construct base AST node with source line metadata.
Parameters
line 1-based source line number associated with this node.
Definition at line 102 of file AST.h.
References lineNumber.
Referenced by AssignStmtNode::AssignStmtNode(), BinaryOpNode::BinaryOpNode(), BlockNode::BlockNode(), ClassDeclNode::ClassDeclNode(), DataMemberNode::DataMemberNode(), FloatLitNode::FloatLitNode(), FuncCallNode::FuncCallNode(), FuncDefNode::FuncDefNode(), IdNode::IdNode(), IfStmtNode::IfStmtNode(), IntLitNode::IntLitNode(), IOStmtNode::IOStmtNode(), ProgNode::ProgNode(), ReturnStmtNode::ReturnStmtNode(), TypeNode::TypeNode(), UnaryOpNode::UnaryOpNode(), VarDeclNode::VarDeclNode(), and WhileStmtNode::WhileStmtNode().
~ASTNode()
virtual ASTNode::~ASTNode () virtual default
Virtual destructor for polymorphic ownership safety.
Member Function Documentation
accept()
virtual void ASTNode::accept (ASTVisitor & visitor) pure virtual
Accept a visitor (double-dispatch entry point).
Parameters
visitor Visitor implementation for current compiler phase.
Implemented in AssignStmtNode, BinaryOpNode, BlockNode, ClassDeclNode, DataMemberNode, FloatLitNode, FuncCallNode, FuncDefNode, IdNode, IfStmtNode, IntLitNode, IOStmtNode, ProgNode, ReturnStmtNode, TypeNode, UnaryOpNode, VarDeclNode, and WhileStmtNode.
getLeft()
std::shared_ptr< ASTNode > ASTNode::getLeft () const inline
Get left child pointer (binary/unary shared convention).
Definition at line 109 of file AST.h.
References left.
Referenced by CodeGenVisitor::emitAddressForDataMember(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), SemanticAnalyzer::visit(), SemanticAnalyzer::visit(), SemanticAnalyzer::visit(), SemanticAnalyzer::visit(), SemanticAnalyzer::visit(), SemanticAnalyzer::visit(), SemanticAnalyzer::visit(), SemanticAnalyzer::visit(), and SemanticAnalyzer::visit().
getLineNumber()
int ASTNode::getLineNumber () const inline
Get source line number for diagnostics and tracing.
Definition at line 107 of file AST.h.
References lineNumber.
Referenced by CodeGenVisitor::emitAddressForDataMember(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), SemanticAnalyzer::visit(), SemanticAnalyzer::visit(), SemanticAnalyzer::visit(), SemanticAnalyzer::visit(), SemanticAnalyzer::visit(), SemanticAnalyzer::visit(), SemanticAnalyzer::visit(), SemanticAnalyzer::visit(), SemanticAnalyzer::visit(), SemanticAnalyzer::visit(), SemanticAnalyzer::visit(), and SemanticAnalyzer::visit().
getRight()
std::shared_ptr< ASTNode > ASTNode::getRight () const inline
Get right child pointer (binary/shared convention).
Definition at line 111 of file AST.h.
References right.
Referenced by CodeGenVisitor::visit(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), CodeGenVisitor::visit(), SemanticAnalyzer::visit(), SemanticAnalyzer::visit(), SemanticAnalyzer::visit(), SemanticAnalyzer::visit(), and SemanticAnalyzer::visit().
getValue()
virtual std::string ASTNode::getValue () const pure virtual
Return compact textual label for diagnostics/printers.
Returns
Node-specific display string.
Implemented in AssignStmtNode, BinaryOpNode, BlockNode, ClassDeclNode, DataMemberNode, FloatLitNode, FuncCallNode, FuncDefNode, IdNode, IfStmtNode, IntLitNode, IOStmtNode, ProgNode, ReturnStmtNode, TypeNode, UnaryOpNode, VarDeclNode, and WhileStmtNode.
setLeft()
void ASTNode::setLeft (std::shared_ptr< ASTNode > leftNode) inline
Set left child pointer.
Definition at line 114 of file AST.h.
References left.
Referenced by AssignStmtNode::AssignStmtNode(), BinaryOpNode::BinaryOpNode(), IfStmtNode::IfStmtNode(), IOStmtNode::IOStmtNode(), ReturnStmtNode::ReturnStmtNode(), UnaryOpNode::UnaryOpNode(), and WhileStmtNode::WhileStmtNode().
setRight()
void ASTNode::setRight (std::shared_ptr< ASTNode > rightNode) inline
Set right child pointer.
Definition at line 116 of file AST.h.
References right.
Referenced by AssignStmtNode::AssignStmtNode(), BinaryOpNode::BinaryOpNode(), IfStmtNode::IfStmtNode(), and WhileStmtNode::WhileStmtNode().
Member Data Documentation
left
std::shared_ptr<ASTNode> ASTNode::left private
Definition at line 131 of file AST.h.
Referenced by getLeft(), and setLeft().
lineNumber
int ASTNode::lineNumber private
Definition at line 130 of file AST.h.
Referenced by ASTNode(), and getLineNumber().
right
std::shared_ptr<ASTNode> ASTNode::right private
Definition at line 132 of file AST.h.
Referenced by getRight(), and setRight().
The documentation for this class was generated from the following file:
AST.h