COMP442 Compiler: ReturnStmtNode Class Reference
ReturnStmtNode Class Reference
Return statement node.
#include <AST.h>
Public Member Functions
void accept (ASTVisitor &visitor) override
Accept a visitor (double-dispatch entry point).
std::string getValue () const override
Return compact textual label for diagnostics/printers.
ReturnStmtNode (int line, std::shared_ptr< ASTNode > returnExpr)
Public Member Functions inherited from ASTNode
ASTNode (int line=0)
Construct base AST node with source line metadata.
std::shared_ptr< ASTNode > getLeft () const
Get left child pointer (binary/unary shared convention).
int getLineNumber () const
Get source line number for diagnostics and tracing.
std::shared_ptr< ASTNode > getRight () const
Get right child pointer (binary/shared convention).
void setLeft (std::shared_ptr< ASTNode > leftNode)
Set left child pointer.
void setRight (std::shared_ptr< ASTNode > rightNode)
Set right child pointer.
virtual ~ASTNode ()=default
Virtual destructor for polymorphic ownership safety.
Detailed Description
Return statement node.
Definition at line 365 of file AST.h.
Constructor & Destructor Documentation
ReturnStmtNode()
ReturnStmtNode::ReturnStmtNode (int line, std::shared_ptr< ASTNode > returnExpr) inline
Definition at line 367 of file AST.h.
References ASTNode::ASTNode(), and ASTNode::setLeft().
Member Function Documentation
accept()
void ReturnStmtNode::accept (ASTVisitor & visitor) override virtual
Accept a visitor (double-dispatch entry point).
Parameters
visitor Visitor implementation for current compiler phase.
Implements ASTNode.
Definition at line 47 of file AST.cpp.
References ASTVisitor::visit().
getValue()
std::string ReturnStmtNode::getValue () const inline override virtual
Return compact textual label for diagnostics/printers.
Returns
Node-specific display string.
Implements ASTNode.
Definition at line 370 of file AST.h.
The documentation for this class was generated from the following files:
AST.h
AST.cpp