COMP442 Compiler: SemanticAnalyzer Class Reference
SemanticAnalyzer Class Reference
Two-pass semantic analyzer implemented as an AST visitor.
#include <semantic.h>
Public Member Functions
bool analyze (const std::shared_ptr< ProgNode > &root)
Run semantic analysis on program AST root.
std::string dumpSymbolTables () const
Dump formatted symbol-table hierarchy.
const std::vector< std::string > & getErrors () const
Get accumulated semantic error diagnostics.
const std::vector< std::string > & getWarnings () const
Get accumulated semantic warning diagnostics.
bool isPassOne () const
True when analyzer is running declaration-building pass.
void setPassOne (bool passOne)
Set active semantic pass mode.
AST Visitor Overrides
void visit (IdNode &node) override
Validate identifier use in pass 2 by lexical resolution.
void visit (IntLitNode &node) override
Integer literal has no standalone semantic action.
void visit (FloatLitNode &node) override
Float literal has no standalone semantic action.
void visit (TypeNode &node) override
Type node has no standalone semantic action.
void visit (BinaryOpNode &node) override
Validate binary-expression operand compatibility.
void visit (UnaryOpNode &node) override
Traverse unary operand.
void visit (FuncCallNode &node) override
Validate function/method call declaration and parameter compatibility.
void visit (DataMemberNode &node) override
Validate member access and array indexing semantics.
void visit (AssignStmtNode &node) override
Validate assignment type compatibility rules.
void visit (IfStmtNode &node) override
Validate if-condition type and traverse branches.
void visit (WhileStmtNode &node) override
Validate while-condition type and traverse loop body.
void visit (IOStmtNode &node) override
Validate read/write statement operand constraints.
void visit (ReturnStmtNode &node) override
Validate return statement placement and type compatibility.
void visit (BlockNode &node) override
Enter block scope, visit statements, then restore previous scope.
void visit (VarDeclNode &node) override
Register and validate variable/field declarations.
void visit (FuncDefNode &node) override
Handle function/method declaration, implementation, and body checks.
void visit (ClassDeclNode &node) override
Process class declaration and class-member semantic rules.
void visit (ProgNode &node) override
Program-level traversal entry: classes then functions.
Public Member Functions inherited from ASTVisitor
virtual ~ASTVisitor ()=default
Virtual destructor for interface-safe polymorphic deletion.
Private Member Functions
bool defineSymbol (const SymbolEntry &entry)
Define symbol in current scope with redefinition policy checks.
void dumpScope (const std::shared_ptr< SymbolTable > &scope, int depth, std::string &out) const
Recursively dump scope tree in table format.
std::shared_ptr< SymbolTable > getOrCreateChildScope (const std::shared_ptr< SymbolTable > &parent, const std::string &scopeName)
Reuse existing child scope in pass 2 or create one in pass 1.
std::string inferExprType (const std::shared_ptr< ASTNode > &node) const
Infer expression result type for semantic checks.
void reportError (int line, const std::string &message)
Record semantic error with line context.
void reportWarning (int line, const std::string &message)
Record semantic warning with line context.
const SymbolEntry * resolveClassMember (const std::string &classTypeName, const std::string &memberName) const
Resolve member inside a class type scope.
void visitNode (const std::shared_ptr< ASTNode > &node)
Null-safe helper for visiting an optional node.
Static Private Member Functions
static std::string baseTypeName (const std::string &typeName)
Strip signature/array suffixes from a type name.
static std::string classTypeName (const ClassDeclNode &node)
Build class descriptor string including inheritance summary.
static std::string functionSignature (const FuncDefNode &node)
Build canonical function signature string from AST function node.
static std::string kindToString (SymbolKind kind)
Convert SymbolKind enum to printable label.
Private Attributes
int _blockCounter = 0
Counter for synthesized block scope naming.
std::unordered_map< std::string, std::shared_ptr< SymbolTable > > _classScopes
Class name -> class scope map.
std::shared_ptr< SymbolTable > _currentScope
Scope currently being visited.
std::vector< std::string > _errors
Collected semantic errors.
std::vector< std::string > _functionReturnTypeStack
Return-type stack for nested function-body visits.
std::shared_ptr< SymbolTable > _globalScope
Global/root scope table.
bool _isPassOne = false
Current pass mode flag.
std::vector< std::string > _warnings
Collected semantic warnings.
Detailed Description
Two-pass semantic analyzer implemented as an AST visitor.
Pass 1 builds declarations/scopes and signature metadata. Pass 2 validates identifier use, type compatibility, member access, function calls, control-flow constraints, and language semantic rules.
Definition at line 127 of file semantic.h.
Member Function Documentation
analyze()
bool SemanticAnalyzer::analyze (const std::shared_ptr< ProgNode > & root)
Run semantic analysis on program AST root.
Run semantic analyzer passes over program root.
Parameters
root Program root node.
Returns
True when no semantic errors were produced.
Parameters
root Program AST root.
Returns
True if no semantic errors were emitted.
Execution order: 1) pass 1 declaration/scope construction, 2) cross-pass global checks (undefined member declarations, inheritance cycles), 3) pass 2 usage/type checks.
Definition at line 357 of file semantic.cpp.
References _blockCounter, _classScopes, _currentScope, _errors, _functionReturnTypeStack, _globalScope, _warnings, Class, Function, reportError(), and setPassOne().
Referenced by main().
baseTypeName()
std::string SemanticAnalyzer::baseTypeName (const std::string & typeName) static private
Strip signature/array suffixes from a type name.
Extract base type token from signature/array decorated type string.
Parameters
typeName Raw type string.
Returns
Base type.
Definition at line 1330 of file semantic.cpp.
Referenced by resolveClassMember(), visit(), visit(), visit(), and visit().
classTypeName()
std::string SemanticAnalyzer::classTypeName (const ClassDeclNode & node) static private
Build class descriptor string including inheritance summary.
Build class descriptor including optional inheritance list.
Definition at line 1309 of file semantic.cpp.
References ClassDeclNode::getParents().
Referenced by resolveClassMember(), and visit().
defineSymbol()
bool SemanticAnalyzer::defineSymbol (const SymbolEntry & entry) private
Define symbol in current scope with redefinition policy checks.
Define symbol in current scope with language-specific redeclaration policy.
Parameters
entry Symbol to define.
Returns
True if accepted (defined or pass-2-safe reuse), false if rejected.
Definition at line 1210 of file semantic.cpp.
References _currentScope, Class, Field, Function, isPassOne(), SymbolEntry::kind, SymbolEntry::line, SymbolEntry::name, Parameter, reportError(), and Variable.
Referenced by visit(), visit(), and visit().
dumpScope()
void SemanticAnalyzer::dumpScope (const std::shared_ptr< SymbolTable > & scope, int depth, std::string & out) const private
Recursively dump scope tree in table format.
Recursively emit formatted symbol-table scopes as aligned text tables.
Parameters
scope Scope root for current dump recursion.
depth Nesting depth used for indentation.
out Accumulated output buffer.
Definition at line 1456 of file semantic.cpp.
References Class, dumpScope(), Function, and kindToString().
Referenced by dumpScope(), and dumpSymbolTables().
dumpSymbolTables()
std::string SemanticAnalyzer::dumpSymbolTables () const
Dump formatted symbol-table hierarchy.
Produce formatted symbol-table dump for all scopes.
Definition at line 453 of file semantic.cpp.
References _globalScope, and dumpScope().
Referenced by main().
functionSignature()
std::string SemanticAnalyzer::functionSignature (const FuncDefNode & node) static private
Build canonical function signature string from AST function node.
Build normalized signature text for function declaration comparison.
Definition at line 1294 of file semantic.cpp.
References FuncDefNode::getParams(), and FuncDefNode::getReturnType().
Referenced by visit(), and visit().
getErrors()
const std::vector< std::string > & SemanticAnalyzer::getErrors () const
Get accumulated semantic error diagnostics.
Return semantic error list.
Definition at line 443 of file semantic.cpp.
References _errors.
Referenced by main().
getOrCreateChildScope()
std::shared_ptr< SymbolTable > SemanticAnalyzer::getOrCreateChildScope (const std::shared_ptr< SymbolTable > & parent, const std::string & scopeName) private
Reuse existing child scope in pass 2 or create one in pass 1.
Reuse matching child scope (pass 2) or create fresh child scope (pass 1).
Parameters
parent Parent scope.
scopeName Target child scope label.
Returns
Matching or newly created child scope.
Definition at line 1259 of file semantic.cpp.
References isPassOne().
Referenced by visit(), visit(), and visit().
getWarnings()
const std::vector< std::string > & SemanticAnalyzer::getWarnings () const
Get accumulated semantic warning diagnostics.
Return semantic warning list.
Definition at line 448 of file semantic.cpp.
References _warnings.
Referenced by main().
inferExprType()
std::string SemanticAnalyzer::inferExprType (const std::shared_ptr< ASTNode > & node) const private
Infer expression result type for semantic checks.
Infer expression result type for semantic compatibility checks.
Parameters
node Expression node.
Returns
Inferred type string, or "null" when unresolved.
Definition at line 1374 of file semantic.cpp.
References _currentScope, inferExprType(), resolveClassMember(), and SymbolEntry::type.
Referenced by inferExprType(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
isPassOne()
bool SemanticAnalyzer::isPassOne () const inline
True when analyzer is running declaration-building pass.
Definition at line 130 of file semantic.h.
References _isPassOne.
Referenced by defineSymbol(), getOrCreateChildScope(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
kindToString()
std::string SemanticAnalyzer::kindToString (SymbolKind kind) static private
Convert SymbolKind enum to printable label.
Convert SymbolKind to printable lowercase text label.
Definition at line 1276 of file semantic.cpp.
References Class, Field, Function, Parameter, and Variable.
Referenced by dumpScope().
reportError()
void SemanticAnalyzer::reportError (int line, const std::string & message) private
Record semantic error with line context.
Append semantic error diagnostic with standardized prefix.
Definition at line 1196 of file semantic.cpp.
References _errors.
Referenced by analyze(), defineSymbol(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
reportWarning()
void SemanticAnalyzer::reportWarning (int line, const std::string & message) private
Record semantic warning with line context.
Append semantic warning diagnostic with standardized prefix.
Definition at line 1201 of file semantic.cpp.
References _warnings.
Referenced by visit(), visit(), and visit().
resolveClassMember()
const SymbolEntry * SemanticAnalyzer::resolveClassMember (const std::string & classTypeName, const std::string & memberName) const private
Resolve member inside a class type scope.
Resolve member symbol in class scope by class type name.
Parameters
classTypeName Class type string.
memberName Member identifier.
Returns
Matching member symbol or null.
Definition at line 1360 of file semantic.cpp.
References _classScopes, baseTypeName(), and classTypeName().
Referenced by inferExprType(), visit(), and visit().
setPassOne()
void SemanticAnalyzer::setPassOne (bool passOne) inline
Set active semantic pass mode.
Definition at line 132 of file semantic.h.
References _isPassOne.
Referenced by analyze().
visit() [1/18]
void SemanticAnalyzer::visit (AssignStmtNode & node) override virtual
Validate assignment type compatibility rules.
Implements ASTVisitor.
Definition at line 752 of file semantic.cpp.
References ASTNode::getLeft(), ASTNode::getLineNumber(), ASTNode::getRight(), inferExprType(), isPassOne(), reportError(), and visitNode().
visit() [2/18]
void SemanticAnalyzer::visit (BinaryOpNode & node) override virtual
Validate binary-expression operand compatibility.
Current rule set enforces numeric operands for arithmetic-style expressions.
Implements ASTVisitor.
Definition at line 482 of file semantic.cpp.
References ASTNode::getLeft(), ASTNode::getLineNumber(), ASTNode::getRight(), inferExprType(), isPassOne(), reportError(), and visitNode().
visit() [3/18]
void SemanticAnalyzer::visit (BlockNode & node) override virtual
Enter block scope, visit statements, then restore previous scope.
Implements ASTVisitor.
Definition at line 911 of file semantic.cpp.
References _blockCounter, _currentScope, getOrCreateChildScope(), BlockNode::getStatements(), and visitNode().
visit() [4/18]
void SemanticAnalyzer::visit (ClassDeclNode & node) override virtual
Process class declaration and class-member semantic rules.
Pass 1 registers class scope and fields before methods. Pass 2 validates member bodies/usages.
Implements ASTVisitor.
Definition at line 1126 of file semantic.cpp.
References _classScopes, _currentScope, _globalScope, Class, classTypeName(), defineSymbol(), SymbolEntry::details, Function, functionSignature(), ASTNode::getLineNumber(), ClassDeclNode::getMembers(), ClassDeclNode::getName(), getOrCreateChildScope(), ClassDeclNode::getParents(), isPassOne(), SymbolEntry::kind, SymbolEntry::line, SymbolEntry::name, SymbolEntry::paramTypes, reportWarning(), SymbolEntry::returnType, SymbolEntry::type, SymbolEntry::visibility, and visitNode().
visit() [5/18]
void SemanticAnalyzer::visit (DataMemberNode & node) override virtual
Validate member access and array indexing semantics.
Checks declaration visibility, owner-type/member existence, dimensional arity, integer index typing, and constant index bounds when evaluable.
Implements ASTVisitor.
Definition at line 678 of file semantic.cpp.
References _currentScope, baseTypeName(), SymbolEntry::dimensions, DataMemberNode::getIndices(), ASTNode::getLeft(), ASTNode::getLineNumber(), DataMemberNode::getName(), inferExprType(), isPassOne(), reportError(), resolveClassMember(), and visitNode().
visit() [6/18]
void SemanticAnalyzer::visit (FloatLitNode & node) override virtual
Float literal has no standalone semantic action.
Implements ASTVisitor.
Definition at line 473 of file semantic.cpp.
visit() [7/18]
void SemanticAnalyzer::visit (FuncCallNode & node) override virtual
Validate function/method call declaration and parameter compatibility.
Handles free-function and owner-qualified method-call forms, then enforces argument count/type compatibility and selected array-size semantic checks.
Implements ASTVisitor.
Definition at line 513 of file semantic.cpp.
References _currentScope, baseTypeName(), SymbolEntry::dimensions, Function, FuncCallNode::getArgs(), FuncCallNode::getFunctionName(), ASTNode::getLeft(), ASTNode::getLineNumber(), inferExprType(), isPassOne(), SymbolEntry::kind, SymbolEntry::paramDimensions, SymbolEntry::paramTypes, reportError(), resolveClassMember(), and visitNode().
visit() [8/18]
void SemanticAnalyzer::visit (FuncDefNode & node) override virtual
Handle function/method declaration, implementation, and body checks.
Pass 1: signature registration and declaration/implementation bookkeeping. Pass 2: scope setup, parameter definitions, body traversal, and return checks.
Implements ASTVisitor.
Definition at line 984 of file semantic.cpp.
References _classScopes, _currentScope, _functionReturnTypeStack, _globalScope, defineSymbol(), SymbolEntry::details, SymbolEntry::dimensions, Function, functionSignature(), FuncDefNode::getClassName(), ASTNode::getLineNumber(), FuncDefNode::getName(), getOrCreateChildScope(), FuncDefNode::getParams(), FuncDefNode::getReturnType(), ASTNode::getRight(), isPassOne(), SymbolEntry::kind, SymbolEntry::line, SymbolEntry::name, SymbolEntry::paramDimensions, Parameter, SymbolEntry::paramTypes, reportError(), reportWarning(), SymbolEntry::returnType, SymbolEntry::type, SymbolEntry::visibility, and visitNode().
visit() [9/18]
void SemanticAnalyzer::visit (IdNode & node) override virtual
Validate identifier use in pass 2 by lexical resolution.
Implements ASTVisitor.
Definition at line 460 of file semantic.cpp.
References _currentScope, ASTNode::getLineNumber(), IdNode::getName(), isPassOne(), and reportError().
visit() [10/18]
void SemanticAnalyzer::visit (IfStmtNode & node) override virtual
Validate if-condition type and traverse branches.
Implements ASTVisitor.
Definition at line 772 of file semantic.cpp.
References IfStmtNode::getElseBlock(), ASTNode::getLeft(), ASTNode::getLineNumber(), ASTNode::getRight(), inferExprType(), isPassOne(), reportError(), and visitNode().
visit() [11/18]
void SemanticAnalyzer::visit (IntLitNode & node) override virtual
Integer literal has no standalone semantic action.
Implements ASTVisitor.
Definition at line 471 of file semantic.cpp.
visit() [12/18]
void SemanticAnalyzer::visit (IOStmtNode & node) override virtual
Validate read/write statement operand constraints.
Implements ASTVisitor.
Definition at line 818 of file semantic.cpp.
References baseTypeName(), ASTNode::getLeft(), ASTNode::getLineNumber(), IOStmtNode::getValue(), inferExprType(), isPassOne(), reportError(), and visitNode().
visit() [13/18]
void SemanticAnalyzer::visit (ProgNode & node) override virtual
Program-level traversal entry: classes then functions.
Implements ASTVisitor.
Definition at line 1185 of file semantic.cpp.
References ProgNode::getClasses(), ProgNode::getFunctions(), and visitNode().
visit() [14/18]
void SemanticAnalyzer::visit (ReturnStmtNode & node) override virtual
Validate return statement placement and type compatibility.
Implements ASTVisitor.
Definition at line 859 of file semantic.cpp.
References _functionReturnTypeStack, ASTNode::getLeft(), ASTNode::getLineNumber(), inferExprType(), isPassOne(), reportError(), and visitNode().
visit() [15/18]
void SemanticAnalyzer::visit (TypeNode & node) override virtual
Type node has no standalone semantic action.
Implements ASTVisitor.
Definition at line 475 of file semantic.cpp.
visit() [16/18]
void SemanticAnalyzer::visit (UnaryOpNode & node) override virtual
Traverse unary operand.
Implements ASTVisitor.
Definition at line 503 of file semantic.cpp.
References ASTNode::getLeft(), and visitNode().
visit() [17/18]
void SemanticAnalyzer::visit (VarDeclNode & node) override virtual
Register and validate variable/field declarations.
Enforces class-type existence and selected shadowing diagnostics.
Implements ASTVisitor.
Definition at line 927 of file semantic.cpp.
References _classScopes, _currentScope, _globalScope, baseTypeName(), defineSymbol(), SymbolEntry::details, SymbolEntry::dimensions, Field, VarDeclNode::getDimensions(), ASTNode::getLineNumber(), VarDeclNode::getName(), VarDeclNode::getTypeName(), VarDeclNode::getVisibility(), isPassOne(), SymbolEntry::kind, SymbolEntry::line, SymbolEntry::name, SymbolEntry::paramTypes, reportError(), reportWarning(), SymbolEntry::returnType, SymbolEntry::type, Variable, and SymbolEntry::visibility.
visit() [18/18]
void SemanticAnalyzer::visit (WhileStmtNode & node) override virtual
Validate while-condition type and traverse loop body.
Implements ASTVisitor.
Definition at line 796 of file semantic.cpp.
References ASTNode::getLeft(), ASTNode::getLineNumber(), ASTNode::getRight(), inferExprType(), isPassOne(), reportError(), and visitNode().
visitNode()
void SemanticAnalyzer::visitNode (const std::shared_ptr< ASTNode > & node) private
Null-safe helper for visiting an optional node.
Null-safe node visitation helper.
Definition at line 1247 of file semantic.cpp.
Referenced by visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
Member Data Documentation
_blockCounter
int SemanticAnalyzer::_blockCounter = 0 private
Counter for synthesized block scope naming.
Definition at line 185 of file semantic.h.
Referenced by analyze(), and visit().
_classScopes
std::unordered_map<std::string, std::shared_ptr<SymbolTable> > SemanticAnalyzer::_classScopes private
Class name -> class scope map.
Definition at line 177 of file semantic.h.
Referenced by analyze(), resolveClassMember(), visit(), visit(), and visit().
_currentScope
std::shared_ptr<SymbolTable> SemanticAnalyzer::_currentScope private
Scope currently being visited.
Definition at line 175 of file semantic.h.
Referenced by analyze(), defineSymbol(), inferExprType(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
_errors
std::vector<std::string> SemanticAnalyzer::_errors private
Collected semantic errors.
Definition at line 179 of file semantic.h.
Referenced by analyze(), getErrors(), and reportError().
_functionReturnTypeStack
std::vector<std::string> SemanticAnalyzer::_functionReturnTypeStack private
Return-type stack for nested function-body visits.
Definition at line 183 of file semantic.h.
Referenced by analyze(), visit(), and visit().
_globalScope
std::shared_ptr<SymbolTable> SemanticAnalyzer::_globalScope private
Global/root scope table.
Definition at line 173 of file semantic.h.
Referenced by analyze(), dumpSymbolTables(), visit(), visit(), and visit().
_isPassOne
bool SemanticAnalyzer::_isPassOne = false private
Current pass mode flag.
Definition at line 171 of file semantic.h.
Referenced by isPassOne(), and setPassOne().
_warnings
std::vector<std::string> SemanticAnalyzer::_warnings private
Collected semantic warnings.
Definition at line 181 of file semantic.h.
Referenced by analyze(), getWarnings(), and reportWarning().
The documentation for this class was generated from the following files:
semantic.h
semantic.cpp