COMP442 Compiler: VarDeclNode Class Reference
VarDeclNode Class Reference
Variable/field/parameter declaration node.
#include <AST.h>
Public Member Functions
void accept (ASTVisitor &visitor) override
Accept a visitor (double-dispatch entry point).
void addDimension (int size)
std::vector< int > getDimensions () const
const std::string & getName () const
const std::string & getTypeName () const
std::string getValue () const override
Return compact textual label for diagnostics/printers.
const std::string & getVisibility () const
VarDeclNode (int line, const std::string &t, const std::string &n, const std::string &vis="local")
Public Member Functions inherited from ASTNode
ASTNode (int line=0)
Construct base AST node with source line metadata.
std::shared_ptr< ASTNode > getLeft () const
Get left child pointer (binary/unary shared convention).
int getLineNumber () const
Get source line number for diagnostics and tracing.
std::shared_ptr< ASTNode > getRight () const
Get right child pointer (binary/shared convention).
void setLeft (std::shared_ptr< ASTNode > leftNode)
Set left child pointer.
void setRight (std::shared_ptr< ASTNode > rightNode)
Set right child pointer.
virtual ~ASTNode ()=default
Virtual destructor for polymorphic ownership safety.
Private Attributes
std::vector< int > arrayDimensions
std::string name
std::string type
std::string visibility
Detailed Description
Variable/field/parameter declaration node.
Carries type, name, visibility/scope role, and optional array dimensions.
Definition at line 402 of file AST.h.
Constructor & Destructor Documentation
VarDeclNode()
VarDeclNode::VarDeclNode (int line, const std::string & t, const std::string & n, const std::string & vis = "local") inline
Definition at line 409 of file AST.h.
References ASTNode::ASTNode(), name, type, and visibility.
Member Function Documentation
accept()
void VarDeclNode::accept (ASTVisitor & visitor) override virtual
Accept a visitor (double-dispatch entry point).
Parameters
visitor Visitor implementation for current compiler phase.
Implements ASTNode.
Definition at line 49 of file AST.cpp.
References ASTVisitor::visit().
addDimension()
void VarDeclNode::addDimension (int size) inline
Definition at line 412 of file AST.h.
References arrayDimensions.
getDimensions()
std::vector< int > VarDeclNode::getDimensions () const inline
Definition at line 416 of file AST.h.
References arrayDimensions.
Referenced by SemanticAnalyzer::visit().
getName()
const std::string & VarDeclNode::getName () const inline
Definition at line 414 of file AST.h.
References name.
Referenced by SemanticAnalyzer::visit().
getTypeName()
const std::string & VarDeclNode::getTypeName () const inline
Definition at line 413 of file AST.h.
References type.
Referenced by SemanticAnalyzer::visit().
getValue()
std::string VarDeclNode::getValue () const inline override virtual
Return compact textual label for diagnostics/printers.
Returns
Node-specific display string.
Implements ASTNode.
Definition at line 417 of file AST.h.
References name, type, and visibility.
getVisibility()
const std::string & VarDeclNode::getVisibility () const inline
Definition at line 415 of file AST.h.
References visibility.
Referenced by SemanticAnalyzer::visit().
Member Data Documentation
arrayDimensions
std::vector<int> VarDeclNode::arrayDimensions private
Definition at line 406 of file AST.h.
Referenced by addDimension(), and getDimensions().
name
std::string VarDeclNode::name private
Definition at line 405 of file AST.h.
Referenced by getName(), getValue(), and VarDeclNode().
type
std::string VarDeclNode::type private
Definition at line 404 of file AST.h.
Referenced by getTypeName(), getValue(), and VarDeclNode().
visibility
std::string VarDeclNode::visibility private
Definition at line 407 of file AST.h.
Referenced by getValue(), getVisibility(), and VarDeclNode().
The documentation for this class was generated from the following files:
AST.h
AST.cpp