COMP442 Compiler: FuncDefNode Class Reference
FuncDefNode Class Reference
Function or method definition node.
#include <AST.h>
Public Member Functions
void accept (ASTVisitor &visitor) override
Accept a visitor (double-dispatch entry point).
void addLocalVar (std::shared_ptr< VarDeclNode > var)
void addParam (std::shared_ptr< VarDeclNode > param)
FuncDefNode (int line, const std::string &ret, const std::string &n, const std::string &cls="")
const std::string & getClassName () const
std::vector< std::shared_ptr< VarDeclNode > > getLocalVars () const
const std::string & getName () const
std::vector< std::shared_ptr< VarDeclNode > > getParams () const
const std::string & getReturnType () const
std::string getValue () const override
Return compact textual label for diagnostics/printers.
Public Member Functions inherited from ASTNode
ASTNode (int line=0)
Construct base AST node with source line metadata.
std::shared_ptr< ASTNode > getLeft () const
Get left child pointer (binary/unary shared convention).
int getLineNumber () const
Get source line number for diagnostics and tracing.
std::shared_ptr< ASTNode > getRight () const
Get right child pointer (binary/shared convention).
void setLeft (std::shared_ptr< ASTNode > leftNode)
Set left child pointer.
void setRight (std::shared_ptr< ASTNode > rightNode)
Set right child pointer.
virtual ~ASTNode ()=default
Virtual destructor for polymorphic ownership safety.
Private Attributes
std::string className
std::vector< std::shared_ptr< VarDeclNode > > localVariables
std::string name
std::vector< std::shared_ptr< VarDeclNode > > parameters
std::string returnType
Detailed Description
Function or method definition node.
Holds signature metadata (return type/name/class owner), parameter list, local declarations, and body block (in right child).
Definition at line 429 of file AST.h.
Constructor & Destructor Documentation
FuncDefNode()
FuncDefNode::FuncDefNode (int line, const std::string & ret, const std::string & n, const std::string & cls = "") inline
Definition at line 437 of file AST.h.
References ASTNode::ASTNode(), className, name, and returnType.
Member Function Documentation
accept()
void FuncDefNode::accept (ASTVisitor & visitor) override virtual
Accept a visitor (double-dispatch entry point).
Parameters
visitor Visitor implementation for current compiler phase.
Implements ASTNode.
Definition at line 50 of file AST.cpp.
References ASTVisitor::visit().
addLocalVar()
void FuncDefNode::addLocalVar (std::shared_ptr< VarDeclNode > var) inline
Definition at line 441 of file AST.h.
References localVariables.
addParam()
void FuncDefNode::addParam (std::shared_ptr< VarDeclNode > param) inline
Definition at line 440 of file AST.h.
References parameters.
getClassName()
const std::string & FuncDefNode::getClassName () const inline
Definition at line 444 of file AST.h.
References className.
Referenced by SemanticAnalyzer::visit().
getLocalVars()
std::vector< std::shared_ptr< VarDeclNode > > FuncDefNode::getLocalVars () const inline
Definition at line 446 of file AST.h.
References localVariables.
getName()
const std::string & FuncDefNode::getName () const inline
Definition at line 443 of file AST.h.
References name.
Referenced by SemanticAnalyzer::visit().
getParams()
std::vector< std::shared_ptr< VarDeclNode > > FuncDefNode::getParams () const inline
Definition at line 445 of file AST.h.
References parameters.
Referenced by SemanticAnalyzer::functionSignature(), and SemanticAnalyzer::visit().
getReturnType()
const std::string & FuncDefNode::getReturnType () const inline
Definition at line 442 of file AST.h.
References returnType.
Referenced by SemanticAnalyzer::functionSignature(), and SemanticAnalyzer::visit().
getValue()
std::string FuncDefNode::getValue () const inline override virtual
Return compact textual label for diagnostics/printers.
Returns
Node-specific display string.
Implements ASTNode.
Definition at line 448 of file AST.h.
References className, name, and returnType.
Member Data Documentation
className
std::string FuncDefNode::className private
Definition at line 433 of file AST.h.
Referenced by FuncDefNode(), getClassName(), and getValue().
localVariables
std::vector<std::shared_ptr<VarDeclNode> > FuncDefNode::localVariables private
Definition at line 435 of file AST.h.
Referenced by addLocalVar(), and getLocalVars().
name
std::string FuncDefNode::name private
Definition at line 432 of file AST.h.
Referenced by FuncDefNode(), getName(), and getValue().
parameters
std::vector<std::shared_ptr<VarDeclNode> > FuncDefNode::parameters private
Definition at line 434 of file AST.h.
Referenced by addParam(), and getParams().
returnType
std::string FuncDefNode::returnType private
Definition at line 431 of file AST.h.
Referenced by FuncDefNode(), getReturnType(), and getValue().
The documentation for this class was generated from the following files:
AST.h
AST.cpp