COMP442 Compiler: Token Class Reference
Token Class Reference
Immutable lexical token value with scanner utilities.
#include <token.h>
Public Types
enum class Type {
ID_ , INTEGER_LITERAL_ , FLOAT_LITERAL_ , INVALID_NUMBER_ ,
EQUAL_ , KEYWORD_ , PLUS_ , MINUS_ ,
MULTIPLY_ , DIVIDE_ , OPEN_PAREN_ , CLOSE_PAREN_ ,
OPEN_BRACE_ , CLOSE_BRACE_ , OPEN_BRACKET_ , CLOSE_BRACKET_ ,
COMMA_ , DOT_ , COLON_ , COLON_COLON_ ,
SEMICOLON_ , NOT_EQUAL_ , LESS_THAN_ , GREATER_THAN_ ,
LESS_EQUAL_ , GREATER_EQUAL_ , ASSIGNMENT_ , IF_KEYWORD_ ,
DO_KEYWORD_ , THEN_KEYWORD_ , END_KEYWORD_ , ELSE_KEYWORD_ ,
WHILE_KEYWORD_ , READ_KEYWORD_ , WRITE_KEYWORD_ , PUBLIC_KEYWORD_ ,
PRIVATE_KEYWORD_ , CLASS_KEYWORD_ , RETURN_KEYWORD_ , INHERITS_ ,
LOCAL_ , INTEGER_TYPE_ , FLOAT_TYPE_ , AND_ ,
OR_ , NOT_ , VOID_TYPE_ , MAIN_ ,
INLINE_COMMENT_ , BLOCK_COMMENT_ , UNTERMINATED_COMMENT_ , TERMINATED_COMMENT_ ,
INVALID_CHAR_ , INVALID_ID_ , INVALID_ , END_OF_FILE_
}
Canonical token categories produced by lexical analysis.
Public Member Functions
std::string getErrorString (std::string error_step) const
Build formatted lexical error message for this token.
int getLineNumber () const
Access source line for diagnostics.
Type getType () const
Access token category.
std::string getTypeString () const
Convert token type to stable printable label.
const std::string & getValue () const
Access token lexeme.
Token & operator= (const Token &other)
Copy assignment operator.
Token (const Token &other)
Copy constructor.
Token (Type type, const std::string &value, int lineNumber)
Construct a token from classification and source metadata.
std::string toString () const
Format token as output artifact record.
Static Public Member Functions
static bool _isAlphaNumeric (char c)
Check if character is allowed in identifier body.
static Type _isBlockComment (size_t &index, const std::string &line, bool &inBlockComment)
Continue or terminate block-comment parsing.
static bool _isFractionPart (const std::string &line, size_t &index)
Validate fraction part beginning with '.'.
static Type _isInlineComment (size_t &index, const std::string &line)
Parse inline comment beginning with "//".
static bool _isValidFloatLiteral (size_t &index, const std::string &line)
Validate optional exponent part for float literal.
static bool _isValidIntegerLiteral (size_t &index, const std::string &line)
Validate integer portion of numeric literal.
static std::string _scanIdentifier (const std::string &startChar, const std::string &line, size_t &index)
Scan full identifier body after first character.
static void backtrack (size_t &index, const std::string &line, const size_t &start_index)
Restore scanner index to known safe position.
static void flushPendingBlockComment (std::vector< Token > &valid, std::vector< Token > &invalid)
Emit pending unterminated block comment as both valid and invalid token.
static Type getKeywordType (const std::string &lexeme)
Resolve a lexeme as either a reserved keyword or a generic identifier.
static char getNextChar (const std::string &input, size_t &index)
Return current character and advance scanner index.
static Type isValidCharOperator (const std::string &line, size_t &index)
Classify single- and multi-character operators.
static Type isValidComment (char startChar, size_t &index, const std::string &line, bool &inBlockComment)
Classify '/' as divide, inline comment, or block comment start.
static Type isValidId (char startChar, const std::string &line, size_t &index)
Validate and classify identifier token starting at current index.
static Type isValidIntegerOrFloat (size_t &index, const std::string &line)
Validate numeric literal starting at current index.
static Type isValidKeywordOrId (const std::string &value)
Resolve scanned identifier lexeme to keyword-or-id category.
static void skipToken (size_t &index, const std::string &line)
Advance to token boundary when recovering from lexical error.
static std::tuple< std::vector< Token >, std::vector< Token > > tokenize (const std::string &line, int lineNumber, bool &inBlockComment)
Tokenize one source line.
Static Public Attributes
static std::string _blockCommentAccum
Accumulated text for currently open multi-line block comment.
static int _blockCommentStartLine = 0
Line number where current multi-line block comment started.
Private Attributes
int lineNumber_
1-based source line number.
Type type_
Token category.
std::string value_
Original lexeme text.
Detailed Description
Immutable lexical token value with scanner utilities.
Each token stores its categorical type, source lexeme, and source line. The same class also hosts scanner routines because token construction and lexical decisions are tightly coupled in this project architecture.
Why keep scanner helpers here?
The design minimizes indirection for students reading generated diagnostics: token construction, classification, and formatting live in one discoverable location.
What comes next?
If lexer complexity grows (for example, DFA tables or unicode handling), these helpers can be moved into a dedicated lexer class while preserving the Token API.
Definition at line 47 of file token.h.
Member Enumeration Documentation
Type
enum class Token::Type strong
Canonical token categories produced by lexical analysis.
The parser depends on these categories for production dispatch and error recovery. Error-prefixed kinds are intentionally first-class tokens so the pipeline can continue and report multiple issues per file.
Enumerator
ID_
INTEGER_LITERAL_
FLOAT_LITERAL_
INVALID_NUMBER_
EQUAL_
KEYWORD_
PLUS_
MINUS_
MULTIPLY_
DIVIDE_
OPEN_PAREN_
CLOSE_PAREN_
OPEN_BRACE_
CLOSE_BRACE_
OPEN_BRACKET_
CLOSE_BRACKET_
COMMA_
DOT_
COLON_
COLON_COLON_
SEMICOLON_
NOT_EQUAL_
LESS_THAN_
GREATER_THAN_
LESS_EQUAL_
GREATER_EQUAL_
ASSIGNMENT_
IF_KEYWORD_
DO_KEYWORD_
THEN_KEYWORD_
END_KEYWORD_
ELSE_KEYWORD_
WHILE_KEYWORD_
READ_KEYWORD_
WRITE_KEYWORD_
PUBLIC_KEYWORD_
PRIVATE_KEYWORD_
CLASS_KEYWORD_
RETURN_KEYWORD_
INHERITS_
LOCAL_
INTEGER_TYPE_
FLOAT_TYPE_
AND_
OR_
NOT_
VOID_TYPE_
MAIN_
INLINE_COMMENT_
BLOCK_COMMENT_
UNTERMINATED_COMMENT_
TERMINATED_COMMENT_
INVALID_CHAR_
INVALID_ID_
INVALID_
END_OF_FILE_
Definition at line 58 of file token.h.
Constructor & Destructor Documentation
Token() [1/2]
Token::Token (Type type, const std::string & value, int lineNumber) inline
Construct a token from classification and source metadata.
Parameters
type Token category.
value Lexeme extracted from source.
lineNumber 1-based source line where token starts.
Definition at line 273 of file token.h.
References lineNumber_, type_, and value_.
Referenced by flushPendingBlockComment(), operator=(), and Token().
Token() [2/2]
Token::Token (const Token & other) inline
Copy constructor.
Parameters
other Token to copy.
Definition at line 307 of file token.h.
References lineNumber_, Token(), type_, and value_.
Member Function Documentation
_isAlphaNumeric()
bool Token::_isAlphaNumeric (char c) static
Check if character is allowed in identifier body.
Test identifier-body character set.
Parameters
c Character to test.
Returns
True if alphanumeric or underscore.
Parameters
c Character to classify.
Returns
True for [a-zA-Z0-9_] characters.
Definition at line 495 of file token.cpp.
Referenced by _scanIdentifier(), and tokenize().
_isBlockComment()
Token::Type Token::_isBlockComment (size_t & index, const std::string & line, bool & inBlockComment) static
Continue or terminate block-comment parsing.
Consume block comment section and update multiline state.
Parameters
index Scanner index.
line Source line.
inBlockComment Cross-line block-comment state.
Returns
BLOCK_COMMENT_ if closed, UNTERMINATED_COMMENT_ otherwise.
Parameters
index In/out scanner cursor.
line Source line.
inBlockComment In/out multiline comment state.
Returns
BLOCK_COMMENT_ if closed on this line, UNTERMINATED_COMMENT_ otherwise.
Why explicit state?
The tokenizer processes one line at a time, so cross-line comments require explicit state handoff between tokenize() calls.
Definition at line 680 of file token.cpp.
References BLOCK_COMMENT_, and UNTERMINATED_COMMENT_.
Referenced by isValidComment().
_isFractionPart()
bool Token::_isFractionPart (const std::string & line, size_t & index) static
Validate fraction part beginning with '.'.
Validate and consume fraction segment beginning with '.'.
Parameters
line Source line.
index Current scanner position at '.'.
Returns
True if accepted by language float policy.
Parameters
line Source line.
index In/out scanner cursor.
Returns
True when fraction policy is satisfied.
Current policy permits ".0" but rejects trailing-zero multi-digit fractions (for example, ".50"). That policy is intentional for this language version.
Definition at line 379 of file token.cpp.
References skipToken().
Referenced by isValidIntegerOrFloat().
_isInlineComment()
Token::Type Token::_isInlineComment (size_t & index, const std::string & line) static
Parse inline comment beginning with "//".
Consume inline comment from "//" to end-of-line.
Parameters
index Scanner index.
line Source line.
Returns
INLINE_COMMENT_.
Parameters
index In/out scanner cursor.
line Source line.
Returns
INLINE_COMMENT_.
Definition at line 660 of file token.cpp.
References INLINE_COMMENT_.
Referenced by isValidComment().
_isValidFloatLiteral()
bool Token::_isValidFloatLiteral (size_t & index, const std::string & line) static
Validate optional exponent part for float literal.
Validate optional exponent segment of a float literal.
Parameters
index Scanner index currently at optional 'e'.
line Source line.
Returns
True if exponent form is valid.
Note
float ::= integer fraction [e[+|−] integer]
Parameters
index In/out scanner cursor expected at optional 'e'.
line Source line.
Returns
True if exponent syntax is valid.
Why?
Splitting exponent validation from fraction validation keeps numeric error messages and rollback behavior easier to reason about.
Definition at line 346 of file token.cpp.
References _isValidIntegerLiteral(), and skipToken().
Referenced by isValidIntegerOrFloat().
_isValidIntegerLiteral()
bool Token::_isValidIntegerLiteral (size_t & index, const std::string & line) static
Validate integer portion of numeric literal.
Validate integer segment according to language integer rule.
Parameters
index Current scanner position, advanced through integer part.
line Source line.
Returns
True if integer form is valid.
Note
integer ::= nonzero digit* | 0.
Parameters
index In/out scanner cursor.
line Source line.
Returns
True when integer form is accepted.
This validator enforces leading-zero policy and rejects illegal identifier suffixes (except exponent handoff via 'e').
Definition at line 285 of file token.cpp.
References skipToken().
Referenced by _isValidFloatLiteral(), and isValidIntegerOrFloat().
_scanIdentifier()
std::string Token::_scanIdentifier (const std::string & startChar, const std::string & line, size_t & index) static
Scan full identifier body after first character.
Consume identifier tail and return full lexeme.
Parameters
startChar First identifier character as string.
line Source line.
index Current scanner index (advanced during scan).
Returns
Complete identifier lexeme.
Parameters
startChar First character wrapped as string.
line Source line.
index In/out scanner cursor.
Returns
Complete identifier lexeme.
Definition at line 543 of file token.cpp.
References _isAlphaNumeric().
Referenced by isValidId().
backtrack()
void Token::backtrack (size_t & index, const std::string & line, const size_t & start_index) static
Restore scanner index to known safe position.
Parameters
index Scanner index updated in-place.
line Source line.
start_index Position to restore.
Reserved for future recovery workflows; currently declared for interface completeness in case predictive lexical recovery requires rollback.
flushPendingBlockComment()
void Token::flushPendingBlockComment (std::vector< Token > & valid, std::vector< Token > & invalid) static
Emit pending unterminated block comment as both valid and invalid token.
Flush unterminated multiline comment at end-of-file.
Parameters
valid Output stream containing all produced tokens.
invalid Output stream containing lexical error tokens.
Why?
Unterminated comments are lexical errors, but preserving the raw lexeme in both streams improves observability for debugging and grading.
What comes next?
Call this once after the last source line is tokenized.
Parameters
valid Token output stream.
invalid Invalid-token output stream.
Emits a single UNTERMINATED_COMMENT_ token into both streams so diagnostics remain visible without losing lexical context.
Definition at line 718 of file token.cpp.
References _blockCommentAccum, _blockCommentStartLine, Token(), and UNTERMINATED_COMMENT_.
Referenced by tokenizeFile().
getErrorString()
std::string Token::getErrorString (std::string error_step) const
Build formatted lexical error message for this token.
Compose stable diagnostic message for tokenized lexical error.
Parameters
error_step Pipeline label prefix (for example, "LEXER").
Returns
Structured error string for diagnostics output.
Parameters
error_step Pipeline label prefix.
Returns
Formatted error text.
Definition at line 100 of file token.cpp.
References getLineNumber(), getTypeString(), and getValue().
getKeywordType()
Token::Type Token::getKeywordType (const std::string & lexeme) static
Resolve a lexeme as either a reserved keyword or a generic identifier.
Resolve identifier lexeme against reserved keyword table.
Parameters
lexeme Candidate identifier text.
Returns
Specific keyword token type, or ID_ if not reserved.
Why?
Keyword resolution after identifier scanning keeps the scanner simple and avoids duplicating character rules for each reserved word.
What comes next?
Any language keyword additions should be reflected in this lookup and in the parser grammar terminals.
Parameters
lexeme Candidate text.
Returns
Keyword token type, or ID_ when not reserved.
Why?
Deferring keyword decision after identifier scan allows a single identifier automaton and simplifies maintenance.
Definition at line 35 of file token.cpp.
References AND_, CLASS_KEYWORD_, DO_KEYWORD_, ELSE_KEYWORD_, END_KEYWORD_, FLOAT_TYPE_, ID_, IF_KEYWORD_, INHERITS_, INTEGER_TYPE_, LOCAL_, MAIN_, NOT_, OR_, PRIVATE_KEYWORD_, PUBLIC_KEYWORD_, READ_KEYWORD_, RETURN_KEYWORD_, THEN_KEYWORD_, VOID_TYPE_, WHILE_KEYWORD_, and WRITE_KEYWORD_.
Referenced by isValidKeywordOrId().
getLineNumber()
int Token::getLineNumber () const inline
Access source line for diagnostics.
Returns
1-based line number where token starts.
Definition at line 299 of file token.h.
References lineNumber_.
Referenced by Parser::_formatError(), Parser::_parseAddOpTail(), Parser::_parseClassDecl(), Parser::_parseExprTail(), Parser::_parseFactor(), Parser::_parseFactorCallTail(), Parser::_parseFactorRest(), Parser::_parseFParams(), Parser::_parseFParamsTail(), Parser::_parseFuncHead(), Parser::_parseMemberDecl(), Parser::_parseMultOpTail(), Parser::_parseProgram(), Parser::_parseRelExpr(), Parser::_parseStatement(), Parser::_parseStatementCallTail(), Parser::_parseStatementRest(), Parser::_parseType(), Parser::_parseVarDecl(), Parser::_parseVariable(), getErrorString(), and toString().
getNextChar()
char Token::getNextChar (const std::string & line, size_t & index) static
Return current character and advance scanner index.
Return current character and advance index safely.
Parameters
input Source line.
index Current scanner position, advanced when in range.
Returns
Character at current position or '\0' at end-of-line.
Parameters
line Source line.
index In/out scanner cursor.
Returns
Character at cursor, or '\0' when out of bounds.
Definition at line 74 of file token.cpp.
getType()
Type Token::getType () const inline
Access token category.
Returns
Token::Type classification.
Definition at line 283 of file token.h.
References type_.
getTypeString()
std::string Token::getTypeString () const inline
Convert token type to stable printable label.
Returns
Human-readable token type name used by logs and output artifacts.
Definition at line 138 of file token.h.
References AND_, ASSIGNMENT_, BLOCK_COMMENT_, CLASS_KEYWORD_, CLOSE_BRACE_, CLOSE_BRACKET_, CLOSE_PAREN_, COLON_, COLON_COLON_, COMMA_, DIVIDE_, DO_KEYWORD_, DOT_, ELSE_KEYWORD_, END_KEYWORD_, END_OF_FILE_, EQUAL_, FLOAT_LITERAL_, FLOAT_TYPE_, GREATER_EQUAL_, GREATER_THAN_, ID_, IF_KEYWORD_, INHERITS_, INLINE_COMMENT_, INTEGER_LITERAL_, INTEGER_TYPE_, INVALID_CHAR_, INVALID_ID_, INVALID_NUMBER_, LESS_EQUAL_, LESS_THAN_, LOCAL_, MAIN_, MINUS_, MULTIPLY_, NOT_, NOT_EQUAL_, OPEN_BRACE_, OPEN_BRACKET_, OPEN_PAREN_, OR_, PLUS_, PRIVATE_KEYWORD_, PUBLIC_KEYWORD_, READ_KEYWORD_, RETURN_KEYWORD_, SEMICOLON_, TERMINATED_COMMENT_, THEN_KEYWORD_, type_, UNTERMINATED_COMMENT_, VOID_TYPE_, WHILE_KEYWORD_, and WRITE_KEYWORD_.
Referenced by Parser::_formatError(), getErrorString(), and toString().
getValue()
const std::string & Token::getValue () const inline
Access token lexeme.
Returns
Source substring captured for this token.
Definition at line 291 of file token.h.
References value_.
Referenced by Parser::_parseArraySizeTail(), Parser::_parseClassDecl(), Parser::_parseFactor(), Parser::_parseFactorCallTail(), Parser::_parseFactorRest(), Parser::_parseFParams(), Parser::_parseFParamsTail(), Parser::_parseFuncHead(), Parser::_parseFuncHeadTail(), Parser::_parseInheritanceOpt(), Parser::_parseInheritsList(), Parser::_parseMemberDecl(), Parser::_parseStatement(), Parser::_parseStatementCallTail(), Parser::_parseStatementRest(), Parser::_parseType(), Parser::_parseVarDecl(), Parser::_parseVariable(), getErrorString(), and toString().
isValidCharOperator()
Token::Type Token::isValidCharOperator (const std::string & line, size_t & index) static
Classify single- and multi-character operators.
Classify operator and punctuation tokens requiring lookahead.
Parameters
line Source line.
index Current scanner position, advanced according to operator width.
Returns
Operator token type or INVALID_CHAR_.
Parameters
line Source line.
index In/out scanner cursor.
Returns
Operator token class or INVALID_CHAR_.
What comes next?
Add new multi-character operators here when language operators expand.
Definition at line 573 of file token.cpp.
References ASSIGNMENT_, COLON_, COLON_COLON_, EQUAL_, GREATER_EQUAL_, GREATER_THAN_, INVALID_CHAR_, LESS_EQUAL_, LESS_THAN_, and NOT_EQUAL_.
Referenced by tokenize().
isValidComment()
Token::Type Token::isValidComment (char startChar, size_t & index, const std::string & line, bool & inBlockComment) static
Classify '/' as divide, inline comment, or block comment start.
Disambiguate '/' as divide, inline comment, or block comment.
Parameters
startChar Current character expected to be '/'.
index Scanner index.
line Source line.
inBlockComment Cross-line block-comment state.
Returns
DIVIDE_, INLINE_COMMENT_, BLOCK_COMMENT_, or UNTERMINATED_COMMENT_.
Parameters
startChar Current scanner character (expected '/').
index In/out scanner cursor.
line Source line.
inBlockComment In/out multiline comment state.
Returns
Comment token type or DIVIDE_.
Definition at line 626 of file token.cpp.
References _isBlockComment(), _isInlineComment(), DIVIDE_, and INVALID_.
Referenced by tokenize().
isValidId()
Token::Type Token::isValidId (char startChar, const std::string & line, size_t & index) static
Validate and classify identifier token starting at current index.
Validate identifier form and classify as keyword or ID.
Parameters
startChar First character already observed.
line Source line.
index Current scanner position, advanced through identifier.
Returns
ID_ / keyword type or INVALID_ID_.
Note
Language rule: id ::= letter alphanum*.
Parameters
startChar First character of candidate identifier.
line Source line.
index In/out scanner cursor.
Returns
ID_/keyword type or INVALID_ID_.
Why?
Leading-character validation here keeps tokenize() dispatch concise and ensures all identifier diagnostics are consistent.
Definition at line 521 of file token.cpp.
References _scanIdentifier(), INVALID_ID_, isValidKeywordOrId(), and skipToken().
Referenced by tokenize().
isValidIntegerOrFloat()
Token::Type Token::isValidIntegerOrFloat (size_t & index, const std::string & line) static
Validate numeric literal starting at current index.
Classify numeric lexeme as integer, float, or invalid number.
Parameters
index Current scanner position, advanced across literal.
line Source line.
Returns
INTEGER_LITERAL_, FLOAT_LITERAL_, or INVALID_NUMBER_.
Parameters
index In/out scanner cursor.
line Source line.
Returns
INTEGER_LITERAL_, FLOAT_LITERAL_, or INVALID_NUMBER_.
Why staged checks?
Integer -> fraction -> exponent progression mirrors grammar and allows precise failure points without re-scanning input.
Definition at line 449 of file token.cpp.
References _isFractionPart(), _isValidFloatLiteral(), _isValidIntegerLiteral(), FLOAT_LITERAL_, INTEGER_LITERAL_, and INVALID_NUMBER_.
Referenced by tokenize().
isValidKeywordOrId()
Token::Type Token::isValidKeywordOrId (const std::string & current_char) static
Resolve scanned identifier lexeme to keyword-or-id category.
Resolve scanned identifier to keyword-or-id token class.
Parameters
value Identifier lexeme.
Returns
Specific keyword type or ID_.
Parameters
current_char Identifier lexeme.
Returns
Keyword type or ID_.
Definition at line 506 of file token.cpp.
References getKeywordType().
Referenced by isValidId().
operator=()
Token & Token::operator= (const Token & other) inline
Copy assignment operator.
Parameters
other Token to copy.
Returns
Reference to this token.
Definition at line 327 of file token.h.
References lineNumber_, Token(), type_, and value_.
skipToken()
void Token::skipToken (size_t & index, const std::string & line) static
Advance to token boundary when recovering from lexical error.
Consume input until whitespace boundary for error recovery.
Parameters
index Scanner index updated in-place.
line Source line.
index In/out scanner cursor.
line Source line.
Why?
Recovery-by-skip prevents the lexer from getting stuck on malformed lexemes.
Definition at line 89 of file token.cpp.
Referenced by _isFractionPart(), _isValidFloatLiteral(), _isValidIntegerLiteral(), and isValidId().
tokenize()
std::tuple< std::vector< Token >, std::vector< Token > > Token::tokenize (const std::string & line, int lineNumber, bool & inBlockComment) static
Tokenize one source line.
Tokenize one source line into full stream and invalid-token stream.
Parameters
line Source text for current line.
lineNumber 1-based source line number.
inBlockComment Cross-line state flag for block comments.
Returns
Tuple(validOrAllTokens, invalidTokens).
Valid stream includes comment tokens and normal tokens. Invalid stream contains only lexical-error tokens used for error output artifacts.
Why line-by-line?
The project pipeline emits per-line diagnostics and keeps parser-facing handling simple while still supporting multi-line block comments via state.
What comes next?
Driver code should call flushPendingBlockComment() at end-of-file to emit unterminated block-comment diagnostics.
Parameters
line Source line text.
lineNumber 1-based source line number.
inBlockComment In/out state for multi-line block comments.
Returns
Tuple(allTokens, invalidTokens).
The lexer prioritizes deterministic progress: every iteration either consumes at least one character or explicitly advances index to avoid infinite loops.
Why this split output?
The driver emits token and error artifacts independently, so we keep both channels available from a single scan pass.
What comes next?
End-of-file handling should call flushPendingBlockComment() to emit an unterminated multi-line comment if still open.
Definition at line 131 of file token.cpp.
References _blockCommentAccum, _blockCommentStartLine, _isAlphaNumeric(), BLOCK_COMMENT_, CLOSE_BRACE_, CLOSE_BRACKET_, CLOSE_PAREN_, COMMA_, DOT_, INVALID_, INVALID_CHAR_, INVALID_ID_, INVALID_NUMBER_, isValidCharOperator(), isValidComment(), isValidId(), isValidIntegerOrFloat(), MINUS_, MULTIPLY_, OPEN_BRACE_, OPEN_BRACKET_, OPEN_PAREN_, PLUS_, SEMICOLON_, and UNTERMINATED_COMMENT_.
Referenced by tokenizeFile().
toString()
std::string Token::toString () const inline
Format token as output artifact record.
Returns
String representation used in generated lexer output files.
Definition at line 317 of file token.h.
References getLineNumber(), getTypeString(), and getValue().
Referenced by Parser::_formatError().
Member Data Documentation
_blockCommentAccum
std::string Token::_blockCommentAccum static
Accumulated text for currently open multi-line block comment.
This is explicit shared state across tokenize() calls to preserve full comment lexeme when the opening '/' + '' and the closing '' + '/' span different lines.
Definition at line 503 of file token.h.
Referenced by flushPendingBlockComment(), and tokenize().
_blockCommentStartLine
int Token::_blockCommentStartLine = 0 static
Line number where current multi-line block comment started.
Definition at line 508 of file token.h.
Referenced by flushPendingBlockComment(), and tokenize().
lineNumber_
int Token::lineNumber_ private
1-based source line number.
Definition at line 534 of file token.h.
Referenced by getLineNumber(), operator=(), Token(), and Token().
type_
Type Token::type_ private
Token category.
Definition at line 530 of file token.h.
Referenced by getType(), getTypeString(), operator=(), Token(), and Token().
value_
std::string Token::value_ private
Original lexeme text.
Definition at line 532 of file token.h.
Referenced by getValue(), operator=(), Token(), and Token().
The documentation for this class was generated from the following files:
token.h
token.cpp