COMP442 Compiler: FuncCallNode Class Reference
FuncCallNode Class Reference
Function or method call expression node.
#include <AST.h>
Public Member Functions
void accept (ASTVisitor &visitor) override
Accept a visitor (double-dispatch entry point).
void addArgument (std::shared_ptr< ASTNode > arg)
FuncCallNode (int line, const std::string &name)
std::vector< std::shared_ptr< ASTNode > > getArgs () const
const std::string & getFunctionName () const
std::string getValue () const override
Return compact textual label for diagnostics/printers.
Public Member Functions inherited from ASTNode
ASTNode (int line=0)
Construct base AST node with source line metadata.
std::shared_ptr< ASTNode > getLeft () const
Get left child pointer (binary/unary shared convention).
int getLineNumber () const
Get source line number for diagnostics and tracing.
std::shared_ptr< ASTNode > getRight () const
Get right child pointer (binary/shared convention).
void setLeft (std::shared_ptr< ASTNode > leftNode)
Set left child pointer.
void setRight (std::shared_ptr< ASTNode > rightNode)
Set right child pointer.
virtual ~ASTNode ()=default
Virtual destructor for polymorphic ownership safety.
Private Attributes
std::vector< std::shared_ptr< ASTNode > > arguments
std::string funcName
Detailed Description
Function or method call expression node.
Stores textual function name plus argument expressions. Optional left child can hold receiver/callee-owner context for member-call forms.
Definition at line 253 of file AST.h.
Constructor & Destructor Documentation
FuncCallNode()
FuncCallNode::FuncCallNode (int line, const std::string & name) inline
Definition at line 258 of file AST.h.
References ASTNode::ASTNode(), and funcName.
Member Function Documentation
accept()
void FuncCallNode::accept (ASTVisitor & visitor) override virtual
Accept a visitor (double-dispatch entry point).
Parameters
visitor Visitor implementation for current compiler phase.
Implements ASTNode.
Definition at line 41 of file AST.cpp.
References ASTVisitor::visit().
addArgument()
void FuncCallNode::addArgument (std::shared_ptr< ASTNode > arg) inline
Definition at line 260 of file AST.h.
References arguments.
getArgs()
std::vector< std::shared_ptr< ASTNode > > FuncCallNode::getArgs () const inline
Definition at line 262 of file AST.h.
References arguments.
Referenced by CodeGenVisitor::visit(), and SemanticAnalyzer::visit().
getFunctionName()
const std::string & FuncCallNode::getFunctionName () const inline
Definition at line 261 of file AST.h.
References funcName.
Referenced by CodeGenVisitor::visit(), and SemanticAnalyzer::visit().
getValue()
std::string FuncCallNode::getValue () const inline override virtual
Return compact textual label for diagnostics/printers.
Returns
Node-specific display string.
Implements ASTNode.
Definition at line 264 of file AST.h.
References funcName.
Member Data Documentation
arguments
std::vector<std::shared_ptr<ASTNode> > FuncCallNode::arguments private
Definition at line 256 of file AST.h.
Referenced by addArgument(), and getArgs().
funcName
std::string FuncCallNode::funcName private
Definition at line 255 of file AST.h.
Referenced by FuncCallNode(), getFunctionName(), and getValue().
The documentation for this class was generated from the following files:
AST.h
AST.cpp