COMP442 Compiler: ASTVisitor Class Reference
ASTVisitor Class Reference abstract
Visitor interface for all concrete AST node kinds.
#include <AST.h>
Public Member Functions
virtual void visit (AssignStmtNode &node)=0
virtual void visit (BinaryOpNode &node)=0
virtual void visit (BlockNode &node)=0
virtual void visit (ClassDeclNode &node)=0
virtual void visit (DataMemberNode &node)=0
virtual void visit (FloatLitNode &node)=0
virtual void visit (FuncCallNode &node)=0
virtual void visit (FuncDefNode &node)=0
virtual void visit (IdNode &node)=0
virtual void visit (IfStmtNode &node)=0
virtual void visit (IntLitNode &node)=0
virtual void visit (IOStmtNode &node)=0
virtual void visit (ProgNode &node)=0
virtual void visit (ReturnStmtNode &node)=0
virtual void visit (TypeNode &node)=0
virtual void visit (UnaryOpNode &node)=0
virtual void visit (VarDeclNode &node)=0
virtual void visit (WhileStmtNode &node)=0
virtual ~ASTVisitor ()=default
Virtual destructor for interface-safe polymorphic deletion.
Detailed Description
Visitor interface for all concrete AST node kinds.
This interface is the single dispatch surface for compiler passes that operate on AST nodes. Each pass implements these visit methods and receives a concrete node type through double-dispatch via ASTNode::accept().
Why explicit visit overloads?
Explicit overloads provide type-safe traversal and avoid runtime casts in each compiler phase.
Definition at line 60 of file AST.h.
Constructor & Destructor Documentation
~ASTVisitor()
virtual ASTVisitor::~ASTVisitor () virtual default
Virtual destructor for interface-safe polymorphic deletion.
Member Function Documentation
visit() [1/18]
virtual void ASTVisitor::visit (AssignStmtNode & node) pure virtual
Implemented in CodeGenVisitor, and SemanticAnalyzer.
visit() [2/18]
virtual void ASTVisitor::visit (BinaryOpNode & node) pure virtual
Implemented in CodeGenVisitor, and SemanticAnalyzer.
visit() [3/18]
virtual void ASTVisitor::visit (BlockNode & node) pure virtual
Implemented in CodeGenVisitor, and SemanticAnalyzer.
visit() [4/18]
virtual void ASTVisitor::visit (ClassDeclNode & node) pure virtual
Implemented in CodeGenVisitor, and SemanticAnalyzer.
visit() [5/18]
virtual void ASTVisitor::visit (DataMemberNode & node) pure virtual
Implemented in CodeGenVisitor, and SemanticAnalyzer.
visit() [6/18]
virtual void ASTVisitor::visit (FloatLitNode & node) pure virtual
Implemented in CodeGenVisitor, and SemanticAnalyzer.
visit() [7/18]
virtual void ASTVisitor::visit (FuncCallNode & node) pure virtual
Implemented in CodeGenVisitor, and SemanticAnalyzer.
visit() [8/18]
virtual void ASTVisitor::visit (FuncDefNode & node) pure virtual
Implemented in CodeGenVisitor, and SemanticAnalyzer.
visit() [9/18]
virtual void ASTVisitor::visit (IdNode & node) pure virtual
Implemented in CodeGenVisitor, and SemanticAnalyzer.
Referenced by AssignStmtNode::accept(), BinaryOpNode::accept(), BlockNode::accept(), ClassDeclNode::accept(), DataMemberNode::accept(), FloatLitNode::accept(), FuncCallNode::accept(), FuncDefNode::accept(), IdNode::accept(), IfStmtNode::accept(), IntLitNode::accept(), IOStmtNode::accept(), ProgNode::accept(), ReturnStmtNode::accept(), TypeNode::accept(), UnaryOpNode::accept(), VarDeclNode::accept(), and WhileStmtNode::accept().
visit() [10/18]
virtual void ASTVisitor::visit (IfStmtNode & node) pure virtual
Implemented in CodeGenVisitor, and SemanticAnalyzer.
visit() [11/18]
virtual void ASTVisitor::visit (IntLitNode & node) pure virtual
Implemented in CodeGenVisitor, and SemanticAnalyzer.
visit() [12/18]
virtual void ASTVisitor::visit (IOStmtNode & node) pure virtual
Implemented in CodeGenVisitor, and SemanticAnalyzer.
visit() [13/18]
virtual void ASTVisitor::visit (ProgNode & node) pure virtual
Implemented in CodeGenVisitor, and SemanticAnalyzer.
visit() [14/18]
virtual void ASTVisitor::visit (ReturnStmtNode & node) pure virtual
Implemented in CodeGenVisitor, and SemanticAnalyzer.
visit() [15/18]
virtual void ASTVisitor::visit (TypeNode & node) pure virtual
Implemented in CodeGenVisitor, and SemanticAnalyzer.
visit() [16/18]
virtual void ASTVisitor::visit (UnaryOpNode & node) pure virtual
Implemented in CodeGenVisitor, and SemanticAnalyzer.
visit() [17/18]
virtual void ASTVisitor::visit (VarDeclNode & node) pure virtual
Implemented in CodeGenVisitor, and SemanticAnalyzer.
visit() [18/18]
virtual void ASTVisitor::visit (WhileStmtNode & node) pure virtual
Implemented in CodeGenVisitor, and SemanticAnalyzer.
The documentation for this class was generated from the following file:
AST.h