COMP442 Compiler: ProgNode Class Reference
ProgNode Class Reference
Root program node containing classes and top-level functions.
#include <AST.h>
Public Member Functions
void accept (ASTVisitor &visitor) override
Accept a visitor (double-dispatch entry point).
void addClass (std::shared_ptr< ClassDeclNode > cls)
void addFunction (std::shared_ptr< FuncDefNode > func)
std::vector< std::shared_ptr< ClassDeclNode > > getClasses () const
std::vector< std::shared_ptr< FuncDefNode > > getFunctions () const
std::string getValue () const override
Return compact textual label for diagnostics/printers.
ProgNode (int line=0)
Public Member Functions inherited from ASTNode
ASTNode (int line=0)
Construct base AST node with source line metadata.
std::shared_ptr< ASTNode > getLeft () const
Get left child pointer (binary/unary shared convention).
int getLineNumber () const
Get source line number for diagnostics and tracing.
std::shared_ptr< ASTNode > getRight () const
Get right child pointer (binary/shared convention).
void setLeft (std::shared_ptr< ASTNode > leftNode)
Set left child pointer.
void setRight (std::shared_ptr< ASTNode > rightNode)
Set right child pointer.
virtual ~ASTNode ()=default
Virtual destructor for polymorphic ownership safety.
Private Attributes
std::vector< std::shared_ptr< ClassDeclNode > > classes
std::vector< std::shared_ptr< FuncDefNode > > functions
Detailed Description
Root program node containing classes and top-level functions.
Definition at line 483 of file AST.h.
Constructor & Destructor Documentation
ProgNode()
ProgNode::ProgNode (int line = 0) inline
Definition at line 488 of file AST.h.
References ASTNode::ASTNode().
Member Function Documentation
accept()
void ProgNode::accept (ASTVisitor & visitor) override virtual
Accept a visitor (double-dispatch entry point).
Parameters
visitor Visitor implementation for current compiler phase.
Implements ASTNode.
Definition at line 52 of file AST.cpp.
References ASTVisitor::visit().
addClass()
void ProgNode::addClass (std::shared_ptr< ClassDeclNode > cls) inline
Definition at line 490 of file AST.h.
References classes.
addFunction()
void ProgNode::addFunction (std::shared_ptr< FuncDefNode > func) inline
Definition at line 491 of file AST.h.
References functions.
getClasses()
std::vector< std::shared_ptr< ClassDeclNode > > ProgNode::getClasses () const inline
Definition at line 492 of file AST.h.
References classes.
Referenced by CodeGenVisitor::visit(), and SemanticAnalyzer::visit().
getFunctions()
std::vector< std::shared_ptr< FuncDefNode > > ProgNode::getFunctions () const inline
Definition at line 493 of file AST.h.
References functions.
Referenced by CodeGenVisitor::visit(), and SemanticAnalyzer::visit().
getValue()
std::string ProgNode::getValue () const inline override virtual
Return compact textual label for diagnostics/printers.
Returns
Node-specific display string.
Implements ASTNode.
Definition at line 495 of file AST.h.
Member Data Documentation
classes
std::vector<std::shared_ptr<ClassDeclNode> > ProgNode::classes private
Definition at line 485 of file AST.h.
Referenced by addClass(), and getClasses().
functions
std::vector<std::shared_ptr<FuncDefNode> > ProgNode::functions private
Definition at line 486 of file AST.h.
Referenced by addFunction(), and getFunctions().
The documentation for this class was generated from the following files:
AST.h
AST.cpp