COMP442 Compiler: Parser Class Reference
Parser Class Reference
LL(1) recursive-descent parser with panic-mode recovery and AST construction.
#include <my_parser.h>
Classes
struct FuncHeadInfo
Temporary container for parsed function-head components.
struct StatementIdTailResult
Result bundle for identifier-led statement disambiguation.
Static Private Member Functions
Program and Declaration Parsing
Parse top-level program structure, classes, and declarations.
These routines parse compilation-unit skeleton first (classes/functions/ main) before statement-level details.
Why?
A predictable top-down structure keeps synchronization points clear and aligns with grammar non-terminal hierarchy.
static std::shared_ptr< ProgNode > _parseProgram ()
Parse complete program grammar entry point.
static std::vector< std::shared_ptr< ClassDeclNode > > _parseClassDeclList ()
Parse top-level class declaration list with recovery.
static std::vector< std::shared_ptr< FuncDefNode > > _parseFuncDefList ()
Parse top-level function definition list with recovery.
static std::shared_ptr< ClassDeclNode > _parseClassDecl ()
Parse class declaration.
static std::vector< std::string > _parseInheritanceOpt ()
Parse optional inheritance clause.
static std::vector< std::string > _parseInheritsList ()
Parse trailing inherited-class list.
static std::vector< std::shared_ptr< ASTNode > > _parseClassBody ()
Parse class body sequence.
static std::shared_ptr< ASTNode > _parseClassMemberDecl ()
Parse one class member declaration with leading visibility.
static std::string _parseVisibility ()
Parse visibility modifier.
static std::shared_ptr< ASTNode > _parseMemberDecl (const std::string &visibility)
Parse class member declaration entry point.
static std::shared_ptr< ASTNode > _parseMemberDeclIdTail (const std::string &memberName, const std::string &visibility, int line)
Parse member declaration tail when first token was identifier.
static std::shared_ptr< ASTNode > _parseMemberDeclTypeTail (const std::string &typeName, const std::string &memberName, const std::string &visibility, int line)
Parse member declaration tail when explicit type token started declaration.
Function Parsing
Parse function signatures, parameters, locals, and bodies.
Why?
Separating function-head parsing from body parsing allows clear handling of method-qualified names and return-type constraints.
static std::shared_ptr< FuncDefNode > _parseFuncDef ()
Parse complete function definition.
static FuncHeadInfo _parseFuncHead ()
Parse function head (name, params, optional class qualifier, return type).
static void _parseFuncHeadTail (FuncHeadInfo &info, int headLine)
Parse function-head tail for free function or class-qualified method.
static std::string _parseReturnType ()
Parse function return type non-terminal.
static std::shared_ptr< TypeNode > _parseType ()
static std::vector< std::shared_ptr< VarDeclNode > > _parseFParams ()
Parse formal parameter list in function/method signatures.
static void _parseFParamsTail (std::vector< std::shared_ptr< VarDeclNode > > &params)
Parse remaining formal parameters after the first one.
static std::shared_ptr< BlockNode > _parseFuncBody (std::vector< std::shared_ptr< VarDeclNode > > *localVars=nullptr)
Parse function body including local declarations and statements.
static std::vector< std::shared_ptr< VarDeclNode > > _parseLocalVarDeclList ()
Parse optional local declaration region inside function body.
static std::vector< std::shared_ptr< VarDeclNode > > _parseVarDeclList ()
Parse zero-or-more variable declarations with recovery.
static std::shared_ptr< VarDeclNode > _parseVarDecl (const std::string &visibility="local")
Parse variable declaration production.
Statement Parsing
Parse executable statements and statement blocks.
Identifier-leading statements are disambiguated through tail routines because they may represent calls, assignments, or member chains.
static std::vector< std::shared_ptr< ASTNode > > _parseStatementList ()
Parse statement list with panic-mode recovery.
static std::shared_ptr< ASTNode > _parseStatement ()
Parse one executable statement.
static std::shared_ptr< ASTNode > _parseStatBlock ()
Parse statement block (single statement or do-end block).
static StatementIdTailResult _parseStatementIdTail (const std::shared_ptr< ASTNode > &lhsBase)
Parse statement identifier tail (indices + rest disambiguation).
static std::shared_ptr< ASTNode > _parseStatementRest (const std::shared_ptr< ASTNode > &lhsBase)
Parse continuation after identifier-led statement start.
static std::shared_ptr< ASTNode > _parseStatementCallTail (const std::shared_ptr< ASTNode > &callOrMember)
Parse statement call tail for chained member call statements.
static bool _parseAssignOp ()
Expression Parsing
Parse expressions by precedence tiers.
Expression parsing is layered (factor -> term -> arith -> relational) to encode precedence and associativity while constructing AST operator nodes.
static std::shared_ptr< ASTNode > _parseExpr ()
Parse expression non-terminal.
static std::shared_ptr< ASTNode > _parseExprTail (const std::shared_ptr< ASTNode > &left)
Parse optional relational tail after arithmetic expression.
static std::shared_ptr< ASTNode > _parseRelExpr ()
Parse relational expression with explicit operator.
static std::shared_ptr< ASTNode > _parseArithExpr ()
Parse arithmetic expression tier.
static std::shared_ptr< ASTNode > _parseAddOpTail (std::shared_ptr< ASTNode > left)
Parse additive tail with left-associative folding.
static std::shared_ptr< ASTNode > _parseTerm ()
Parse term non-terminal.
static std::shared_ptr< ASTNode > _parseMultOpTail (std::shared_ptr< ASTNode > left)
Parse multiplicative tail with left-associative folding.
static std::shared_ptr< ASTNode > _parseFactor ()
Parse factor non-terminal.
static std::shared_ptr< ASTNode > _parseFactorIdTail (const std::shared_ptr< ASTNode > &baseId)
Parse factor identifier tail: indices followed by rest chain.
static std::shared_ptr< ASTNode > _parseFactorRest (const std::shared_ptr< ASTNode > &base)
Parse continuation after factor base (dot/call/epsilon).
static std::shared_ptr< ASTNode > _parseFactorCallTail (const std::shared_ptr< ASTNode > &base)
Parse chained member access after a call/factor base.
static std::shared_ptr< ASTNode > _parseVariable ()
Parse variable non-terminal (id plus optional tails).
Parameters and Array Dimensions
Parse formal/actual parameter lists and array dimension/index lists.
Why?
Arrays and parameters recur across declarations and expressions, so these helpers centralize grammar behavior and reduce duplicated edge cases.
static std::vector< std::shared_ptr< ASTNode > > _parseAParams ()
Parse actual argument list for function calls.
static void _parseAParamsTail (std::vector< std::shared_ptr< ASTNode > > &params)
Parse remaining actual arguments after first expression.
static std::vector< std::shared_ptr< ASTNode > > _parseIndiceList ()
Parse zero-or-more index operations for member/array access.
static std::shared_ptr< ASTNode > _parseIndice ()
Parse one indexing expression inside brackets.
static std::vector< int > _parseArraySizeList ()
Parse zero-or-more array dimensions.
static int _parseArraySize ()
Parse one array-size production.
static int _parseArraySizeTail ()
Parse array-size tail after opening bracket.
Error Recovery and Diagnostics
Helpers for panic-mode synchronization and syntax diagnostics.
These methods implement a fail-fast local strategy with recovery at higher grammar boundaries.
Why?
Without recovery, recursive-descent parsers often stop at the first error; panic-mode improves usability by surfacing multiple syntax issues.
What comes next?
Follow sets can be refined as grammar evolves to reduce skipped regions.
static std::vector< std::string > _errorMessages
Collected parser error messages.
static std::vector< std::string > _derivationSteps
Derivation trace used for parser debugging/output artifacts.
static std::shared_ptr< ProgNode > _astRoot = nullptr
AST root produced by latest parse run.
static void _skipUntil (const std::vector< Token::Type > &followSet)
Synchronize parser cursor to the next token in a follow set.
static std::string _formatError (const std::string &message, const Token &token, const std::vector< Token::Type > &expectedTokens)
Format parser error message with lookahead and expected set.
static void _reportError (const std::string &message, const std::vector< Token::Type > &expectedTokens)
Record syntax error then throw control-flow exception.
Parser Runtime State
Token cursor, lookahead, and shared parser context.
Why?
Predictive parsing requires one-token lookahead and explicit cursor control.
What comes next?
This state can be encapsulated in a context object if parser reentrancy becomes a requirement.
static Token _lookaheadToken
Static lookahead token state for predictive parsing.
static int _currentTokenIndex = 0
Current index into flattened token stream.
static bool _inErrorRecoveryMode = false
Panic-mode guard to suppress cascading duplicate errors.
static std::vector< std::vector< Token > > _tokens
Original per-line token matrix from lexer.
static std::vector< Token > _flatTokens
Flattened token stream consumed by recursive-descent routines.
static bool _nextToken ()
Advance lookahead to next non-comment token.
static void _match (Token::Type expectedType)
Consume expected token or trigger panic-mode error path.
Operator Parsing
Parse operator terminals and optionally return concrete lexemes.
These methods expose lexemes so AST operators preserve source-level symbols for semantic analysis and later diagnostics.
static bool _parseRelOp (std::string *opLexeme=nullptr)
static bool _parseAddOp (std::string *opLexeme=nullptr)
static bool _parseMultOp (std::string *opLexeme=nullptr)
static bool _parseSign (std::string *signLexeme=nullptr)
Parser ()
Construct parser facade object.
~Parser ()
Destroy parser facade object.
bool parseProgram (std::string token_filepath)
Parse tokens from a token artifact file path.
static bool parseTokens (const std::vector< std::vector< Token > > &tokens)
Parse lexer-produced tokens directly (preferred in-memory path).
static std::shared_ptr< ProgNode > getASTRoot ()
Retrieve the parser-produced AST root.
static const std::vector< std::string > & getErrorMessages ()
Retrieve accumulated syntax error messages.
static const std::vector< std::string > & getDerivationSteps ()
Retrieve grammar derivation trace.
Detailed Description
LL(1) recursive-descent parser with panic-mode recovery and AST construction.
The parser consumes a flattened token stream and applies grammar productions as dedicated methods. It records derivation steps and syntax errors while continuing parsing when possible.
Why static state?
Static parser state simplifies mapping from grammar productions to methods and supports existing assignment tooling that expects global parser outputs.
What comes next?
For larger projects, these static members can be migrated into instance state so multiple parser contexts can run concurrently in tests.
Definition at line 65 of file my_parser.h.
Constructor & Destructor Documentation
Parser()
Parser::Parser ()
Construct parser facade object.
~Parser()
Parser::~Parser ()
Destroy parser facade object.
Member Function Documentation
_formatError()
std::string Parser::_formatError (const std::string & message, const Token & token, const std::vector< Token::Type > & expectedTokens) static private
Format parser error message with lookahead and expected set.
Parameters
message High-level error description.
token Current lookahead token.
expectedTokens Expected token classes.
Returns
Fully formatted diagnostic string.
Definition at line 162 of file my_parser.cpp.
References Token::getLineNumber(), Token::getTypeString(), and Token::toString().
Referenced by _reportError().
_match()
void Parser::_match (Token::Type expectedType) static private
Consume expected token or trigger panic-mode error path.
Parameters
expectedType Token class required by current production.
Definition at line 193 of file my_parser.cpp.
References _inErrorRecoveryMode, _nextToken(), _reportError(), and LTTYPE.
Referenced by _parseAddOp(), _parseAParamsTail(), _parseArraySize(), _parseArraySizeTail(), _parseAssignOp(), _parseClassDecl(), _parseFactor(), _parseFactorCallTail(), _parseFactorRest(), _parseFParams(), _parseFParamsTail(), _parseFuncBody(), _parseFuncHead(), _parseFuncHeadTail(), _parseIndice(), _parseInheritanceOpt(), _parseInheritsList(), _parseLocalVarDeclList(), _parseMemberDecl(), _parseMemberDeclIdTail(), _parseMemberDeclTypeTail(), _parseMultOp(), _parseProgram(), _parseRelOp(), _parseReturnType(), _parseSign(), _parseStatBlock(), _parseStatement(), _parseStatementCallTail(), _parseStatementRest(), _parseType(), _parseVarDecl(), _parseVariable(), and _parseVisibility().
_nextToken()
bool Parser::_nextToken () static private
Advance lookahead to next non-comment token.
Returns
True when a next token was loaded, false at end of stream.
Comment tokens are skipped here so production logic only sees grammar-relevant terminals.
Definition at line 51 of file my_parser.cpp.
References _currentTokenIndex, _flatTokens, _lookaheadToken, _nextToken(), and LTTYPE.
Referenced by _match(), _nextToken(), and parseTokens().
_parseAddOp()
bool Parser::_parseAddOp (std::string * opLexeme = nullptr) static private
Parse additive-level operator terminal.
Parameters
opLexeme Optional output of source lexeme.
Returns
True if additive operator was consumed.
Definition at line 284 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), and LTTYPE.
Referenced by _parseAddOpTail().
_parseAddOpTail()
std::shared_ptr< ASTNode > Parser::_parseAddOpTail (std::shared_ptr< ASTNode > left) static private
Parse additive tail with left-associative folding.
Parameters
left Left operand AST accumulated so far.
Returns
Folded AST subtree.
Definition at line 771 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _parseAddOp(), _parseTerm(), Token::getLineNumber(), and LTTYPE.
Referenced by _parseArithExpr().
_parseAParams()
std::vector< std::shared_ptr< ASTNode > > Parser::_parseAParams () static private
Parse actual argument list for function calls.
Returns
Vector of argument expression nodes.
Definition at line 550 of file my_parser.cpp.
References _derivationSteps, _parseAParamsTail(), _parseExpr(), and LTTYPE.
Referenced by _parseFactorRest(), and _parseStatementRest().
_parseAParamsTail()
void Parser::_parseAParamsTail (std::vector< std::shared_ptr< ASTNode > > & params) static private
Parse remaining actual arguments after first expression.
Parameters
params In/out argument list accumulator.
Definition at line 530 of file my_parser.cpp.
References _derivationSteps, _match(), _parseAParamsTail(), _parseExpr(), and LTTYPE.
Referenced by _parseAParams(), and _parseAParamsTail().
_parseArithExpr()
std::shared_ptr< ASTNode > Parser::_parseArithExpr () static private
Parse arithmetic expression tier.
Returns
Arithmetic AST node.
Definition at line 788 of file my_parser.cpp.
References _derivationSteps, _parseAddOpTail(), and _parseTerm().
Referenced by _parseExpr(), _parseExprTail(), _parseFactor(), and _parseRelExpr().
_parseArraySize()
int Parser::_parseArraySize () static private
Parse one array-size production.
Returns
Parsed dimension size (or sentinel for unsized).
Definition at line 461 of file my_parser.cpp.
References _derivationSteps, _match(), and _parseArraySizeTail().
Referenced by _parseArraySizeList().
_parseArraySizeList()
std::vector< int > Parser::_parseArraySizeList () static private
Parse zero-or-more array dimensions.
Returns
Ordered list of parsed dimensions.
Definition at line 473 of file my_parser.cpp.
References _derivationSteps, _parseArraySize(), _parseArraySizeList(), and LTTYPE.
Referenced by _parseArraySizeList(), _parseFParams(), _parseFParamsTail(), _parseMemberDeclIdTail(), _parseMemberDeclTypeTail(), and _parseVarDecl().
_parseArraySizeTail()
int Parser::_parseArraySizeTail () static private
Parse array-size tail after opening bracket.
Returns
Declared dimension value, or -1 for unsized dimension.
Definition at line 434 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), _reportError(), Token::getValue(), and LTTYPE.
Referenced by _parseArraySize().
_parseAssignOp()
bool Parser::_parseAssignOp () static private
Parse assignment operator token.
Returns
True when assignment token was consumed.
Definition at line 386 of file my_parser.cpp.
References _derivationSteps, _match(), and LTTYPE.
Referenced by _parseStatementRest().
_parseClassBody()
std::vector< std::shared_ptr< ASTNode > > Parser::_parseClassBody () static private
Parse class body sequence.
Returns
Vector of member declarations.
Definition at line 1509 of file my_parser.cpp.
References _derivationSteps, _inErrorRecoveryMode, _parseClassMemberDecl(), _skipUntil(), and LTTYPE.
Referenced by _parseClassDecl().
_parseClassDecl()
std::shared_ptr< ClassDeclNode > Parser::_parseClassDecl () static private
Parse class declaration.
Returns
Class declaration node.
Definition at line 1581 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), _parseClassBody(), _parseInheritanceOpt(), Token::getLineNumber(), and Token::getValue().
Referenced by _parseClassDeclList().
_parseClassDeclList()
std::vector< std::shared_ptr< ClassDeclNode > > Parser::_parseClassDeclList () static private
Parse top-level class declaration list with recovery.
Returns
Vector of class declarations.
Definition at line 1630 of file my_parser.cpp.
References _derivationSteps, _inErrorRecoveryMode, _parseClassDecl(), _skipUntil(), and LTTYPE.
Referenced by _parseProgram().
_parseClassMemberDecl()
std::shared_ptr< ASTNode > Parser::_parseClassMemberDecl () static private
Parse one class member declaration with leading visibility.
Returns
Member declaration node.
Definition at line 1499 of file my_parser.cpp.
References _derivationSteps, _parseMemberDecl(), and _parseVisibility().
Referenced by _parseClassBody().
_parseExpr()
std::shared_ptr< ASTNode > Parser::_parseExpr () static private
Parse expression non-terminal.
Returns
Expression AST node.
Definition at line 833 of file my_parser.cpp.
References _derivationSteps, _parseArithExpr(), and _parseExprTail().
Referenced by _parseAParams(), _parseAParamsTail(), _parseIndice(), _parseStatement(), and _parseStatementRest().
_parseExprTail()
std::shared_ptr< ASTNode > Parser::_parseExprTail (const std::shared_ptr< ASTNode > & left) static private
Parse optional relational tail after arithmetic expression.
Parameters
left Left arithmetic expression.
Returns
Relational node or original left node.
Definition at line 815 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _parseArithExpr(), _parseRelOp(), and Token::getLineNumber().
Referenced by _parseExpr().
_parseFactor()
std::shared_ptr< ASTNode > Parser::_parseFactor () static private
Parse factor non-terminal.
Returns
Factor AST node.
Definition at line 676 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), _parseArithExpr(), _parseFactor(), _parseFactorIdTail(), _parseSign(), _reportError(), Token::getLineNumber(), Token::getValue(), and LTTYPE.
Referenced by _parseFactor(), _parseMultOpTail(), and _parseTerm().
_parseFactorCallTail()
std::shared_ptr< ASTNode > Parser::_parseFactorCallTail (const std::shared_ptr< ASTNode > & base) static private
Parse chained member access after a call/factor base.
Parameters
base Current left-side AST node.
Returns
Extended AST chain.
Definition at line 585 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), _parseFactorIdTail(), Token::getLineNumber(), Token::getValue(), and LTTYPE.
Referenced by _parseFactorRest().
_parseFactorIdTail()
std::shared_ptr< ASTNode > Parser::_parseFactorIdTail (const std::shared_ptr< ASTNode > & baseId) static private
Parse factor identifier tail: indices followed by rest chain.
Parameters
baseId Identifier-origin base node.
Returns
Final factor AST node.
Definition at line 651 of file my_parser.cpp.
References _derivationSteps, _parseFactorRest(), and _parseIndiceList().
Referenced by _parseFactor(), _parseFactorCallTail(), _parseFactorRest(), and _parseVariable().
_parseFactorRest()
std::shared_ptr< ASTNode > Parser::_parseFactorRest (const std::shared_ptr< ASTNode > & base) static private
Parse continuation after factor base (dot/call/epsilon).
Parameters
base Current base node.
Returns
Final factor AST node.
Definition at line 608 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), _parseAParams(), _parseFactorCallTail(), _parseFactorIdTail(), Token::getLineNumber(), Token::getValue(), and LTTYPE.
Referenced by _parseFactorIdTail().
_parseFParams()
std::vector< std::shared_ptr< VarDeclNode > > Parser::_parseFParams () static private
Parse formal parameter list in function/method signatures.
Returns
Vector of formal parameter declaration nodes.
Definition at line 1221 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), _parseArraySizeList(), _parseFParamsTail(), _parseType(), Token::getLineNumber(), and Token::getValue().
Referenced by _parseFuncHeadTail(), _parseMemberDeclIdTail(), and _parseMemberDeclTypeTail().
_parseFParamsTail()
void Parser::_parseFParamsTail (std::vector< std::shared_ptr< VarDeclNode > > & params) static private
Parse remaining formal parameters after the first one.
Parameters
params In/out parameter declaration accumulator.
Definition at line 1189 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), _parseArraySizeList(), _parseFParamsTail(), _parseType(), _reportError(), Token::getLineNumber(), Token::getValue(), and LTTYPE.
Referenced by _parseFParams(), and _parseFParamsTail().
_parseFuncBody()
std::shared_ptr< BlockNode > Parser::_parseFuncBody (std::vector< std::shared_ptr< VarDeclNode > > * localVars = nullptr) static private
Parse function body including local declarations and statements.
Parameters
localVars Optional output pointer for parsed local declarations.
Returns
Block node containing locals and statements.
Definition at line 1162 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), _parseLocalVarDeclList(), and _parseStatementList().
Referenced by _parseFuncDef(), and _parseProgram().
_parseFuncDef()
std::shared_ptr< FuncDefNode > Parser::_parseFuncDef () static private
Parse complete function definition.
Returns
Function definition AST node.
Definition at line 1317 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _parseFuncBody(), _parseFuncHead(), _reportError(), Parser::FuncHeadInfo::className, LTTYPE, Parser::FuncHeadInfo::name, Parser::FuncHeadInfo::params, and Parser::FuncHeadInfo::returnType.
Referenced by _parseFuncDefList().
_parseFuncDefList()
std::vector< std::shared_ptr< FuncDefNode > > Parser::_parseFuncDefList () static private
Parse top-level function definition list with recovery.
Returns
Vector of function definitions.
Definition at line 1606 of file my_parser.cpp.
References _derivationSteps, _inErrorRecoveryMode, _parseFuncDef(), _skipUntil(), and LTTYPE.
Referenced by _parseProgram().
_parseFuncHead()
Parser::FuncHeadInfo Parser::_parseFuncHead () static private
Parse function head (name, params, optional class qualifier, return type).
Returns
Aggregated function-head information.
Definition at line 1303 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), _parseFuncHeadTail(), Token::getLineNumber(), Token::getValue(), and Parser::FuncHeadInfo::name.
Referenced by _parseFuncDef().
_parseFuncHeadTail()
void Parser::_parseFuncHeadTail (FuncHeadInfo & info, int headLine) static private
Parse function-head tail for free function or class-qualified method.
Parameters
info In/out function-head aggregate information.
headLine Source line where head started.
Definition at line 1271 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), _parseFParams(), _parseReturnType(), _reportError(), Parser::FuncHeadInfo::className, Token::getValue(), LTTYPE, Parser::FuncHeadInfo::name, Parser::FuncHeadInfo::params, and Parser::FuncHeadInfo::returnType.
Referenced by _parseFuncHead().
_parseIndice()
std::shared_ptr< ASTNode > Parser::_parseIndice () static private
Parse one indexing expression inside brackets.
Returns
AST node for index expression.
Definition at line 496 of file my_parser.cpp.
References _derivationSteps, _match(), and _parseExpr().
Referenced by _parseIndiceList().
_parseIndiceList()
std::vector< std::shared_ptr< ASTNode > > Parser::_parseIndiceList () static private
Parse zero-or-more index operations for member/array access.
Returns
List of index expression nodes.
Definition at line 509 of file my_parser.cpp.
References _derivationSteps, _parseIndice(), _parseIndiceList(), and LTTYPE.
Referenced by _parseFactorIdTail(), _parseIndiceList(), and _parseStatementIdTail().
_parseInheritanceOpt()
std::vector< std::string > Parser::_parseInheritanceOpt () static private
Parse optional inheritance clause.
Returns
Parent class names (possibly empty).
Definition at line 1558 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), _parseInheritsList(), Token::getValue(), and LTTYPE.
Referenced by _parseClassDecl().
_parseInheritsList()
std::vector< std::string > Parser::_parseInheritsList () static private
Parse trailing inherited-class list.
Returns
Additional parent class names.
Definition at line 1534 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), _parseInheritsList(), Token::getValue(), and LTTYPE.
Referenced by _parseInheritanceOpt(), and _parseInheritsList().
_parseLocalVarDeclList()
std::vector< std::shared_ptr< VarDeclNode > > Parser::_parseLocalVarDeclList () static private
Parse optional local declaration region inside function body.
Returns
Vector of local declarations (possibly empty).
Definition at line 1144 of file my_parser.cpp.
References _derivationSteps, _match(), _parseVarDeclList(), and LTTYPE.
Referenced by _parseFuncBody().
_parseMemberDecl()
std::shared_ptr< ASTNode > Parser::_parseMemberDecl (const std::string & visibility) static private
Parse class member declaration entry point.
Parameters
visibility Visibility modifier from preceding production.
Returns
Member declaration AST node.
Definition at line 1446 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), _parseMemberDeclIdTail(), _parseMemberDeclTypeTail(), _parseType(), _reportError(), Token::getLineNumber(), Token::getValue(), and LTTYPE.
Referenced by _parseClassMemberDecl().
_parseMemberDeclIdTail()
std::shared_ptr< ASTNode > Parser::_parseMemberDeclIdTail (const std::string & memberName, const std::string & visibility, int line) static private
Parse member declaration tail when first token was identifier.
Parameters
memberName First identifier lexeme (type or member name context).
visibility Visibility modifier.
line Source line.
Returns
Member declaration node.
Definition at line 1347 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), _parseArraySizeList(), _parseFParams(), _parseReturnType(), and LTTYPE.
Referenced by _parseMemberDecl().
_parseMemberDeclTypeTail()
std::shared_ptr< ASTNode > Parser::_parseMemberDeclTypeTail (const std::string & typeName, const std::string & memberName, const std::string & visibility, int line) static private
Parse member declaration tail when explicit type token started declaration.
Parameters
typeName Parsed member type.
memberName Parsed member/function name.
visibility Visibility modifier.
line Source line.
Returns
Member declaration node.
Definition at line 1408 of file my_parser.cpp.
References _derivationSteps, _match(), _parseArraySizeList(), _parseFParams(), _parseReturnType(), and LTTYPE.
Referenced by _parseMemberDecl().
_parseMultOp()
bool Parser::_parseMultOp (std::string * opLexeme = nullptr) static private
Parse multiplicative-level operator terminal.
Parameters
opLexeme Optional output of source lexeme.
Returns
True if multiplicative operator was consumed.
Definition at line 320 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), and LTTYPE.
Referenced by _parseMultOpTail().
_parseMultOpTail()
std::shared_ptr< ASTNode > Parser::_parseMultOpTail (std::shared_ptr< ASTNode > left) static private
Parse multiplicative tail with left-associative folding.
Parameters
left Left operand AST accumulated so far.
Returns
Folded AST subtree.
Definition at line 742 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _parseFactor(), _parseMultOp(), Token::getLineNumber(), and LTTYPE.
Referenced by _parseTerm().
_parseProgram()
std::shared_ptr< ProgNode > Parser::_parseProgram () static private
Parse complete program grammar entry point.
Returns
Program AST root node.
Program parse proceeds in phases: class list, function list, then mandatory main body. Each phase is recoverable to maximize diagnostics in one run.
Definition at line 1658 of file my_parser.cpp.
References _derivationSteps, _inErrorRecoveryMode, _lookaheadToken, _match(), _parseClassDeclList(), _parseFuncBody(), _parseFuncDefList(), _skipUntil(), and Token::getLineNumber().
Referenced by parseTokens().
_parseRelExpr()
std::shared_ptr< ASTNode > Parser::_parseRelExpr () static private
Parse relational expression with explicit operator.
Returns
Relational AST node.
Definition at line 798 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _parseArithExpr(), _parseRelOp(), _reportError(), and Token::getLineNumber().
Referenced by _parseStatement().
_parseRelOp()
bool Parser::_parseRelOp (std::string * opLexeme = nullptr) static private
Parse relational operator terminal.
Parameters
opLexeme Optional output of source lexeme.
Returns
True if a relational operator was consumed.
Definition at line 227 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), and LTTYPE.
Referenced by _parseExprTail(), and _parseRelExpr().
_parseReturnType()
std::string Parser::_parseReturnType () static private
Parse function return type non-terminal.
Returns
Canonical return type string.
Definition at line 1249 of file my_parser.cpp.
References _derivationSteps, _match(), _parseType(), _reportError(), and LTTYPE.
Referenced by _parseFuncHeadTail(), _parseMemberDeclIdTail(), and _parseMemberDeclTypeTail().
_parseSign()
bool Parser::_parseSign (std::string * signLexeme = nullptr) static private
Parse unary sign operator.
Parameters
signLexeme Optional output of sign lexeme.
Returns
True if unary sign was consumed.
Definition at line 357 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), and LTTYPE.
Referenced by _parseFactor().
_parseStatBlock()
std::shared_ptr< ASTNode > Parser::_parseStatBlock () static private
Parse statement block (single statement or do-end block).
Returns
Block/statement AST node.
Definition at line 950 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), _parseStatement(), _parseStatementList(), and LTTYPE.
Referenced by _parseStatement().
_parseStatement()
std::shared_ptr< ASTNode > Parser::_parseStatement () static private
Parse one executable statement.
Returns
Statement AST node or nullptr for epsilon context.
Definition at line 979 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), _parseExpr(), _parseRelExpr(), _parseStatBlock(), _parseStatementIdTail(), _parseVariable(), Parser::StatementIdTailResult::base, Token::getLineNumber(), Token::getValue(), LTTYPE, and Parser::StatementIdTailResult::statementNode.
Referenced by _parseStatBlock(), and _parseStatementList().
_parseStatementCallTail()
std::shared_ptr< ASTNode > Parser::_parseStatementCallTail (const std::shared_ptr< ASTNode > & callOrMember) static private
Parse statement call tail for chained member call statements.
Parameters
callOrMember Existing call/member base.
Returns
Completed statement/call AST node.
Definition at line 844 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), _parseStatementIdTail(), _reportError(), Parser::StatementIdTailResult::base, Token::getLineNumber(), Token::getValue(), LTTYPE, and Parser::StatementIdTailResult::statementNode.
Referenced by _parseStatementRest().
_parseStatementIdTail()
Parser::StatementIdTailResult Parser::_parseStatementIdTail (const std::shared_ptr< ASTNode > & lhsBase) static private
Parse statement identifier tail (indices + rest disambiguation).
Parameters
lhsBase Base identifier/member node.
Returns
Pair of evolved base node and optional statement node.
Definition at line 924 of file my_parser.cpp.
References _derivationSteps, _parseIndiceList(), and _parseStatementRest().
Referenced by _parseStatement(), _parseStatementCallTail(), and _parseStatementRest().
_parseStatementList()
std::vector< std::shared_ptr< ASTNode > > Parser::_parseStatementList () static private
Parse statement list with panic-mode recovery.
Returns
Vector of parsed statement nodes.
Definition at line 1067 of file my_parser.cpp.
References _derivationSteps, _inErrorRecoveryMode, _parseStatement(), and _skipUntil().
Referenced by _parseFuncBody(), and _parseStatBlock().
_parseStatementRest()
std::shared_ptr< ASTNode > Parser::_parseStatementRest (const std::shared_ptr< ASTNode > & lhsBase) static private
Parse continuation after identifier-led statement start.
Parameters
lhsBase Left-hand base expression.
Returns
Statement AST node.
Definition at line 875 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), _parseAParams(), _parseAssignOp(), _parseExpr(), _parseStatementCallTail(), _parseStatementIdTail(), _reportError(), Parser::StatementIdTailResult::base, Token::getLineNumber(), Token::getValue(), LTTYPE, and Parser::StatementIdTailResult::statementNode.
Referenced by _parseStatementIdTail().
_parseTerm()
std::shared_ptr< ASTNode > Parser::_parseTerm () static private
Parse term non-terminal.
Returns
Term AST node.
Definition at line 760 of file my_parser.cpp.
References _derivationSteps, _parseFactor(), and _parseMultOpTail().
Referenced by _parseAddOpTail(), and _parseArithExpr().
_parseType()
std::shared_ptr< TypeNode > Parser::_parseType () static private
Parse type non-terminal (built-ins or class identifier).
Returns
Parsed TypeNode or nullptr on epsilon/non-type lookahead.
Definition at line 400 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), Token::getLineNumber(), Token::getValue(), and LTTYPE.
Referenced by _parseFParams(), _parseFParamsTail(), _parseMemberDecl(), _parseReturnType(), and _parseVarDecl().
_parseVarDecl()
std::shared_ptr< VarDeclNode > Parser::_parseVarDecl (const std::string & visibility = "local") static private
Parse variable declaration production.
Parameters
visibility Visibility/locality tag to attach to declaration.
Returns
VarDeclNode or nullptr when no declaration is present.
Definition at line 1095 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), _parseArraySizeList(), _parseType(), Token::getLineNumber(), and Token::getValue().
Referenced by _parseVarDeclList().
_parseVarDeclList()
std::vector< std::shared_ptr< VarDeclNode > > Parser::_parseVarDeclList () static private
Parse zero-or-more variable declarations with recovery.
Returns
Vector of variable declaration nodes.
Definition at line 1118 of file my_parser.cpp.
References _derivationSteps, _inErrorRecoveryMode, _parseVarDecl(), and _skipUntil().
Referenced by _parseLocalVarDeclList().
_parseVariable()
std::shared_ptr< ASTNode > Parser::_parseVariable () static private
Parse variable non-terminal (id plus optional tails).
Returns
Variable/member access AST node.
Definition at line 572 of file my_parser.cpp.
References _derivationSteps, _lookaheadToken, _match(), _parseFactorIdTail(), Token::getLineNumber(), and Token::getValue().
Referenced by _parseStatement().
_parseVisibility()
std::string Parser::_parseVisibility () static private
Parse visibility modifier.
Returns
Visibility string (public/private).
Definition at line 1478 of file my_parser.cpp.
References _derivationSteps, _match(), _reportError(), and LTTYPE.
Referenced by _parseClassMemberDecl().
_reportError()
void Parser::_reportError (const std::string & message, const std::vector< Token::Type > & expectedTokens) static private
Record syntax error then throw control-flow exception.
Parameters
message Error summary.
expectedTokens Expected token classes at this point.
Exceptions
SyntaxError Always thrown after message registration.
Definition at line 183 of file my_parser.cpp.
References _errorMessages, _formatError(), and _lookaheadToken.
Referenced by _match(), _parseArraySizeTail(), _parseFactor(), _parseFParamsTail(), _parseFuncDef(), _parseFuncHeadTail(), _parseMemberDecl(), _parseRelExpr(), _parseReturnType(), _parseStatementCallTail(), _parseStatementRest(), and _parseVisibility().
_skipUntil()
void Parser::_skipUntil (const std::vector< Token::Type > & followSet) static private
Synchronize parser cursor to the next token in a follow set.
Parameters
followSet Recovery token set for current grammar context.
Used by panic-mode recovery after syntax errors to resume parsing from a stable boundary and continue collecting diagnostics.
Definition at line 75 of file my_parser.cpp.
References _currentTokenIndex, _flatTokens, _lookaheadToken, and LTTYPE.
Referenced by _parseClassBody(), _parseClassDeclList(), _parseFuncDefList(), _parseProgram(), _parseStatementList(), and _parseVarDeclList().
getASTRoot()
std::shared_ptr< ProgNode > Parser::getASTRoot () static
Retrieve the parser-produced AST root.
Return AST root produced by most recent parse.
Returns
Program AST root or nullptr if parsing failed.
Program AST root or nullptr when unavailable.
Definition at line 135 of file my_parser.cpp.
References _astRoot.
Referenced by main().
getDerivationSteps()
const std::vector< std::string > & Parser::getDerivationSteps () static
Retrieve grammar derivation trace.
Return derivation trace for grammar debugging/output.
Returns
Read-only list of derivation steps.
Useful for debugging grammar transitions and assignment deliverables.
Returns
Read-only derivation step list.
Definition at line 151 of file my_parser.cpp.
References _derivationSteps.
Referenced by main().
getErrorMessages()
const std::vector< std::string > & Parser::getErrorMessages () static
Retrieve accumulated syntax error messages.
Return collected syntax diagnostics.
Returns
Read-only list of parser error messages.
Read-only syntax error message list.
Definition at line 143 of file my_parser.cpp.
References _errorMessages.
Referenced by main().
parseProgram()
bool Parser::parseProgram (std::string token_filepath)
Parse tokens from a token artifact file path.
Parameters
token_filepath Path to token input artifact.
Returns
True if parsing completed with no syntax errors.
Kept for compatibility with file-based workflow tooling.
parseTokens()
bool Parser::parseTokens (const std::vector< std::vector< Token > > & tokens) static
Parse lexer-produced tokens directly (preferred in-memory path).
Parse lexer tokens provided in memory and build AST.
Parameters
tokens Token stream grouped by source line.
Returns
True if syntax parsing completed without errors.
Why?
This avoids re-parsing text artifacts and preserves exact lexer token data.
What comes next?
On success, call getASTRoot() and forward AST to semantic analysis.
Parameters
tokens Token stream grouped by line.
Returns
True if parsing completed without syntax errors.
Definition at line 101 of file my_parser.cpp.
References _astRoot, _currentTokenIndex, _derivationSteps, _errorMessages, _flatTokens, _inErrorRecoveryMode, _nextToken(), _parseProgram(), and _tokens.
Referenced by main().
Member Data Documentation
_astRoot
std::shared_ptr< ProgNode > Parser::_astRoot = nullptr static private
AST root produced by latest parse run.
Definition at line 126 of file my_parser.h.
Referenced by getASTRoot(), and parseTokens().
_currentTokenIndex
int Parser::_currentTokenIndex = 0 static private
Current index into flattened token stream.
Definition at line 149 of file my_parser.h.
Referenced by _nextToken(), _skipUntil(), and parseTokens().
_derivationSteps
std::vector< std::string > Parser::_derivationSteps static private
Derivation trace used for parser debugging/output artifacts.
Definition at line 124 of file my_parser.h.
Referenced by _parseAddOp(), _parseAddOpTail(), _parseAParams(), _parseAParamsTail(), _parseArithExpr(), _parseArraySize(), _parseArraySizeList(), _parseArraySizeTail(), _parseAssignOp(), _parseClassBody(), _parseClassDecl(), _parseClassDeclList(), _parseClassMemberDecl(), _parseExpr(), _parseExprTail(), _parseFactor(), _parseFactorCallTail(), _parseFactorIdTail(), _parseFactorRest(), _parseFParams(), _parseFParamsTail(), _parseFuncBody(), _parseFuncDef(), _parseFuncDefList(), _parseFuncHead(), _parseFuncHeadTail(), _parseIndice(), _parseIndiceList(), _parseInheritanceOpt(), _parseInheritsList(), _parseLocalVarDeclList(), _parseMemberDecl(), _parseMemberDeclIdTail(), _parseMemberDeclTypeTail(), _parseMultOp(), _parseMultOpTail(), _parseProgram(), _parseRelExpr(), _parseRelOp(), _parseReturnType(), _parseSign(), _parseStatBlock(), _parseStatement(), _parseStatementCallTail(), _parseStatementIdTail(), _parseStatementList(), _parseStatementRest(), _parseTerm(), _parseType(), _parseVarDecl(), _parseVarDeclList(), _parseVariable(), _parseVisibility(), getDerivationSteps(), and parseTokens().
_errorMessages
std::vector< std::string > Parser::_errorMessages static private
Collected parser error messages.
Definition at line 122 of file my_parser.h.
Referenced by _reportError(), getErrorMessages(), and parseTokens().
_flatTokens
std::vector< Token > Parser::_flatTokens static private
Flattened token stream consumed by recursive-descent routines.
Definition at line 157 of file my_parser.h.
Referenced by _nextToken(), _skipUntil(), and parseTokens().
_inErrorRecoveryMode
bool Parser::_inErrorRecoveryMode = false static private
Panic-mode guard to suppress cascading duplicate errors.
Definition at line 153 of file my_parser.h.
Referenced by _match(), _parseClassBody(), _parseClassDeclList(), _parseFuncDefList(), _parseProgram(), _parseStatementList(), _parseVarDeclList(), and parseTokens().
_lookaheadToken
Token Parser::_lookaheadToken static private
Static lookahead token state for predictive parsing.
Definition at line 147 of file my_parser.h.
Referenced by _nextToken(), _parseAddOp(), _parseAddOpTail(), _parseArraySizeTail(), _parseClassDecl(), _parseExprTail(), _parseFactor(), _parseFactorCallTail(), _parseFactorRest(), _parseFParams(), _parseFParamsTail(), _parseFuncBody(), _parseFuncDef(), _parseFuncHead(), _parseFuncHeadTail(), _parseInheritanceOpt(), _parseInheritsList(), _parseMemberDecl(), _parseMemberDeclIdTail(), _parseMultOp(), _parseMultOpTail(), _parseProgram(), _parseRelExpr(), _parseRelOp(), _parseSign(), _parseStatBlock(), _parseStatement(), _parseStatementCallTail(), _parseStatementRest(), _parseType(), _parseVarDecl(), _parseVariable(), _reportError(), and _skipUntil().
_tokens
std::vector< std::vector< Token > > Parser::_tokens static private
Original per-line token matrix from lexer.
Definition at line 155 of file my_parser.h.
Referenced by parseTokens().
The documentation for this class was generated from the following files:
my_parser.h
my_parser.cpp