COMP442 Compiler: CodeGenVisitor Class Reference
CodeGenVisitor Class Reference
AST visitor that emits Moon assembly for the full program.
#include <codegen.h>
Classes
struct ClassLayoutInfo
Fully flattened class layout including inherited fields.
struct FieldLayoutInfo
Memory layout metadata for class fields.
struct FunctionLayoutInfo
Stack-frame and call metadata for a lowered function/method.
class RegisterAllocator
Simple pool allocator for Moon general-purpose temporaries.
struct StackVarInfo
Per-variable frame metadata for local/param lowering.
Public Member Functions
CodeGenVisitor (std::ostream &out)
Construct code generator with destination output stream.
bool generate (const std::shared_ptr< ProgNode > &root)
Generate Moon assembly from program AST root.
const std::vector< std::string > & getErrors () const
Get accumulated code generation diagnostics.
AST Visitor Overrides
void visit (IdNode &node) override
Lower identifier expression into register value load.
void visit (IntLitNode &node) override
Lower integer literal into immediate-loaded register.
void visit (FloatLitNode &node) override
Lower float literal into fixed-point integer immediate.
void visit (TypeNode &node) override
Type nodes are metadata-only and produce no runtime value.
void visit (BinaryOpNode &node) override
Lower binary expression with scalar/fixed-point operator selection.
void visit (UnaryOpNode &node) override
Lower unary operators (negation, logical not, unary plus passthrough).
void visit (FuncCallNode &node) override
Lower function or method call sequence.
void visit (DataMemberNode &node) override
Lower member access expression by address resolution then load.
void visit (AssignStmtNode &node) override
Lower assignment statement for scalar store or aggregate object copy.
void visit (IfStmtNode &node) override
Lower if/else control flow with generated branch labels.
void visit (WhileStmtNode &node) override
Lower while loop with explicit start/end labels and conditional branch.
void visit (IOStmtNode &node) override
Lower read/write statements through runtime helper routines.
void visit (ReturnStmtNode &node) override
Lower return statement and transfer result to return register.
void visit (BlockNode &node) override
Lower statement block by visiting statements in source order.
void visit (VarDeclNode &node) override
Variable declarations are layout-only and emit no direct instructions.
void visit (FuncDefNode &node) override
Function declarations are emitted centrally during program lowering.
void visit (ClassDeclNode &node) override
Class declaration node currently contributes layout metadata only.
void visit (ProgNode &node) override
Lower full program: collect layouts, emit main, emit non-main functions.
Public Member Functions inherited from ASTVisitor
virtual ~ASTVisitor ()=default
Virtual destructor for interface-safe polymorphic deletion.
Private Member Functions
void assignOffsets (const std::vector< std::shared_ptr< VarDeclNode > > &vars)
Assign stack offsets for variable declarations.
bool buildClassLayout (const std::string &className, std::unordered_set< std::string > &visiting, int line)
Build/cached class field layout.
bool buildFunctionLayout (const std::shared_ptr< FuncDefNode > &functionNode)
Build frame layout for one function/method.
void emit (const std::string &line)
Emit raw assembly line plus optional trace line.
int emitAddressForDataMember (DataMemberNode &node)
Emit address computation for data member chain/access.
int emitAddressForLValue (const std::shared_ptr< ASTNode > &node, int line)
Emit address computation for assignable l-value.
int emitAddressForObjectExpression (const std::shared_ptr< ASTNode > &node, int line)
Emit address for object expression used by object copy/call paths.
void emitComment (const std::string &message)
Emit comment line with readability filtering policy.
bool emitCopyWords (int dstAddrReg, int srcAddrReg, long byteCount, int line)
Emit word-wise memory copy loop for aggregate transfer.
void emitFunctionBody (const std::shared_ptr< FuncDefNode > &functionNode, const FunctionLayoutInfo &layout, bool isMainBody)
Emit full function body/prologue/epilogue from layout info.
bool emitIndexOffsetIntoAddress (int addrReg, const std::vector< std::shared_ptr< ASTNode > > &indices, const std::vector< int > &declaredDimensions, long elementSize, int line)
Emit array-index linearized offset into address register.
void emitRuntimeIntegerIO ()
Emit runtime helper routines for integer/float input-output.
void emitSourceLineContext (int line, const std::string &message)
Emit comment with source line context tag.
bool emitStoreTarget (const std::shared_ptr< ASTNode > &target, int valueReg)
Emit scalar store into assignment target.
int evalExpr (const std::shared_ptr< ASTNode > &node)
Evaluate expression and return result register.
const FunctionLayoutInfo * findFunctionLayout (const std::string &className, const std::string &functionName) const
Lookup prebuilt function layout by owner/name.
bool hasOffset (const std::string &name) const
Check whether active frame has named stack slot.
bool loadThisPointerInto (int targetReg, int line)
Load implicit receiver pointer into target register.
bool lookupFieldLayout (const std::string &className, const std::string &fieldName, FieldLayoutInfo &out, int line)
Lookup resolved field layout metadata in class layout.
long lookupOffset (const std::string &name) const
Lookup named stack offset in active frame.
std::string makeLabel (const std::string &prefix)
Build unique label from prefix.
void reportError (int line, const std::string &message)
Record formatted codegen diagnostic.
void resetFunctionState ()
Reset per-function emission state.
bool resolveDataMemberType (const std::shared_ptr< DataMemberNode > &node, std::string &typeName, std::vector< int > &dimensions)
Infer type info specifically for data-member access node.
bool resolveNodeType (const std::shared_ptr< ASTNode > &node, std::string &typeName, std::vector< int > &dimensions)
Infer type and dimensions for any expression node.
void setTraceContext (int line, const std::string &contextTag)
Set active trace context fields.
long sizeOfClass (const std::string &className, std::unordered_set< std::string > &visiting, int line)
Compute class byte size (with cycle-safe recursion).
long sizeOfType (const std::string &typeName, int line)
Compute byte size for scalar/class type.
long sizeOfVar (const std::shared_ptr< VarDeclNode > &decl)
Compute storage bytes for variable declaration.
Static Private Member Functions
static std::string functionKey (const std::string &className, const std::string &functionName)
Build canonical function key from class/function names.
static std::string sanitizeName (const std::string &raw)
Sanitize string for assembly-safe label token.
Private Attributes
std::unordered_map< std::string, std::shared_ptr< ClassDeclNode > > _classDecls
Class declarations indexed by name from AST root.
std::unordered_map< std::string, ClassLayoutInfo > _classLayouts
Cached class layouts.
std::unordered_map< std::string, long > _classSizes
Cached class sizes.
std::string _currentClassName
Current class name during method emission.
long _currentFrameSize = 0
Current frame size.
std::string _currentFunction
Current function name during emission.
std::string _currentReturnLabel
Current function return label.
std::string _currentReturnType
Current function return type.
long _currentThisOffset = 0
Current implicit receiver slot offset.
std::vector< std::string > _errors
Collected codegen errors.
std::unordered_map< std::string, FunctionLayoutInfo > _functionLayouts
Cached function frame layouts.
int _labelCounter = 0
Unique label counter.
int _lastExprReg = -1
Last expression result register.
long _nextOffset = 0
Active frame allocation cursor.
std::ostream & _out
Assembly output stream target.
RegisterAllocator _regs
Temporary register allocator.
std::unordered_map< std::string, long > _stackOffsets
Active frame offsets.
std::unordered_map< std::string, StackVarInfo > _stackVarInfo
Active frame variable metadata.
std::string _traceContextTag
Trace context tag.
long _traceEmitCounter = 0
Trace instruction counter.
int _traceSourceLine = 0
Trace source line context.
Detailed Description
AST visitor that emits Moon assembly for the full program.
Responsibilities include:
frame and class layout construction,
expression/type-driven instruction selection,
object/member/array address lowering,
runtime helper emission for integer/float I/O,
trace-aware assembly comments and diagnostics.
Definition at line 38 of file codegen.h.
Constructor & Destructor Documentation
CodeGenVisitor()
CodeGenVisitor::CodeGenVisitor (std::ostream & out) explicit
Construct code generator with destination output stream.
Construct backend with output stream sink.
Parameters
out Stream receiving emitted Moon assembly.
Definition at line 205 of file codegen.cpp.
References _out.
Member Function Documentation
assignOffsets()
void CodeGenVisitor::assignOffsets (const std::vector< std::shared_ptr< VarDeclNode > > & vars) private
Assign stack offsets for variable declarations.
Assign stack offsets and metadata for a set of declarations.
Definition at line 661 of file codegen.cpp.
References _nextOffset, _stackOffsets, _stackVarInfo, emitComment(), reportError(), sizeOfType(), and sizeOfVar().
buildClassLayout()
bool CodeGenVisitor::buildClassLayout (const std::string & className, std::unordered_set< std::string > & visiting, int line) private
Build/cached class field layout.
Build flattened class layout, including inherited fields.
The visitor tracks active recursion to detect storage dependency cycles and report clear diagnostics instead of silently producing invalid offsets.
Definition at line 506 of file codegen.cpp.
References _classDecls, _classLayouts, _classSizes, buildClassLayout(), CodeGenVisitor::FieldLayoutInfo::dimensions, CodeGenVisitor::ClassLayoutInfo::fields, CodeGenVisitor::FieldLayoutInfo::offset, reportError(), CodeGenVisitor::ClassLayoutInfo::size, CodeGenVisitor::FieldLayoutInfo::size, sizeOfVar(), and CodeGenVisitor::FieldLayoutInfo::typeName.
Referenced by buildClassLayout(), lookupFieldLayout(), sizeOfClass(), and visit().
buildFunctionLayout()
bool CodeGenVisitor::buildFunctionLayout (const std::shared_ptr< FuncDefNode > & functionNode) private
Build frame layout for one function/method.
Build and cache frame layout for a function or method.
Layout includes return link slot, optional receiver slot, parameter slots, local storage slots, and metadata used by argument/assignment lowering.
Definition at line 382 of file codegen.cpp.
References _functionLayouts, CodeGenVisitor::FunctionLayoutInfo::className, CodeGenVisitor::FunctionLayoutInfo::frameSize, functionKey(), CodeGenVisitor::FunctionLayoutInfo::isMethod, CodeGenVisitor::FunctionLayoutInfo::key, CodeGenVisitor::FunctionLayoutInfo::label, CodeGenVisitor::FunctionLayoutInfo::name, CodeGenVisitor::FunctionLayoutInfo::paramNames, CodeGenVisitor::FunctionLayoutInfo::paramOffsets, CodeGenVisitor::FunctionLayoutInfo::returnLinkOffset, CodeGenVisitor::FunctionLayoutInfo::returnType, sanitizeName(), sizeOfType(), sizeOfVar(), CodeGenVisitor::FunctionLayoutInfo::thisOffset, CodeGenVisitor::FunctionLayoutInfo::varInfo, and CodeGenVisitor::FunctionLayoutInfo::varOffsets.
Referenced by visit().
emit()
void CodeGenVisitor::emit (const std::string & line) private
Emit raw assembly line plus optional trace line.
Emit assembly line and optional instruction trace comment.
Non-comment instructions receive an auto-incrementing trace marker to make generated assembly easy to audit against source-line context.
Definition at line 254 of file codegen.cpp.
References _out, _traceContextTag, _traceEmitCounter, and _traceSourceLine.
Referenced by emitAddressForDataMember(), emitAddressForLValue(), emitComment(), emitCopyWords(), emitFunctionBody(), emitIndexOffsetIntoAddress(), emitRuntimeIntegerIO(), emitStoreTarget(), generate(), loadThisPointerInto(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
emitAddressForDataMember()
int CodeGenVisitor::emitAddressForDataMember (DataMemberNode & node) private
Emit address computation for data member chain/access.
Emit address for member/array-chain access.
Supports local/parameter variables, implicit receiver fields, and explicit owner expressions with recursive address construction.
Definition at line 1070 of file codegen.cpp.
References _currentClassName, _regs, _stackVarInfo, CodeGenVisitor::FieldLayoutInfo::dimensions, emit(), emitAddressForLValue(), emitIndexOffsetIntoAddress(), emitSourceLineContext(), DataMemberNode::getIndices(), ASTNode::getLeft(), ASTNode::getLineNumber(), DataMemberNode::getName(), hasOffset(), loadThisPointerInto(), lookupFieldLayout(), lookupOffset(), CodeGenVisitor::FieldLayoutInfo::offset, reportError(), resolveNodeType(), CodeGenVisitor::FieldLayoutInfo::size, sizeOfType(), and CodeGenVisitor::FieldLayoutInfo::typeName.
Referenced by emitAddressForLValue(), and visit().
emitAddressForLValue()
int CodeGenVisitor::emitAddressForLValue (const std::shared_ptr< ASTNode > & node, int line) private
Emit address computation for assignable l-value.
Emit l-value address for identifier or member target expression.
Definition at line 1000 of file codegen.cpp.
References _currentClassName, _regs, _stackVarInfo, emit(), emitAddressForDataMember(), emitSourceLineContext(), hasOffset(), loadThisPointerInto(), lookupFieldLayout(), lookupOffset(), CodeGenVisitor::FieldLayoutInfo::offset, and reportError().
Referenced by emitAddressForDataMember(), emitAddressForObjectExpression(), emitStoreTarget(), visit(), and visit().
emitAddressForObjectExpression()
int CodeGenVisitor::emitAddressForObjectExpression (const std::shared_ptr< ASTNode > & node, int line) private
Emit address for object expression used by object copy/call paths.
Emit address for expressions expected to denote aggregate objects.
Definition at line 1215 of file codegen.cpp.
References emitAddressForLValue(), evalExpr(), and reportError().
Referenced by visit(), visit(), and visit().
emitComment()
void CodeGenVisitor::emitComment (const std::string & message) private
Emit comment line with readability filtering policy.
Emit backend comment line with readability filtering.
Very high-frequency comment categories are suppressed to keep emitted assembly reviewable in assignment-scale test outputs.
Definition at line 285 of file codegen.cpp.
References emit().
Referenced by assignOffsets(), emitFunctionBody(), emitRuntimeIntegerIO(), emitSourceLineContext(), generate(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
emitCopyWords()
bool CodeGenVisitor::emitCopyWords (int dstAddrReg, int srcAddrReg, long byteCount, int line) private
Emit word-wise memory copy loop for aggregate transfer.
Emit word-wise memory copy used by object assignment and argument passing.
Definition at line 1235 of file codegen.cpp.
References _regs, emit(), emitSourceLineContext(), and reportError().
Referenced by visit(), and visit().
emitFunctionBody()
void CodeGenVisitor::emitFunctionBody (const std::shared_ptr< FuncDefNode > & functionNode, const FunctionLayoutInfo & layout, bool isMainBody) private
Emit full function body/prologue/epilogue from layout info.
Emit one function body with frame-aware conventions.
Handles prologue/epilogue, parameter/local trace summaries, block lowering, and method receiver context for nested member accesses.
Definition at line 1304 of file codegen.cpp.
References _currentClassName, _currentFrameSize, _currentFunction, _currentReturnLabel, _currentReturnType, _currentThisOffset, _stackOffsets, _stackVarInfo, CodeGenVisitor::FunctionLayoutInfo::className, emit(), emitComment(), emitSourceLineContext(), CodeGenVisitor::FunctionLayoutInfo::frameSize, CodeGenVisitor::FunctionLayoutInfo::isMethod, CodeGenVisitor::FunctionLayoutInfo::key, CodeGenVisitor::FunctionLayoutInfo::label, CodeGenVisitor::FunctionLayoutInfo::paramNames, CodeGenVisitor::FunctionLayoutInfo::paramOffsets, resetFunctionState(), CodeGenVisitor::FunctionLayoutInfo::returnLinkOffset, CodeGenVisitor::FunctionLayoutInfo::thisOffset, CodeGenVisitor::FunctionLayoutInfo::varInfo, and CodeGenVisitor::FunctionLayoutInfo::varOffsets.
Referenced by visit().
emitIndexOffsetIntoAddress()
bool CodeGenVisitor::emitIndexOffsetIntoAddress (int addrReg, const std::vector< std::shared_ptr< ASTNode > > & indices, const std::vector< int > & declaredDimensions, long elementSize, int line) private
Emit array-index linearized offset into address register.
Lower multidimensional index expressions into linear byte offset.
Parameters
addrReg Base address register to update in-place.
indices Runtime index expressions in source order.
declaredDimensions Declared array dimensions for stride computation.
elementSize Element size in bytes.
line Source line for diagnostics/tracing.
Returns
True when offset emission succeeds.
Definition at line 937 of file codegen.cpp.
References _regs, emit(), emitSourceLineContext(), evalExpr(), and reportError().
Referenced by emitAddressForDataMember().
emitRuntimeIntegerIO()
void CodeGenVisitor::emitRuntimeIntegerIO () private
Emit runtime helper routines for integer/float input-output.
Emit runtime helper routines for integer and fixed-point float I/O.
Helpers are emitted once per compilation unit and invoked via jl from read/ write statements to keep core statement lowering simple and uniform.
Definition at line 1393 of file codegen.cpp.
References emit(), emitComment(), and emitSourceLineContext().
Referenced by generate().
emitSourceLineContext()
void CodeGenVisitor::emitSourceLineContext (int line, const std::string & message) private
Emit comment with source line context tag.
Attach source-line context tag and emit contextual trace comment.
Definition at line 304 of file codegen.cpp.
References emitComment(), and setTraceContext().
Referenced by emitAddressForDataMember(), emitAddressForLValue(), emitCopyWords(), emitFunctionBody(), emitIndexOffsetIntoAddress(), emitRuntimeIntegerIO(), emitStoreTarget(), loadThisPointerInto(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
emitStoreTarget()
bool CodeGenVisitor::emitStoreTarget (const std::shared_ptr< ASTNode > & target, int valueReg) private
Emit scalar store into assignment target.
Emit scalar store into assignable target location.
Definition at line 1271 of file codegen.cpp.
References _regs, emit(), emitAddressForLValue(), emitSourceLineContext(), and reportError().
Referenced by visit(), and visit().
evalExpr()
int CodeGenVisitor::evalExpr (const std::shared_ptr< ASTNode > & node) private
Evaluate expression and return result register.
Evaluate expression subtree and return result register id.
Definition at line 734 of file codegen.cpp.
References _lastExprReg, and reportError().
Referenced by emitAddressForObjectExpression(), emitIndexOffsetIntoAddress(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
findFunctionLayout()
const CodeGenVisitor::FunctionLayoutInfo * CodeGenVisitor::findFunctionLayout (const std::string & className, const std::string & functionName) const private
Lookup prebuilt function layout by owner/name.
Lookup cached function layout by owner class and function name.
Definition at line 474 of file codegen.cpp.
References _functionLayouts, and functionKey().
Referenced by resolveNodeType(), visit(), and visit().
functionKey()
std::string CodeGenVisitor::functionKey (const std::string & className, const std::string & functionName) static private
Build canonical function key from class/function names.
Build canonical function map key from class/function names.
Definition at line 359 of file codegen.cpp.
Referenced by buildFunctionLayout(), findFunctionLayout(), and visit().
generate()
bool CodeGenVisitor::generate (const std::shared_ptr< ProgNode > & root)
Generate Moon assembly from program AST root.
Generate Moon assembly from program AST.
Parameters
root Program root node.
Returns
True when code generation completes without codegen errors.
Initializes trace state, emits entry bootstrap, delegates full program lowering to the AST visitor, then appends runtime I/O helpers.
Definition at line 215 of file codegen.cpp.
References _errors, _labelCounter, _traceContextTag, _traceEmitCounter, _traceSourceLine, emit(), emitComment(), emitRuntimeIntegerIO(), reportError(), and setTraceContext().
Referenced by generateMoonAssembly().
getErrors()
const std::vector< std::string > & CodeGenVisitor::getErrors () const
Get accumulated code generation diagnostics.
Expose accumulated code generation diagnostics.
Definition at line 243 of file codegen.cpp.
References _errors.
Referenced by generateMoonAssembly().
hasOffset()
bool CodeGenVisitor::hasOffset (const std::string & name) const private
Check whether active frame has named stack slot.
Return true when active frame owns a slot for identifier name.
Definition at line 719 of file codegen.cpp.
References _stackOffsets.
Referenced by emitAddressForDataMember(), emitAddressForLValue(), and visit().
loadThisPointerInto()
bool CodeGenVisitor::loadThisPointerInto (int targetReg, int line) private
Load implicit receiver pointer into target register.
Load implicit receiver pointer into target register for method context.
Definition at line 747 of file codegen.cpp.
References _currentClassName, _currentThisOffset, emit(), emitSourceLineContext(), and reportError().
Referenced by emitAddressForDataMember(), emitAddressForLValue(), visit(), and visit().
lookupFieldLayout()
bool CodeGenVisitor::lookupFieldLayout (const std::string & className, const std::string & fieldName, FieldLayoutInfo & out, int line) private
Lookup resolved field layout metadata in class layout.
Resolve field layout metadata within a class layout cache.
Definition at line 604 of file codegen.cpp.
References _classLayouts, buildClassLayout(), and reportError().
Referenced by emitAddressForDataMember(), emitAddressForLValue(), resolveDataMemberType(), resolveNodeType(), and visit().
lookupOffset()
long CodeGenVisitor::lookupOffset (const std::string & name) const private
Lookup named stack offset in active frame.
Lookup active frame offset for identifier name.
Definition at line 724 of file codegen.cpp.
References _stackOffsets.
Referenced by emitAddressForDataMember(), emitAddressForLValue(), and visit().
makeLabel()
std::string CodeGenVisitor::makeLabel (const std::string & prefix) private
Build unique label from prefix.
Create a unique label from prefix plus monotonic counter.
Definition at line 354 of file codegen.cpp.
References _labelCounter, and sanitizeName().
Referenced by visit(), visit(), and visit().
reportError()
void CodeGenVisitor::reportError (int line, const std::string & message) private
Record formatted codegen diagnostic.
Record formatted codegen error with source line.
Definition at line 329 of file codegen.cpp.
References _errors.
Referenced by assignOffsets(), buildClassLayout(), emitAddressForDataMember(), emitAddressForLValue(), emitAddressForObjectExpression(), emitCopyWords(), emitIndexOffsetIntoAddress(), emitStoreTarget(), evalExpr(), generate(), loadThisPointerInto(), lookupFieldLayout(), resolveDataMemberType(), resolveNodeType(), sizeOfClass(), sizeOfType(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
resetFunctionState()
void CodeGenVisitor::resetFunctionState () private
Reset per-function emission state.
Reset mutable per-function frame/register state before emission.
Definition at line 367 of file codegen.cpp.
References _lastExprReg, _nextOffset, _regs, _stackOffsets, and _stackVarInfo.
Referenced by emitFunctionBody().
resolveDataMemberType()
bool CodeGenVisitor::resolveDataMemberType (const std::shared_ptr< DataMemberNode > & node, std::string & typeName, std::vector< int > & dimensions) private
Infer type info specifically for data-member access node.
Resolve effective type and remaining dimensions for data-member access.
Definition at line 763 of file codegen.cpp.
References _currentClassName, _stackVarInfo, CodeGenVisitor::FieldLayoutInfo::dimensions, lookupFieldLayout(), reportError(), resolveNodeType(), and CodeGenVisitor::FieldLayoutInfo::typeName.
Referenced by resolveNodeType().
resolveNodeType()
bool CodeGenVisitor::resolveNodeType (const std::shared_ptr< ASTNode > & node, std::string & typeName, std::vector< int > & dimensions) private
Infer type and dimensions for any expression node.
Resolve expression type information used by lowering decisions.
This helper enables mixed numeric operations, object-copy detection, call return handling, and argument conversions without re-running semantic analysis.
Definition at line 822 of file codegen.cpp.
References _currentClassName, _stackVarInfo, CodeGenVisitor::FieldLayoutInfo::dimensions, findFunctionLayout(), lookupFieldLayout(), reportError(), resolveDataMemberType(), resolveNodeType(), CodeGenVisitor::FunctionLayoutInfo::returnType, and CodeGenVisitor::FieldLayoutInfo::typeName.
Referenced by emitAddressForDataMember(), resolveDataMemberType(), resolveNodeType(), visit(), visit(), visit(), visit(), and visit().
sanitizeName()
std::string CodeGenVisitor::sanitizeName (const std::string & raw) static private
Sanitize string for assembly-safe label token.
Sanitize arbitrary identifier text for use in Moon labels.
Definition at line 334 of file codegen.cpp.
Referenced by buildFunctionLayout(), and makeLabel().
setTraceContext()
void CodeGenVisitor::setTraceContext (int line, const std::string & contextTag) private
Set active trace context fields.
Update current trace context tuple (line + semantic tag).
Definition at line 323 of file codegen.cpp.
References _traceContextTag, and _traceSourceLine.
Referenced by emitSourceLineContext(), and generate().
sizeOfClass()
long CodeGenVisitor::sizeOfClass (const std::string & className, std::unordered_set< std::string > & visiting, int line) private
Compute class byte size (with cycle-safe recursion).
Compute or retrieve total byte size for a class type.
Definition at line 582 of file codegen.cpp.
References _classSizes, buildClassLayout(), and reportError().
Referenced by sizeOfType().
sizeOfType()
long CodeGenVisitor::sizeOfType (const std::string & typeName, int line) private
Compute byte size for scalar/class type.
Compute storage size for scalar or class type.
Definition at line 484 of file codegen.cpp.
References reportError(), and sizeOfClass().
Referenced by assignOffsets(), buildFunctionLayout(), emitAddressForDataMember(), sizeOfVar(), visit(), and visit().
sizeOfVar()
long CodeGenVisitor::sizeOfVar (const std::shared_ptr< VarDeclNode > & decl) private
Compute storage bytes for variable declaration.
Compute storage size for a declared variable.
Array parameters and declarations with unspecified dimensions are lowered as references (word-sized addresses) rather than inline aggregate storage.
Definition at line 634 of file codegen.cpp.
References sizeOfType().
Referenced by assignOffsets(), buildClassLayout(), and buildFunctionLayout().
visit() [1/18]
void CodeGenVisitor::visit (AssignStmtNode & node) override virtual
Lower assignment statement for scalar store or aggregate object copy.
Object assignment emits explicit memory copy loops while scalar assignment follows expression evaluation and target-address store.
Implements ASTVisitor.
Definition at line 2074 of file codegen.cpp.
References _regs, emit(), emitAddressForLValue(), emitAddressForObjectExpression(), emitCopyWords(), emitSourceLineContext(), emitStoreTarget(), evalExpr(), ASTNode::getLeft(), ASTNode::getLineNumber(), ASTNode::getRight(), resolveNodeType(), and sizeOfType().
visit() [2/18]
void CodeGenVisitor::visit (BinaryOpNode & node) override virtual
Lower binary expression with scalar/fixed-point operator selection.
Mixed integer-float arithmetic is handled by fixed-point promotion using the module-wide scale constant before operation emission.
Implements ASTVisitor.
Definition at line 1730 of file codegen.cpp.
References _lastExprReg, _regs, emit(), emitComment(), emitSourceLineContext(), evalExpr(), ASTNode::getLeft(), ASTNode::getLineNumber(), BinaryOpNode::getOperator(), ASTNode::getRight(), reportError(), and resolveNodeType().
visit() [3/18]
void CodeGenVisitor::visit (BlockNode & node) override virtual
Lower statement block by visiting statements in source order.
Implements ASTVisitor.
Definition at line 2327 of file codegen.cpp.
References _lastExprReg, _regs, emitSourceLineContext(), ASTNode::getLineNumber(), and BlockNode::getStatements().
visit() [4/18]
void CodeGenVisitor::visit (ClassDeclNode & node) override virtual
Class declaration node currently contributes layout metadata only.
Implements ASTVisitor.
Definition at line 2353 of file codegen.cpp.
References emitComment(), and ClassDeclNode::getName().
visit() [5/18]
void CodeGenVisitor::visit (DataMemberNode & node) override virtual
Lower member access expression by address resolution then load.
Implements ASTVisitor.
Definition at line 2042 of file codegen.cpp.
References _lastExprReg, _regs, emit(), emitAddressForDataMember(), emitSourceLineContext(), DataMemberNode::getIndices(), ASTNode::getLineNumber(), DataMemberNode::getName(), and reportError().
visit() [6/18]
void CodeGenVisitor::visit (FloatLitNode & node) override virtual
Lower float literal into fixed-point integer immediate.
Implements ASTVisitor.
Definition at line 1700 of file codegen.cpp.
References _lastExprReg, _regs, emit(), emitSourceLineContext(), FloatLitNode::getFloatValue(), ASTNode::getLineNumber(), and reportError().
visit() [7/18]
void CodeGenVisitor::visit (FuncCallNode & node) override virtual
Lower function or method call sequence.
Emits argument marshalling, optional receiver handling, frame movement around call, jump-link transfer, and return-value capture.
Implements ASTVisitor.
Definition at line 1840 of file codegen.cpp.
References _currentClassName, _currentFrameSize, _lastExprReg, _regs, emit(), emitAddressForLValue(), emitAddressForObjectExpression(), emitComment(), emitCopyWords(), emitSourceLineContext(), evalExpr(), findFunctionLayout(), FuncCallNode::getArgs(), FuncCallNode::getFunctionName(), ASTNode::getLeft(), ASTNode::getLineNumber(), CodeGenVisitor::FunctionLayoutInfo::isMethod, CodeGenVisitor::FunctionLayoutInfo::key, CodeGenVisitor::FunctionLayoutInfo::label, loadThisPointerInto(), CodeGenVisitor::FunctionLayoutInfo::paramNames, CodeGenVisitor::FunctionLayoutInfo::paramOffsets, reportError(), resolveNodeType(), CodeGenVisitor::FunctionLayoutInfo::returnType, sizeOfType(), CodeGenVisitor::FunctionLayoutInfo::thisOffset, and CodeGenVisitor::FunctionLayoutInfo::varInfo.
visit() [8/18]
void CodeGenVisitor::visit (FuncDefNode & node) override virtual
Function declarations are emitted centrally during program lowering.
Implements ASTVisitor.
Definition at line 2347 of file codegen.cpp.
visit() [9/18]
void CodeGenVisitor::visit (IdNode & node) override virtual
Lower identifier expression into register value load.
Implements ASTVisitor.
Definition at line 1624 of file codegen.cpp.
References _currentClassName, _lastExprReg, _regs, emit(), emitSourceLineContext(), ASTNode::getLineNumber(), IdNode::getName(), hasOffset(), loadThisPointerInto(), lookupFieldLayout(), lookupOffset(), CodeGenVisitor::FieldLayoutInfo::offset, and reportError().
visit() [10/18]
void CodeGenVisitor::visit (IfStmtNode & node) override virtual
Lower if/else control flow with generated branch labels.
Implements ASTVisitor.
Definition at line 2153 of file codegen.cpp.
References _regs, emit(), emitSourceLineContext(), evalExpr(), IfStmtNode::getElseBlock(), ASTNode::getLeft(), ASTNode::getLineNumber(), ASTNode::getRight(), and makeLabel().
visit() [11/18]
void CodeGenVisitor::visit (IntLitNode & node) override virtual
Lower integer literal into immediate-loaded register.
Implements ASTVisitor.
Definition at line 1686 of file codegen.cpp.
References _lastExprReg, _regs, emit(), emitSourceLineContext(), IntLitNode::getIntValue(), ASTNode::getLineNumber(), and reportError().
visit() [12/18]
void CodeGenVisitor::visit (IOStmtNode & node) override virtual
Lower read/write statements through runtime helper routines.
Read and write share helper-based ABI so statement lowering only manages target/source evaluation and register conventions.
Implements ASTVisitor.
Definition at line 2218 of file codegen.cpp.
References _regs, emit(), emitComment(), emitSourceLineContext(), emitStoreTarget(), evalExpr(), ASTNode::getLeft(), ASTNode::getLineNumber(), IOStmtNode::getValue(), reportError(), and resolveNodeType().
visit() [13/18]
void CodeGenVisitor::visit (ProgNode & node) override virtual
Lower full program: collect layouts, emit main, emit non-main functions.
Main body is emitted first as entry execution path, then other routines are emitted and referenced by labels for call sites.
Implements ASTVisitor.
Definition at line 2364 of file codegen.cpp.
References _classDecls, _classLayouts, _classSizes, _functionLayouts, buildClassLayout(), buildFunctionLayout(), emit(), emitComment(), emitFunctionBody(), findFunctionLayout(), CodeGenVisitor::FunctionLayoutInfo::frameSize, functionKey(), ProgNode::getClasses(), ProgNode::getFunctions(), CodeGenVisitor::FunctionLayoutInfo::key, makeLabel(), CodeGenVisitor::FunctionLayoutInfo::paramNames, reportError(), and CodeGenVisitor::FunctionLayoutInfo::varOffsets.
visit() [14/18]
void CodeGenVisitor::visit (ReturnStmtNode & node) override virtual
Lower return statement and transfer result to return register.
Implements ASTVisitor.
Definition at line 2288 of file codegen.cpp.
References _currentFunction, _currentReturnLabel, _currentReturnType, _regs, emit(), emitAddressForObjectExpression(), emitComment(), emitSourceLineContext(), evalExpr(), ASTNode::getLeft(), ASTNode::getLineNumber(), and resolveNodeType().
visit() [15/18]
void CodeGenVisitor::visit (TypeNode & node) override virtual
Type nodes are metadata-only and produce no runtime value.
Implements ASTVisitor.
Definition at line 1719 of file codegen.cpp.
References _lastExprReg.
visit() [16/18]
void CodeGenVisitor::visit (UnaryOpNode & node) override virtual
Lower unary operators (negation, logical not, unary plus passthrough).
Implements ASTVisitor.
Definition at line 1813 of file codegen.cpp.
References _lastExprReg, emit(), emitSourceLineContext(), evalExpr(), ASTNode::getLeft(), ASTNode::getLineNumber(), UnaryOpNode::getOperator(), and reportError().
visit() [17/18]
void CodeGenVisitor::visit (VarDeclNode & node) override virtual
Variable declarations are layout-only and emit no direct instructions.
Implements ASTVisitor.
Definition at line 2342 of file codegen.cpp.
visit() [18/18]
void CodeGenVisitor::visit (WhileStmtNode & node) override virtual
Lower while loop with explicit start/end labels and conditional branch.
Implements ASTVisitor.
Definition at line 2185 of file codegen.cpp.
References _regs, emit(), emitComment(), emitSourceLineContext(), evalExpr(), ASTNode::getLeft(), ASTNode::getLineNumber(), ASTNode::getRight(), and makeLabel().
Member Data Documentation
_classDecls
std::unordered_map<std::string, std::shared_ptr<ClassDeclNode> > CodeGenVisitor::_classDecls private
Class declarations indexed by name from AST root.
Definition at line 185 of file codegen.h.
Referenced by buildClassLayout(), and visit().
_classLayouts
std::unordered_map<std::string, ClassLayoutInfo> CodeGenVisitor::_classLayouts private
Cached class layouts.
Definition at line 187 of file codegen.h.
Referenced by buildClassLayout(), lookupFieldLayout(), and visit().
_classSizes
std::unordered_map<std::string, long> CodeGenVisitor::_classSizes private
Cached class sizes.
Definition at line 189 of file codegen.h.
Referenced by buildClassLayout(), sizeOfClass(), and visit().
_currentClassName
std::string CodeGenVisitor::_currentClassName private
Current class name during method emission.
Definition at line 205 of file codegen.h.
Referenced by emitAddressForDataMember(), emitAddressForLValue(), emitFunctionBody(), loadThisPointerInto(), resolveDataMemberType(), resolveNodeType(), visit(), and visit().
_currentFrameSize
long CodeGenVisitor::_currentFrameSize = 0 private
Current frame size.
Definition at line 211 of file codegen.h.
Referenced by emitFunctionBody(), and visit().
_currentFunction
std::string CodeGenVisitor::_currentFunction private
Current function name during emission.
Definition at line 203 of file codegen.h.
Referenced by emitFunctionBody(), and visit().
_currentReturnLabel
std::string CodeGenVisitor::_currentReturnLabel private
Current function return label.
Definition at line 207 of file codegen.h.
Referenced by emitFunctionBody(), and visit().
_currentReturnType
std::string CodeGenVisitor::_currentReturnType private
Current function return type.
Definition at line 209 of file codegen.h.
Referenced by emitFunctionBody(), and visit().
_currentThisOffset
long CodeGenVisitor::_currentThisOffset = 0 private
Current implicit receiver slot offset.
Definition at line 213 of file codegen.h.
Referenced by emitFunctionBody(), and loadThisPointerInto().
_errors
std::vector<std::string> CodeGenVisitor::_errors private
Collected codegen errors.
Definition at line 182 of file codegen.h.
Referenced by generate(), getErrors(), and reportError().
_functionLayouts
std::unordered_map<std::string, FunctionLayoutInfo> CodeGenVisitor::_functionLayouts private
Cached function frame layouts.
Definition at line 191 of file codegen.h.
Referenced by buildFunctionLayout(), findFunctionLayout(), and visit().
_labelCounter
int CodeGenVisitor::_labelCounter = 0 private
Unique label counter.
Definition at line 199 of file codegen.h.
Referenced by generate(), and makeLabel().
_lastExprReg
int CodeGenVisitor::_lastExprReg = -1 private
Last expression result register.
Definition at line 201 of file codegen.h.
Referenced by evalExpr(), resetFunctionState(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
_nextOffset
long CodeGenVisitor::_nextOffset = 0 private
Active frame allocation cursor.
Definition at line 197 of file codegen.h.
Referenced by assignOffsets(), and resetFunctionState().
_out
std::ostream& CodeGenVisitor::_out private
Assembly output stream target.
Definition at line 178 of file codegen.h.
Referenced by CodeGenVisitor(), and emit().
_regs
RegisterAllocator CodeGenVisitor::_regs private
Temporary register allocator.
Definition at line 180 of file codegen.h.
Referenced by emitAddressForDataMember(), emitAddressForLValue(), emitCopyWords(), emitIndexOffsetIntoAddress(), emitStoreTarget(), resetFunctionState(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
_stackOffsets
std::unordered_map<std::string, long> CodeGenVisitor::_stackOffsets private
Active frame offsets.
Definition at line 195 of file codegen.h.
Referenced by assignOffsets(), emitFunctionBody(), hasOffset(), lookupOffset(), and resetFunctionState().
_stackVarInfo
std::unordered_map<std::string, StackVarInfo> CodeGenVisitor::_stackVarInfo private
Active frame variable metadata.
Definition at line 193 of file codegen.h.
Referenced by assignOffsets(), emitAddressForDataMember(), emitAddressForLValue(), emitFunctionBody(), resetFunctionState(), resolveDataMemberType(), and resolveNodeType().
_traceContextTag
std::string CodeGenVisitor::_traceContextTag private
Trace context tag.
Definition at line 219 of file codegen.h.
Referenced by emit(), generate(), and setTraceContext().
_traceEmitCounter
long CodeGenVisitor::_traceEmitCounter = 0 private
Trace instruction counter.
Definition at line 215 of file codegen.h.
Referenced by emit(), and generate().
_traceSourceLine
int CodeGenVisitor::_traceSourceLine = 0 private
Trace source line context.
Definition at line 217 of file codegen.h.
Referenced by emit(), generate(), and setTraceContext().
The documentation for this class was generated from the following files:
codegen.h
codegen.cpp