COMP442 Compiler: IntLitNode Class Reference
IntLitNode Class Reference
Integer literal leaf node.
#include <AST.h>
Public Member Functions
void accept (ASTVisitor &visitor) override
Accept a visitor (double-dispatch entry point).
int getIntValue () const
std::string getValue () const override
Return compact textual label for diagnostics/printers.
IntLitNode (int line, int val)
Public Member Functions inherited from ASTNode
ASTNode (int line=0)
Construct base AST node with source line metadata.
std::shared_ptr< ASTNode > getLeft () const
Get left child pointer (binary/unary shared convention).
int getLineNumber () const
Get source line number for diagnostics and tracing.
std::shared_ptr< ASTNode > getRight () const
Get right child pointer (binary/shared convention).
void setLeft (std::shared_ptr< ASTNode > leftNode)
Set left child pointer.
void setRight (std::shared_ptr< ASTNode > rightNode)
Set right child pointer.
virtual ~ASTNode ()=default
Virtual destructor for polymorphic ownership safety.
Private Attributes
int value
Detailed Description
Integer literal leaf node.
Definition at line 161 of file AST.h.
Constructor & Destructor Documentation
IntLitNode()
IntLitNode::IntLitNode (int line, int val) inline
Definition at line 165 of file AST.h.
References ASTNode::ASTNode(), and value.
Member Function Documentation
accept()
void IntLitNode::accept (ASTVisitor & visitor) override virtual
Accept a visitor (double-dispatch entry point).
Parameters
visitor Visitor implementation for current compiler phase.
Implements ASTNode.
Definition at line 36 of file AST.cpp.
References ASTVisitor::visit().
getIntValue()
int IntLitNode::getIntValue () const inline
Definition at line 166 of file AST.h.
References value.
Referenced by CodeGenVisitor::visit().
getValue()
std::string IntLitNode::getValue () const inline override virtual
Return compact textual label for diagnostics/printers.
Returns
Node-specific display string.
Implements ASTNode.
Definition at line 167 of file AST.h.
References value.
Member Data Documentation
value
int IntLitNode::value private
Definition at line 163 of file AST.h.
Referenced by getIntValue(), getValue(), and IntLitNode().
The documentation for this class was generated from the following files:
AST.h
AST.cpp