COMP442 Compiler: codegen.cpp File Reference
codegen.cpp File Reference
Moon backend implementation for AST-to-assembly lowering.
#include "../include/codegen.h"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <sstream>
#include <cctype>
Functions
bool generateMoonAssembly (const std::shared_ptr< ProgNode > &root, const std::string &outputPath, std::vector< std::string > *errors)
Convenience front-end for writing generated Moon assembly to file.
Detailed Description
Moon backend implementation for AST-to-assembly lowering.
This implementation performs deterministic lowering from typed AST nodes to Moon assembly by combining:
class/function layout synthesis,
register and stack-frame orchestration,
value/address lowering for scalars, arrays, and objects,
runtime helper emission for numeric input-output.
Why this approach?
Keeping lowering decisions centralized enables traceable instruction output, consistent diagnostics, and easier debugging against source-line context.
Definition in file codegen.cpp.
Function Documentation
generateMoonAssembly()
bool generateMoonAssembly (const std::shared_ptr< ProgNode > & root, const std::string & outputPath, std::vector< std::string > * errors)
Convenience front-end for writing generated Moon assembly to file.
Convenience API: generate Moon assembly directly to a file.
Returns
True when generation succeeded and output file was writable.
Definition at line 2463 of file codegen.cpp.
References CodeGenVisitor::generate(), and CodeGenVisitor::getErrors().
Referenced by main().