COMP442 Compiler: codegen.h File Reference
codegen.h File Reference
Moon backend code generation visitor and emission interfaces.
#include "AST.h"
#include <memory>
#include <ostream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>
Classes
struct CodeGenVisitor::ClassLayoutInfo
Fully flattened class layout including inherited fields.
class CodeGenVisitor
AST visitor that emits Moon assembly for the full program.
struct CodeGenVisitor::FieldLayoutInfo
Memory layout metadata for class fields.
struct CodeGenVisitor::FunctionLayoutInfo
Stack-frame and call metadata for a lowered function/method.
class CodeGenVisitor::RegisterAllocator
Simple pool allocator for Moon general-purpose temporaries.
struct CodeGenVisitor::StackVarInfo
Per-variable frame metadata for local/param lowering.
Functions
bool generateMoonAssembly (const std::shared_ptr< ProgNode > &root, const std::string &outputPath, std::vector< std::string > *errors=nullptr)
Convenience API: generate Moon assembly directly to a file.
Detailed Description
Moon backend code generation visitor and emission interfaces.
This header defines the AST-driven backend that lowers typed AST nodes into Moon assembly. The backend is layout-driven (class/object layouts, function frames) and uses a register allocator plus stack-based addressing discipline.
Why this shape?
Keeping layout, type-resolution, and emission helpers in one visitor provides deterministic lowering and consistent diagnostics across all node categories.
Definition in file codegen.h.
Function Documentation
generateMoonAssembly()
bool generateMoonAssembly (const std::shared_ptr< ProgNode > & root, const std::string & outputPath, std::vector< std::string > * errors)
Convenience API: generate Moon assembly directly to a file.
Parameters
root Program root node.
outputPath Destination assembly file path.
errors Optional output vector for codegen diagnostics.
Returns
True on successful generation and file write.
Convenience API: generate Moon assembly directly to a file.
Returns
True when generation succeeded and output file was writable.
Definition at line 2463 of file codegen.cpp.
References CodeGenVisitor::generate(), and CodeGenVisitor::getErrors().
Referenced by main().