COMP442 Compiler: io.cpp File Reference
io.cpp File Reference
#include "../include/io.h"
#include "../include/token.h"
#include <cstdlib>
#include <stdexcept>
#include <iostream>
#include <filesystem>
Functions
std::string buildOutputPath (const std::string &outputDir, const std::string &baseName, const std::string &extension)
std::string createOutputDir (const std::string &sourceFile, const std::string &driverExecutablePath)
std::string getBaseName (const std::string &sourceFile)
std::vector< std::vector< Token > > lex_file (const std::string &input_file, const std::string valid_out_file, const std::string invalid_out_file, size_t *invalidTokenCount)
std::vector< std::pair< std::string, std::string > > makeDisplayArtifacts (const std::vector< std::pair< std::string, std::string > > &artifacts)
std::string makeDisplayPath (const std::string &rawPath)
CompilerOutputPaths prepareCompilerOutputPaths (const std::string &sourceFile, const std::string &driverExecutablePath)
MoonRunResult runMoonSimulator (const std::string &driverExecutablePath, const std::string &moonInputFile, const std::string &moonRunLogFile)
std::tuple< std::vector< std::vector< Token > >, std::vector< std::vector< Token > > > tokenizeFile (const std::string &filename)
void writeDerivationToFile (const std::string &filename, const std::vector< std::string > &derivationSteps)
void writeErrorsToFile (const std::string &filename, const std::vector< std::vector< Token > > &tokens)
bool writeLinesToFile (const std::string &filename, const std::vector< std::string > &lines)
void writeSyntaxErrorsToFile (const std::string &filename, const std::vector< std::string > &errors)
bool writeTextToFile (const std::string &filename, const std::string &text)
void writeTokensToFile (const std::string &filename, const std::vector< std::vector< Token > > &tokens)
Function Documentation
buildOutputPath()
std::string buildOutputPath (const std::string & outputDir, const std::string & baseName, const std::string & extension)
Definition at line 74 of file io.cpp.
Referenced by prepareCompilerOutputPaths().
createOutputDir()
std::string createOutputDir (const std::string & sourceFile, const std::string & driverExecutablePath)
Definition at line 67 of file io.cpp.
References getBaseName().
Referenced by prepareCompilerOutputPaths().
getBaseName()
std::string getBaseName (const std::string & sourceFile)
Definition at line 63 of file io.cpp.
Referenced by createOutputDir(), and prepareCompilerOutputPaths().
lex_file()
std::vector< std::vector< Token > > lex_file (const std::string & input_file, const std::string valid_out_file, const std::string invalid_out_file, size_t * invalidTokenCount)
Definition at line 218 of file io.cpp.
References tokenizeFile(), writeErrorsToFile(), and writeTokensToFile().
Referenced by main().
makeDisplayArtifacts()
std::vector< std::pair< std::string, std::string > > makeDisplayArtifacts (const std::vector< std::pair< std::string, std::string > > & artifacts)
Definition at line 102 of file io.cpp.
References makeDisplayPath().
Referenced by main().
makeDisplayPath()
std::string makeDisplayPath (const std::string & rawPath)
Definition at line 78 of file io.cpp.
Referenced by main(), and makeDisplayArtifacts().
prepareCompilerOutputPaths()
CompilerOutputPaths prepareCompilerOutputPaths (const std::string & sourceFile, const std::string & driverExecutablePath)
Definition at line 114 of file io.cpp.
References CompilerOutputPaths::astDir, CompilerOutputPaths::astDotFile, CompilerOutputPaths::astFile, CompilerOutputPaths::astPngFile, CompilerOutputPaths::baseName, buildOutputPath(), CompilerOutputPaths::codegenDiagnosticsFile, CompilerOutputPaths::codegenDir, createOutputDir(), CompilerOutputPaths::derivationFile, getBaseName(), CompilerOutputPaths::invalidTokensFile, CompilerOutputPaths::lexerDir, CompilerOutputPaths::moonOutputFile, CompilerOutputPaths::moonRunLogFile, CompilerOutputPaths::outputDir, CompilerOutputPaths::parserDir, CompilerOutputPaths::semanticDiagnosticsFile, CompilerOutputPaths::semanticDir, CompilerOutputPaths::symbolTablesFile, CompilerOutputPaths::syntaxErrorsFile, and CompilerOutputPaths::validTokensFile.
Referenced by main().
runMoonSimulator()
MoonRunResult runMoonSimulator (const std::string & driverExecutablePath, const std::string & moonInputFile, const std::string & moonRunLogFile)
Definition at line 264 of file io.cpp.
References MoonRunResult::attempted, MoonRunResult::details, MoonRunResult::moonExecutablePath, MoonRunResult::success, and writeLinesToFile().
Referenced by main().
tokenizeFile()
std::tuple< std::vector< std::vector< Token > >, std::vector< std::vector< Token > > > tokenizeFile (const std::string & filename)
Definition at line 155 of file io.cpp.
References Token::flushPendingBlockComment(), and Token::tokenize().
Referenced by lex_file().
writeDerivationToFile()
void writeDerivationToFile (const std::string & filename, const std::vector< std::string > & derivationSteps)
Definition at line 370 of file io.cpp.
Referenced by main().
writeErrorsToFile()
void writeErrorsToFile (const std::string & filename, const std::vector< std::vector< Token > > & tokens)
Definition at line 331 of file io.cpp.
Referenced by lex_file().
writeLinesToFile()
bool writeLinesToFile (const std::string & filename, const std::vector< std::string > & lines)
Definition at line 241 of file io.cpp.
Referenced by main(), and runMoonSimulator().
writeSyntaxErrorsToFile()
void writeSyntaxErrorsToFile (const std::string & filename, const std::vector< std::string > & errors)
Definition at line 356 of file io.cpp.
Referenced by main().
writeTextToFile()
bool writeTextToFile (const std::string & filename, const std::string & text)
Definition at line 254 of file io.cpp.
Referenced by main().
writeTokensToFile()
void writeTokensToFile (const std::string & filename, const std::vector< std::vector< Token > > & tokens)
Definition at line 196 of file io.cpp.
Referenced by lex_file().