COMP442 Compiler: UI Namespace Reference
UI Namespace Reference
Classes
struct PngRenderResult
Functions
void printArtifactList (const std::string &title, const std::vector< std::pair< std::string, std::string > > &artifacts)
void printCrash (const std::string &phaseName, const std::string &errorMessage)
void printDone ()
void printKV (const std::string &key, const std::string &value)
void printPngGenerationNotes (const PngRenderResult &result)
void printSection (const std::string &title)
void printStatusLine (bool success, const std::string &message)
void printSummaryTable (const std::vector< PhaseSummary > &phases)
void printTitle (const std::string &title)
void printWarning (const std::string &message)
PngRenderResult renderAstPngFromDot (const std::string &inputDot, const std::string &outputPng)
Function Documentation
printArtifactList()
void UI::printArtifactList (const std::string & title, const std::vector< std::pair< std::string, std::string > > & artifacts)
Definition at line 104 of file ui.cpp.
Referenced by main().
printCrash()
void UI::printCrash (const std::string & phaseName, const std::string & errorMessage)
Definition at line 80 of file ui.cpp.
Referenced by main().
printDone()
void UI::printDone ()
Definition at line 131 of file ui.cpp.
Referenced by main().
printKV()
void UI::printKV (const std::string & key, const std::string & value)
Definition at line 68 of file ui.cpp.
Referenced by main().
printPngGenerationNotes()
void UI::printPngGenerationNotes (const PngRenderResult & result)
Definition at line 123 of file ui.cpp.
References UI::PngRenderResult::dotAvailable, UI::PngRenderResult::pngGenerated, and printWarning().
Referenced by main().
printSection()
void UI::printSection (const std::string & title)
Definition at line 61 of file ui.cpp.
Referenced by main().
printStatusLine()
void UI::printStatusLine (bool success, const std::string & message)
Definition at line 72 of file ui.cpp.
Referenced by main().
printSummaryTable()
void UI::printSummaryTable (const std::vector< PhaseSummary > & phases)
Definition at line 84 of file ui.cpp.
Referenced by main().
printTitle()
void UI::printTitle (const std::string & title)
Definition at line 54 of file ui.cpp.
Referenced by main().
printWarning()
void UI::printWarning (const std::string & message)
Definition at line 76 of file ui.cpp.
Referenced by main(), and printPngGenerationNotes().
renderAstPngFromDot()
PngRenderResult UI::renderAstPngFromDot (const std::string & inputDot, const std::string & outputPng)
Definition at line 111 of file ui.cpp.
References UI::PngRenderResult::dotAvailable, and UI::PngRenderResult::pngGenerated.
Referenced by main().