#include "../include/codegen.h"

#include <algorithm>
#include <cmath>
#include <fstream>
#include <sstream>
#include <cctype>

namespace {
std::string regName(int reg) {
    return "r" + std::to_string(reg);
}

std::string trimCopy(const std::string& raw) {
    size_t start = 0;
    while (start < raw.size() && std::isspace(static_cast<unsigned char>(raw[start]))) {
        ++start;
    }

    size_t end = raw.size();
    while (end > start && std::isspace(static_cast<unsigned char>(raw[end - 1]))) {
        --end;
    }

    return raw.substr(start, end - start);
}

bool isBasicScalarType(const std::string& typeName) {
    return typeName == "integer" || typeName == "float" || typeName == "bool";
}
}

CodeGenVisitor::RegisterAllocator::RegisterAllocator() {
    reset();
}

int CodeGenVisitor::RegisterAllocator::acquire() {
    if (_freeRegs.empty()) {
        return -1;
    }

    const int reg = _freeRegs.back();
    _freeRegs.pop_back();
    return reg;
}

void CodeGenVisitor::RegisterAllocator::release(int reg) {
    if (reg <= 0 || reg > 12) {
        return;
    }

    if (std::find(_freeRegs.begin(), _freeRegs.end(), reg) == _freeRegs.end()) {
        _freeRegs.push_back(reg);
    }
}

void CodeGenVisitor::RegisterAllocator::reset() {
    _freeRegs.clear();
    for (int reg = 12; reg >= 1; --reg) {
        _freeRegs.push_back(reg);
    }
}

CodeGenVisitor::CodeGenVisitor(std::ostream& out)
    : _out(out) {}

bool CodeGenVisitor::generate(const std::shared_ptr<ProgNode>& root) {
    _errors.clear();
    _labelCounter = 0;

    if (root == nullptr) {
        reportError(0, "cannot generate code from an empty AST");
        return false;
    }

    emitComment("Moon assembly generated by CodeGenVisitor");
    emit("entry");
    emit("addi r14, r0, topaddr");

    root->accept(*this);

    emit("hlt");

    return _errors.empty();
}

const std::vector<std::string>& CodeGenVisitor::getErrors() const {
    return _errors;
}

void CodeGenVisitor::emit(const std::string& line) {
    _out << line << "\n";
}

void CodeGenVisitor::emitComment(const std::string& message) {
    emit("% " + message);
}

void CodeGenVisitor::reportError(int line, const std::string& message) {
    _errors.push_back("[ERROR][CODEGEN] line " + std::to_string(line) + ": " + message);
}

std::string CodeGenVisitor::sanitizeName(const std::string& raw) {
    std::string result;
    result.reserve(raw.size());

    for (char c : raw) {
        if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_') {
            result.push_back(c);
        } else {
            result.push_back('_');
        }
    }

    if (result.empty()) {
        return "anon";
    }

    return result;
}

std::string CodeGenVisitor::makeLabel(const std::string& prefix) {
    return sanitizeName(prefix) + "_" + std::to_string(++_labelCounter);
}

void CodeGenVisitor::resetFunctionState() {
    _stackOffsets.clear();
    _stackVarInfo.clear();
    _nextOffset = 0;
    _regs.reset();
    _lastExprReg = -1;
}

long CodeGenVisitor::sizeOfType(const std::string& typeName, int line) {
    const std::string cleanType = trimCopy(typeName);
    if (cleanType.empty()) {
        reportError(line, "cannot compute storage size for empty type name");
        return -1;
    }

    if (isBasicScalarType(cleanType)) {
        return 4;
    }

    std::unordered_set<std::string> visiting;
    return sizeOfClass(cleanType, visiting, line);
}

bool CodeGenVisitor::buildClassLayout(const std::string& className, std::unordered_set<std::string>& visiting, int line) {
    const std::string cleanClassName = trimCopy(className);

    if (_classLayouts.find(cleanClassName) != _classLayouts.end()) {
        return true;
    }

    if (visiting.find(cleanClassName) != visiting.end()) {
        reportError(line, "circular class storage dependency while building layout for '" + cleanClassName + "'");
        return false;
    }

    auto declIt = _classDecls.find(cleanClassName);
    if (declIt == _classDecls.end() || declIt->second == nullptr) {
        reportError(line, "unknown class type in storage allocation: '" + cleanClassName + "'");
        return false;
    }

    visiting.insert(cleanClassName);

    ClassLayoutInfo layout;
    long runningOffset = 0;

    for (const auto& parentName : declIt->second->getParents()) {
        if (!buildClassLayout(parentName, visiting, line)) {
            visiting.erase(cleanClassName);
            return false;
        }

        const ClassLayoutInfo& parentLayout = _classLayouts[parentName];
        for (const auto& kv : parentLayout.fields) {
            FieldLayoutInfo inherited = kv.second;
            inherited.offset += runningOffset;
            if (layout.fields.find(kv.first) == layout.fields.end()) {
                layout.fields[kv.first] = inherited;
            }
        }

        runningOffset += parentLayout.size;
    }

    for (const auto& member : declIt->second->getMembers()) {
        auto fieldDecl = std::dynamic_pointer_cast<VarDeclNode>(member);
        if (fieldDecl == nullptr) {
            continue;
        }

        const long fieldSize = sizeOfVar(fieldDecl);
        if (fieldSize <= 0) {
            visiting.erase(cleanClassName);
            return false;
        }

        FieldLayoutInfo field;
        field.typeName = trimCopy(fieldDecl->getTypeName());
        field.dimensions = fieldDecl->getDimensions();
        field.offset = runningOffset;
        field.size = fieldSize;

        layout.fields[fieldDecl->getName()] = field;
        runningOffset += fieldSize;
    }

    if (runningOffset <= 0) {
        runningOffset = 4;
    }

    layout.size = runningOffset;
    _classLayouts[cleanClassName] = layout;
    _classSizes[cleanClassName] = layout.size;

    visiting.erase(cleanClassName);
    return true;
}

long CodeGenVisitor::sizeOfClass(const std::string& className, std::unordered_set<std::string>& visiting, int line) {
    const std::string cleanClassName = trimCopy(className);

    auto knownSize = _classSizes.find(cleanClassName);
    if (knownSize != _classSizes.end()) {
        return knownSize->second;
    }

    if (!buildClassLayout(cleanClassName, visiting, line)) {
        return -1;
    }

    knownSize = _classSizes.find(cleanClassName);
    if (knownSize != _classSizes.end()) {
        return knownSize->second;
    }

    reportError(line, "failed to compute class size for '" + cleanClassName + "'");
    return -1;
}

bool CodeGenVisitor::lookupFieldLayout(const std::string& className, const std::string& fieldName, FieldLayoutInfo& out, int line) {
    const std::string cleanClassName = trimCopy(className);
    std::unordered_set<std::string> visiting;
    if (!buildClassLayout(cleanClassName, visiting, line)) {
        return false;
    }

    auto classIt = _classLayouts.find(cleanClassName);
    if (classIt == _classLayouts.end()) {
        reportError(line, "class layout missing for '" + cleanClassName + "'");
        return false;
    }

    auto fieldIt = classIt->second.fields.find(fieldName);
    if (fieldIt == classIt->second.fields.end()) {
        reportError(line, "class '" + cleanClassName + "' has no field '" + fieldName + "' in code generation");
        return false;
    }

    out = fieldIt->second;
    return true;
}

long CodeGenVisitor::sizeOfVar(const std::shared_ptr<VarDeclNode>& decl) {
    if (decl == nullptr) {
        return 0;
    }

    long elements = 1;
    for (int dim : decl->getDimensions()) {
        if (dim <= 0) {
            reportError(decl->getLineNumber(), "invalid array dimension for variable '" + decl->getName() + "'");
            return -1;
        }

        elements *= dim;
    }

    const long elementSize = sizeOfType(decl->getTypeName(), decl->getLineNumber());
    if (elementSize <= 0) {
        return -1;
    }

    return elements * elementSize;
}

void CodeGenVisitor::assignOffsets(const std::vector<std::shared_ptr<VarDeclNode>>& vars) {
    for (const auto& var : vars) {
        if (var == nullptr) {
            continue;
        }

        const std::string name = var->getName();
        if (name.empty()) {
            continue;
        }

        const long varSize = sizeOfVar(var);
        if (varSize <= 0) {
            reportError(var->getLineNumber(), "invalid storage size for variable '" + name + "'");
            continue;
        }

        if (_stackOffsets.find(name) != _stackOffsets.end()) {
            reportError(var->getLineNumber(), "duplicate variable in codegen frame: '" + name + "'");
            continue;
        }

        _nextOffset -= varSize;
        _stackOffsets[name] = _nextOffset;

        long elements = 1;
        for (int dim : var->getDimensions()) {
            if (dim > 0) {
                elements *= dim;
            }
        }

        long elementSize = (elements > 0) ? (varSize / elements) : 4;
        if (elementSize <= 0) {
            elementSize = 4;
        }

        _stackVarInfo[name] = {trimCopy(var->getTypeName()), var->getDimensions(), elementSize};

        emitComment("alloc " + name + " @ " + std::to_string(_nextOffset) + "(r14), size=" + std::to_string(varSize));
    }
}

bool CodeGenVisitor::hasOffset(const std::string& name) const {
    return _stackOffsets.find(name) != _stackOffsets.end();
}

long CodeGenVisitor::lookupOffset(const std::string& name) const {
    auto it = _stackOffsets.find(name);
    if (it == _stackOffsets.end()) {
        return 0;
    }

    return it->second;
}

int CodeGenVisitor::evalExpr(const std::shared_ptr<ASTNode>& node) {
    _lastExprReg = -1;

    if (node == nullptr) {
        reportError(0, "null expression in code generation");
        return -1;
    }

    node->accept(*this);
    return _lastExprReg;
}

bool CodeGenVisitor::resolveDataMemberType(const std::shared_ptr<DataMemberNode>& node, std::string& typeName, std::vector<int>& dimensions) {
    if (node == nullptr) {
        return false;
    }

    if (node->getLeft() == nullptr) {
        auto infoIt = _stackVarInfo.find(node->getName());
        if (infoIt == _stackVarInfo.end()) {
            reportError(node->getLineNumber(), "unknown variable '" + node->getName() + "' in type resolution");
            return false;
        }

        typeName = infoIt->second.typeName;
        dimensions = infoIt->second.dimensions;
    } else {
        std::string ownerType;
        std::vector<int> ownerDimensions;
        if (!resolveNodeType(node->getLeft(), ownerType, ownerDimensions)) {
            return false;
        }

        if (!ownerDimensions.empty()) {
            reportError(node->getLineNumber(), "member access requires scalar object owner for '" + node->getName() + "'");
            return false;
        }

        FieldLayoutInfo fieldLayout;
        if (!lookupFieldLayout(ownerType, node->getName(), fieldLayout, node->getLineNumber())) {
            return false;
        }

        typeName = fieldLayout.typeName;
        dimensions = fieldLayout.dimensions;
    }

    if (node->getIndices().size() > dimensions.size()) {
        reportError(node->getLineNumber(), "too many indices for member '" + node->getName() + "' in type resolution");
        return false;
    }

    dimensions.erase(dimensions.begin(), dimensions.begin() + static_cast<long long>(node->getIndices().size()));
    return true;
}

bool CodeGenVisitor::resolveNodeType(const std::shared_ptr<ASTNode>& node, std::string& typeName, std::vector<int>& dimensions) {
    if (node == nullptr) {
        return false;
    }

    if (auto idNode = std::dynamic_pointer_cast<IdNode>(node)) {
        auto infoIt = _stackVarInfo.find(idNode->getName());
        if (infoIt == _stackVarInfo.end()) {
            reportError(idNode->getLineNumber(), "unknown identifier '" + idNode->getName() + "' in type resolution");
            return false;
        }

        typeName = infoIt->second.typeName;
        dimensions = infoIt->second.dimensions;
        return true;
    }

    if (auto dataMember = std::dynamic_pointer_cast<DataMemberNode>(node)) {
        return resolveDataMemberType(dataMember, typeName, dimensions);
    }

    if (std::dynamic_pointer_cast<IntLitNode>(node) != nullptr) {
        typeName = "integer";
        dimensions.clear();
        return true;
    }

    if (std::dynamic_pointer_cast<FloatLitNode>(node) != nullptr) {
        typeName = "float";
        dimensions.clear();
        return true;
    }

    if (auto unaryNode = std::dynamic_pointer_cast<UnaryOpNode>(node)) {
        return resolveNodeType(unaryNode->getLeft(), typeName, dimensions);
    }

    if (auto binaryNode = std::dynamic_pointer_cast<BinaryOpNode>(node)) {
        std::string leftType;
        std::vector<int> leftDims;
        std::string rightType;
        std::vector<int> rightDims;
        if (!resolveNodeType(binaryNode->getLeft(), leftType, leftDims) || !resolveNodeType(binaryNode->getRight(), rightType, rightDims)) {
            return false;
        }

        const std::string op = binaryNode->getOperator();
        if (op == "==" || op == "!=" || op == "<" || op == ">" || op == "<=" || op == ">=" || op == "and" || op == "or" || op == "&&" || op == "||") {
            typeName = "bool";
        } else if (leftType == "float" || rightType == "float") {
            typeName = "float";
        } else {
            typeName = "integer";
        }

        dimensions.clear();
        return true;
    }

    return false;
}

bool CodeGenVisitor::emitIndexOffsetIntoAddress(int addrReg,
                                                const std::vector<std::shared_ptr<ASTNode>>& indices,
                                                const std::vector<int>& declaredDimensions,
                                                long elementSize,
                                                int line) {
    if (indices.empty()) {
        return true;
    }

    if (indices.size() > declaredDimensions.size()) {
        reportError(line, "too many array indices in code generation");
        return false;
    }

    const int linearReg = _regs.acquire();
    if (linearReg < 0) {
        reportError(line, "register exhaustion while generating indexed address");
        return false;
    }

    emit("addi " + regName(linearReg) + ", r0, 0");

    for (size_t i = 0; i < indices.size(); ++i) {
        const int idxReg = evalExpr(indices[i]);
        if (idxReg < 0) {
            _regs.release(linearReg);
            return false;
        }

        long stride = 1;
        for (size_t j = i + 1; j < declaredDimensions.size(); ++j) {
            const int dim = declaredDimensions[j];
            if (dim <= 0) {
                _regs.release(idxReg);
                _regs.release(linearReg);
                reportError(line, "invalid declared array dimension in indexed addressing");
                return false;
            }
            stride *= dim;
        }

        if (stride != 1) {
            emit("muli " + regName(idxReg) + ", " + regName(idxReg) + ", " + std::to_string(stride));
        }

        emit("add " + regName(linearReg) + ", " + regName(linearReg) + ", " + regName(idxReg));
        _regs.release(idxReg);
    }

    if (elementSize != 1) {
        emit("muli " + regName(linearReg) + ", " + regName(linearReg) + ", " + std::to_string(elementSize));
    }

    emit("add " + regName(addrReg) + ", " + regName(addrReg) + ", " + regName(linearReg));
    _regs.release(linearReg);
    return true;
}

int CodeGenVisitor::emitAddressForLValue(const std::shared_ptr<ASTNode>& node, int line) {
    if (node == nullptr) {
        reportError(line, "null l-value in address generation");
        return -1;
    }

    if (auto idNode = std::dynamic_pointer_cast<IdNode>(node)) {
        if (!hasOffset(idNode->getName())) {
            reportError(idNode->getLineNumber(), "unknown variable '" + idNode->getName() + "' in code generation");
            return -1;
        }

        const int addrReg = _regs.acquire();
        if (addrReg < 0) {
            reportError(idNode->getLineNumber(), "register exhaustion while generating l-value address");
            return -1;
        }

        emit("addi " + regName(addrReg) + ", r14, " + std::to_string(lookupOffset(idNode->getName())));
        return addrReg;
    }

    if (auto memberNode = std::dynamic_pointer_cast<DataMemberNode>(node)) {
        return emitAddressForDataMember(*memberNode);
    }

    reportError(line, "unsupported l-value expression in address generation");
    return -1;
}

int CodeGenVisitor::emitAddressForDataMember(DataMemberNode& node) {
    if (node.getLeft() == nullptr) {
        if (!hasOffset(node.getName())) {
            reportError(node.getLineNumber(), "unknown variable '" + node.getName() + "' in code generation");
            return -1;
        }

        const int addrReg = _regs.acquire();
        if (addrReg < 0) {
            reportError(node.getLineNumber(), "register exhaustion while generating l-value address");
            return -1;
        }

        emit("addi " + regName(addrReg) + ", r14, " + std::to_string(lookupOffset(node.getName())));

        std::vector<int> declaredDimensions;
        long elementSize = 4;
        auto infoIt = _stackVarInfo.find(node.getName());
        if (infoIt != _stackVarInfo.end()) {
            declaredDimensions = infoIt->second.dimensions;
            elementSize = infoIt->second.elementSize;
        }

        if (!emitIndexOffsetIntoAddress(addrReg, node.getIndices(), declaredDimensions, elementSize, node.getLineNumber())) {
            _regs.release(addrReg);
            return -1;
        }

        return addrReg;
    }

    const int ownerAddrReg = emitAddressForLValue(node.getLeft(), node.getLineNumber());
    if (ownerAddrReg < 0) {
        return -1;
    }

    std::string ownerType;
    std::vector<int> ownerDimensions;
    if (!resolveNodeType(node.getLeft(), ownerType, ownerDimensions)) {
        _regs.release(ownerAddrReg);
        return -1;
    }

    if (!ownerDimensions.empty()) {
        reportError(node.getLineNumber(), "member access requires scalar object owner for '" + node.getName() + "'");
        _regs.release(ownerAddrReg);
        return -1;
    }

    FieldLayoutInfo fieldLayout;
    if (!lookupFieldLayout(ownerType, node.getName(), fieldLayout, node.getLineNumber())) {
        _regs.release(ownerAddrReg);
        return -1;
    }

    if (fieldLayout.offset != 0) {
        emit("addi " + regName(ownerAddrReg) + ", " + regName(ownerAddrReg) + ", " + std::to_string(fieldLayout.offset));
    }

    long elementCount = 1;
    for (int dim : fieldLayout.dimensions) {
        if (dim <= 0) {
            _regs.release(ownerAddrReg);
            reportError(node.getLineNumber(), "invalid declared field array dimension");
            return -1;
        }
        elementCount *= dim;
    }

    long fieldElementSize = fieldLayout.size / elementCount;
    if (fieldElementSize <= 0) {
        fieldElementSize = 4;
    }

    if (!emitIndexOffsetIntoAddress(ownerAddrReg, node.getIndices(), fieldLayout.dimensions, fieldElementSize, node.getLineNumber())) {
        _regs.release(ownerAddrReg);
        return -1;
    }

    return ownerAddrReg;
}

bool CodeGenVisitor::emitStoreTarget(const std::shared_ptr<ASTNode>& target, int valueReg) {
    if (target == nullptr || valueReg < 0) {
        return false;
    }

    if (auto id = std::dynamic_pointer_cast<IdNode>(target)) {
        if (!hasOffset(id->getName())) {
            reportError(id->getLineNumber(), "assignment target not allocated: '" + id->getName() + "'");
            return false;
        }

        emit("sw " + std::to_string(lookupOffset(id->getName())) + "(r14), " + regName(valueReg));
        return true;
    }

    auto dataMember = std::dynamic_pointer_cast<DataMemberNode>(target);
    if (dataMember == nullptr) {
        reportError(target->getLineNumber(), "unsupported assignment target in code generation");
        return false;
    }

    const int addrReg = emitAddressForDataMember(*dataMember);
    if (addrReg < 0) {
        return false;
    }

    emit("sw 0(" + regName(addrReg) + "), " + regName(valueReg));
    _regs.release(addrReg);
    return true;
}

void CodeGenVisitor::emitFunctionBody(const std::shared_ptr<FuncDefNode>& functionNode) {
    if (functionNode == nullptr) {
        return;
    }

    resetFunctionState();
    _currentFunction = functionNode->getName();

    emitComment("function " + _currentFunction);

    if (!functionNode->getParams().empty()) {
        assignOffsets(functionNode->getParams());
    }
    if (!functionNode->getLocalVars().empty()) {
        assignOffsets(functionNode->getLocalVars());
    }

    if (functionNode->getRight() != nullptr) {
        functionNode->getRight()->accept(*this);
    }

    if (_currentFunction != "main") {
        emit("jr r15");
    }
}

void CodeGenVisitor::visit(IdNode& node) {
    if (!hasOffset(node.getName())) {
        reportError(node.getLineNumber(), "unknown identifier in code generation: '" + node.getName() + "'");
        _lastExprReg = -1;
        return;
    }

    int reg = _regs.acquire();
    if (reg < 0) {
        reportError(node.getLineNumber(), "register exhaustion while loading identifier");
        _lastExprReg = -1;
        return;
    }

    emit("lw " + regName(reg) + ", " + std::to_string(lookupOffset(node.getName())) + "(r14)");
    _lastExprReg = reg;
}

void CodeGenVisitor::visit(IntLitNode& node) {
    int reg = _regs.acquire();
    if (reg < 0) {
        reportError(node.getLineNumber(), "register exhaustion while loading integer literal");
        _lastExprReg = -1;
        return;
    }

    emit("addi " + regName(reg) + ", r0, " + std::to_string(node.getIntValue()));
    _lastExprReg = reg;
}

void CodeGenVisitor::visit(FloatLitNode& node) {
    int reg = _regs.acquire();
    if (reg < 0) {
        reportError(node.getLineNumber(), "register exhaustion while loading float literal");
        _lastExprReg = -1;
        return;
    }

    const long lowered = static_cast<long>(std::llround(node.getFloatValue()));
    emitComment("float literal lowered to integer immediate");
    emit("addi " + regName(reg) + ", r0, " + std::to_string(lowered));
    _lastExprReg = reg;
}

void CodeGenVisitor::visit(TypeNode&) {
    _lastExprReg = -1;
}

void CodeGenVisitor::visit(BinaryOpNode& node) {
    int leftReg = evalExpr(node.getLeft());
    int rightReg = evalExpr(node.getRight());

    if (leftReg < 0 || rightReg < 0) {
        if (leftReg > 0) {
            _regs.release(leftReg);
        }
        if (rightReg > 0) {
            _regs.release(rightReg);
        }
        _lastExprReg = -1;
        return;
    }

    const std::string op = node.getOperator();

    if (op == "+") {
        emit("add " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == "-") {
        emit("sub " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == "*") {
        emit("mul " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == "/") {
        emit("div " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == "mod") {
        emit("mod " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == "and" || op == "&&") {
        emit("and " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == "or" || op == "||") {
        emit("or " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == "==") {
        emit("ceq " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == "!=") {
        emit("cne " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == "<") {
        emit("clt " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == "<=") {
        emit("cle " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == ">") {
        emit("cgt " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == ">=") {
        emit("cge " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else {
        reportError(node.getLineNumber(), "unsupported binary operator in code generation: '" + op + "'");
    }

    _regs.release(rightReg);
    _lastExprReg = leftReg;
}

void CodeGenVisitor::visit(UnaryOpNode& node) {
    int operandReg = evalExpr(node.getLeft());
    if (operandReg < 0) {
        _lastExprReg = -1;
        return;
    }

    const std::string op = node.getOperator();
    if (op == "-") {
        emit("sub " + regName(operandReg) + ", r0, " + regName(operandReg));
    } else if (op == "not") {
        emit("ceqi " + regName(operandReg) + ", " + regName(operandReg) + ", 0");
    } else if (op != "+") {
        reportError(node.getLineNumber(), "unsupported unary operator in code generation: '" + op + "'");
    }

    _lastExprReg = operandReg;
}

void CodeGenVisitor::visit(FuncCallNode& node) {
    reportError(node.getLineNumber(), "function call code generation is not implemented yet");

    int reg = _regs.acquire();
    if (reg >= 0) {
        emit("addi " + regName(reg) + ", r0, 0");
    }
    _lastExprReg = reg;
}

void CodeGenVisitor::visit(DataMemberNode& node) {
    const int addrReg = emitAddressForDataMember(node);
    if (addrReg < 0) {
        _lastExprReg = -1;
        return;
    }

    const int valueReg = _regs.acquire();
    if (valueReg < 0) {
        _regs.release(addrReg);
        reportError(node.getLineNumber(), "register exhaustion while loading data member");
        _lastExprReg = -1;
        return;
    }

    emit("lw " + regName(valueReg) + ", 0(" + regName(addrReg) + ")");
    _regs.release(addrReg);
    _lastExprReg = valueReg;
}

void CodeGenVisitor::visit(AssignStmtNode& node) {
    int valueReg = evalExpr(node.getRight());
    if (valueReg < 0) {
        return;
    }

    if (!emitStoreTarget(node.getLeft(), valueReg)) {
        _regs.release(valueReg);
        return;
    }

    _regs.release(valueReg);
}

void CodeGenVisitor::visit(IfStmtNode& node) {
    int condReg = evalExpr(node.getLeft());
    if (condReg < 0) {
        return;
    }

    const std::string elseLabel = makeLabel("else");
    const std::string endLabel = makeLabel("endif");

    emit("bz " + regName(condReg) + ", " + elseLabel);
    _regs.release(condReg);

    if (node.getRight() != nullptr) {
        node.getRight()->accept(*this);
    }

    emit("j " + endLabel);
    emit(elseLabel);

    if (node.getElseBlock() != nullptr) {
        node.getElseBlock()->accept(*this);
    }

    emit(endLabel);
}

void CodeGenVisitor::visit(WhileStmtNode& node) {
    const std::string startLabel = makeLabel("while_start");
    const std::string endLabel = makeLabel("while_end");

    emit(startLabel);

    int condReg = evalExpr(node.getLeft());
    if (condReg < 0) {
        return;
    }

    emit("bz " + regName(condReg) + ", " + endLabel);
    _regs.release(condReg);

    if (node.getRight() != nullptr) {
        node.getRight()->accept(*this);
    }

    emit("j " + startLabel);
    emit(endLabel);
}

void CodeGenVisitor::visit(IOStmtNode& node) {
    const std::string ioType = node.getValue();

    if (ioType == "read") {
        int inputReg = _regs.acquire();
        if (inputReg < 0) {
            reportError(node.getLineNumber(), "register exhaustion while generating read statement");
            return;
        }

        emit("getc " + regName(inputReg));
        emitStoreTarget(node.getLeft(), inputReg);
        _regs.release(inputReg);
        return;
    }

    if (ioType == "write") {
        int valueReg = evalExpr(node.getLeft());
        if (valueReg < 0) {
            return;
        }

        emit("putc " + regName(valueReg));
        _regs.release(valueReg);
        return;
    }

    reportError(node.getLineNumber(), "unknown I/O statement kind in code generation: '" + ioType + "'");
}

void CodeGenVisitor::visit(ReturnStmtNode& node) {
    if (node.getLeft() != nullptr) {
        int retReg = evalExpr(node.getLeft());
        if (retReg >= 0) {
            emitComment("return value currently lowered into r1");
            emit("add r1, " + regName(retReg) + ", r0");
            _regs.release(retReg);
        }
    }

    if (_currentFunction != "main") {
        emit("jr r15");
    }
}

void CodeGenVisitor::visit(BlockNode& node) {
    for (const auto& stmt : node.getStatements()) {
        if (stmt != nullptr) {
            stmt->accept(*this);
        }
    }
}

void CodeGenVisitor::visit(VarDeclNode&) {
    // Storage is assigned when entering a function frame.
}

void CodeGenVisitor::visit(FuncDefNode& node) {
    if (node.getClassName().empty() && node.getName() == "main") {
        emitFunctionBody(std::make_shared<FuncDefNode>(node));
        return;
    }

    emitComment("skipping non-main function in current code generator: " + node.getName());
}

void CodeGenVisitor::visit(ClassDeclNode& node) {
    emitComment("class code generation not implemented for: " + node.getName());
}

void CodeGenVisitor::visit(ProgNode& node) {
    _classDecls.clear();
    _classLayouts.clear();
    _classSizes.clear();

    for (const auto& cls : node.getClasses()) {
        if (cls != nullptr) {
            _classDecls[cls->getName()] = cls;
        }
    }

    for (const auto& cls : node.getClasses()) {
        if (cls != nullptr) {
            cls->accept(*this);
        }
    }

    std::shared_ptr<FuncDefNode> mainFunction = nullptr;
    for (const auto& fn : node.getFunctions()) {
        if (fn != nullptr && fn->getClassName().empty() && fn->getName() == "main") {
            mainFunction = fn;
            break;
        }
    }

    if (mainFunction == nullptr) {
        reportError(0, "program has no main function for code generation");
        return;
    }

    emitFunctionBody(mainFunction);
}

bool generateMoonAssembly(const std::shared_ptr<ProgNode>& root, const std::string& outputPath, std::vector<std::string>* errors) {
    std::ofstream out(outputPath, std::ios::out | std::ios::trunc | std::ios::binary);
    if (!out.is_open()) {
        if (errors != nullptr) {
            errors->push_back("[ERROR][CODEGEN] Failed to open output file: " + outputPath);
        }
        return false;
    }

    CodeGenVisitor generator(out);
    const bool success = generator.generate(root);

    if (errors != nullptr) {
        *errors = generator.getErrors();
    }

    return success;
}
