#include "../include/codegen.h"

#include <algorithm>
#include <cmath>
#include <fstream>
#include <sstream>
#include <cctype>

namespace {
std::string regName(int reg) {
    return "r" + std::to_string(reg);
}

std::string trimCopy(const std::string& raw) {
    size_t start = 0;
    while (start < raw.size() && std::isspace(static_cast<unsigned char>(raw[start]))) {
        ++start;
    }

    size_t end = raw.size();
    while (end > start && std::isspace(static_cast<unsigned char>(raw[end - 1]))) {
        --end;
    }

    return raw.substr(start, end - start);
}

bool isBasicScalarType(const std::string& typeName) {
    return typeName == "integer" || typeName == "float" || typeName == "bool";
}

constexpr int kFloatScale = 100;
}

CodeGenVisitor::RegisterAllocator::RegisterAllocator() {
    reset();
}

int CodeGenVisitor::RegisterAllocator::acquire() {
    if (_freeRegs.empty()) {
        return -1;
    }

    const int reg = _freeRegs.back();
    _freeRegs.pop_back();
    return reg;
}

void CodeGenVisitor::RegisterAllocator::release(int reg) {
    if (reg <= 0 || reg > 12) {
        return;
    }

    if (std::find(_freeRegs.begin(), _freeRegs.end(), reg) == _freeRegs.end()) {
        _freeRegs.push_back(reg);
    }
}

void CodeGenVisitor::RegisterAllocator::reset() {
    _freeRegs.clear();
    for (int reg = 12; reg >= 1; --reg) {
        _freeRegs.push_back(reg);
    }
}

CodeGenVisitor::CodeGenVisitor(std::ostream& out)
    : _out(out) {}

bool CodeGenVisitor::generate(const std::shared_ptr<ProgNode>& root) {
    _errors.clear();
    _labelCounter = 0;

    if (root == nullptr) {
        reportError(0, "cannot generate code from an empty AST");
        return false;
    }

    emitComment("Moon assembly generated by CodeGenVisitor");
    emit("entry");
    emit("addi r14, r0, topaddr");

    root->accept(*this);

    emit("hlt");
    emitRuntimeIntegerIO();

    return _errors.empty();
}

const std::vector<std::string>& CodeGenVisitor::getErrors() const {
    return _errors;
}

void CodeGenVisitor::emit(const std::string& line) {
    _out << line << "\n";
}

void CodeGenVisitor::emitComment(const std::string& message) {
    emit("% " + message);
}

void CodeGenVisitor::reportError(int line, const std::string& message) {
    _errors.push_back("[ERROR][CODEGEN] line " + std::to_string(line) + ": " + message);
}

std::string CodeGenVisitor::sanitizeName(const std::string& raw) {
    std::string result;
    result.reserve(raw.size());

    for (char c : raw) {
        if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_') {
            result.push_back(c);
        } else {
            result.push_back('_');
        }
    }

    if (result.empty()) {
        return "anon";
    }

    return result;
}

std::string CodeGenVisitor::makeLabel(const std::string& prefix) {
    return sanitizeName(prefix) + "_" + std::to_string(++_labelCounter);
}

std::string CodeGenVisitor::functionKey(const std::string& className, const std::string& functionName) {
    if (className.empty()) {
        return functionName;
    }
    return className + "::" + functionName;
}

void CodeGenVisitor::resetFunctionState() {
    _stackOffsets.clear();
    _stackVarInfo.clear();
    _nextOffset = 0;
    _regs.reset();
    _lastExprReg = -1;
}

bool CodeGenVisitor::buildFunctionLayout(const std::shared_ptr<FuncDefNode>& functionNode) {
    if (functionNode == nullptr || functionNode->getRight() == nullptr) {
        return false;
    }

    FunctionLayoutInfo layout;
    layout.className = trimCopy(functionNode->getClassName());
    layout.name = functionNode->getName();
    layout.isMethod = !layout.className.empty();
    layout.key = functionKey(layout.className, layout.name);
    layout.label = "fn_" + sanitizeName(layout.key);

    long cursor = -4; // saved return link
    layout.returnLinkOffset = -4;

    if (layout.isMethod) {
        cursor -= 4;
        layout.thisOffset = cursor;
    }

    for (const auto& param : functionNode->getParams()) {
        const long paramSize = sizeOfVar(param);
        if (paramSize <= 0) {
            return false;
        }

        cursor -= paramSize;
        layout.paramNames.push_back(param->getName());
        layout.paramOffsets.push_back(cursor);
        layout.varOffsets[param->getName()] = cursor;

        const bool isArrayParam = !param->getDimensions().empty();
        long paramElementSize = sizeOfType(param->getTypeName(), param->getLineNumber());
        if (paramElementSize <= 0) {
            return false;
        }

        layout.varInfo[param->getName()] = {
            trimCopy(param->getTypeName()),
            param->getDimensions(),
            paramElementSize,
            isArrayParam
        };
    }

    for (const auto& local : functionNode->getLocalVars()) {
        const long localSize = sizeOfVar(local);
        if (localSize <= 0) {
            return false;
        }

        cursor -= localSize;
        layout.varOffsets[local->getName()] = cursor;

        long localElements = 1;
        for (int dim : local->getDimensions()) {
            if (dim > 0) {
                localElements *= dim;
            }
        }

        long localElementSize = (localElements > 0) ? (localSize / localElements) : 4;
        if (localElementSize <= 0) {
            localElementSize = 4;
        }

        layout.varInfo[local->getName()] = {
            trimCopy(local->getTypeName()),
            local->getDimensions(),
            localElementSize,
            false
        };
    }

    layout.frameSize = -cursor;
    if (layout.frameSize < 4) {
        layout.frameSize = 4;
    }

    _functionLayouts[layout.key] = layout;
    return true;
}

const CodeGenVisitor::FunctionLayoutInfo* CodeGenVisitor::findFunctionLayout(const std::string& className, const std::string& functionName) const {
    const std::string key = functionKey(trimCopy(className), functionName);
    auto it = _functionLayouts.find(key);
    if (it == _functionLayouts.end()) {
        return nullptr;
    }
    return &it->second;
}

long CodeGenVisitor::sizeOfType(const std::string& typeName, int line) {
    const std::string cleanType = trimCopy(typeName);
    if (cleanType.empty()) {
        reportError(line, "cannot compute storage size for empty type name");
        return -1;
    }

    if (isBasicScalarType(cleanType)) {
        return 4;
    }

    std::unordered_set<std::string> visiting;
    return sizeOfClass(cleanType, visiting, line);
}

bool CodeGenVisitor::buildClassLayout(const std::string& className, std::unordered_set<std::string>& visiting, int line) {
    const std::string cleanClassName = trimCopy(className);

    if (_classLayouts.find(cleanClassName) != _classLayouts.end()) {
        return true;
    }

    if (visiting.find(cleanClassName) != visiting.end()) {
        reportError(line, "circular class storage dependency while building layout for '" + cleanClassName + "'");
        return false;
    }

    auto declIt = _classDecls.find(cleanClassName);
    if (declIt == _classDecls.end() || declIt->second == nullptr) {
        reportError(line, "unknown class type in storage allocation: '" + cleanClassName + "'");
        return false;
    }

    visiting.insert(cleanClassName);

    ClassLayoutInfo layout;
    long runningOffset = 0;

    for (const auto& parentName : declIt->second->getParents()) {
        if (!buildClassLayout(parentName, visiting, line)) {
            visiting.erase(cleanClassName);
            return false;
        }

        const ClassLayoutInfo& parentLayout = _classLayouts[parentName];
        for (const auto& kv : parentLayout.fields) {
            FieldLayoutInfo inherited = kv.second;
            inherited.offset += runningOffset;
            if (layout.fields.find(kv.first) == layout.fields.end()) {
                layout.fields[kv.first] = inherited;
            }
        }

        runningOffset += parentLayout.size;
    }

    for (const auto& member : declIt->second->getMembers()) {
        auto fieldDecl = std::dynamic_pointer_cast<VarDeclNode>(member);
        if (fieldDecl == nullptr) {
            continue;
        }

        const long fieldSize = sizeOfVar(fieldDecl);
        if (fieldSize <= 0) {
            visiting.erase(cleanClassName);
            return false;
        }

        FieldLayoutInfo field;
        field.typeName = trimCopy(fieldDecl->getTypeName());
        field.dimensions = fieldDecl->getDimensions();
        field.offset = runningOffset;
        field.size = fieldSize;

        layout.fields[fieldDecl->getName()] = field;
        runningOffset += fieldSize;
    }

    if (runningOffset <= 0) {
        runningOffset = 4;
    }

    layout.size = runningOffset;
    _classLayouts[cleanClassName] = layout;
    _classSizes[cleanClassName] = layout.size;

    visiting.erase(cleanClassName);
    return true;
}

long CodeGenVisitor::sizeOfClass(const std::string& className, std::unordered_set<std::string>& visiting, int line) {
    const std::string cleanClassName = trimCopy(className);

    auto knownSize = _classSizes.find(cleanClassName);
    if (knownSize != _classSizes.end()) {
        return knownSize->second;
    }

    if (!buildClassLayout(cleanClassName, visiting, line)) {
        return -1;
    }

    knownSize = _classSizes.find(cleanClassName);
    if (knownSize != _classSizes.end()) {
        return knownSize->second;
    }

    reportError(line, "failed to compute class size for '" + cleanClassName + "'");
    return -1;
}

bool CodeGenVisitor::lookupFieldLayout(const std::string& className, const std::string& fieldName, FieldLayoutInfo& out, int line) {
    const std::string cleanClassName = trimCopy(className);
    std::unordered_set<std::string> visiting;
    if (!buildClassLayout(cleanClassName, visiting, line)) {
        return false;
    }

    auto classIt = _classLayouts.find(cleanClassName);
    if (classIt == _classLayouts.end()) {
        reportError(line, "class layout missing for '" + cleanClassName + "'");
        return false;
    }

    auto fieldIt = classIt->second.fields.find(fieldName);
    if (fieldIt == classIt->second.fields.end()) {
        reportError(line, "class '" + cleanClassName + "' has no field '" + fieldName + "' in code generation");
        return false;
    }

    out = fieldIt->second;
    return true;
}

long CodeGenVisitor::sizeOfVar(const std::shared_ptr<VarDeclNode>& decl) {
    if (decl == nullptr) {
        return 0;
    }

    if (decl->getVisibility() == "param" && !decl->getDimensions().empty()) {
        return 4;
    }

    long elements = 1;
    for (int dim : decl->getDimensions()) {
        if (dim <= 0) {
            reportError(decl->getLineNumber(), "invalid array dimension for variable '" + decl->getName() + "'");
            return -1;
        }

        elements *= dim;
    }

    const long elementSize = sizeOfType(decl->getTypeName(), decl->getLineNumber());
    if (elementSize <= 0) {
        return -1;
    }

    return elements * elementSize;
}

void CodeGenVisitor::assignOffsets(const std::vector<std::shared_ptr<VarDeclNode>>& vars) {
    for (const auto& var : vars) {
        if (var == nullptr) {
            continue;
        }

        const std::string name = var->getName();
        if (name.empty()) {
            continue;
        }

        const long varSize = sizeOfVar(var);
        if (varSize <= 0) {
            reportError(var->getLineNumber(), "invalid storage size for variable '" + name + "'");
            continue;
        }

        if (_stackOffsets.find(name) != _stackOffsets.end()) {
            reportError(var->getLineNumber(), "duplicate variable in codegen frame: '" + name + "'");
            continue;
        }

        _nextOffset -= varSize;
        _stackOffsets[name] = _nextOffset;

        long elements = 1;
        for (int dim : var->getDimensions()) {
            if (dim > 0) {
                elements *= dim;
            }
        }

        long elementSize = (elements > 0) ? (varSize / elements) : 4;
        if (elementSize <= 0) {
            elementSize = 4;
        }

        _stackVarInfo[name] = {
            trimCopy(var->getTypeName()),
            var->getDimensions(),
            elementSize,
            var->getVisibility() == "param" && !var->getDimensions().empty()
        };

        emitComment("alloc " + name + " @ " + std::to_string(_nextOffset) + "(r14), size=" + std::to_string(varSize));
    }
}

bool CodeGenVisitor::hasOffset(const std::string& name) const {
    return _stackOffsets.find(name) != _stackOffsets.end();
}

long CodeGenVisitor::lookupOffset(const std::string& name) const {
    auto it = _stackOffsets.find(name);
    if (it == _stackOffsets.end()) {
        return 0;
    }

    return it->second;
}

int CodeGenVisitor::evalExpr(const std::shared_ptr<ASTNode>& node) {
    _lastExprReg = -1;

    if (node == nullptr) {
        reportError(0, "null expression in code generation");
        return -1;
    }

    node->accept(*this);
    return _lastExprReg;
}

bool CodeGenVisitor::loadThisPointerInto(int targetReg, int line) {
    if (targetReg < 0) {
        return false;
    }

    if (_currentClassName.empty() || _currentThisOffset == 0) {
        reportError(line, "implicit receiver is unavailable outside member function context");
        return false;
    }

    emit("lw " + regName(targetReg) + ", " + std::to_string(_currentThisOffset) + "(r14)");
    return true;
}

bool CodeGenVisitor::resolveDataMemberType(const std::shared_ptr<DataMemberNode>& node, std::string& typeName, std::vector<int>& dimensions) {
    if (node == nullptr) {
        return false;
    }

    if (node->getLeft() == nullptr) {
        auto infoIt = _stackVarInfo.find(node->getName());
        if (infoIt == _stackVarInfo.end()) {
            reportError(node->getLineNumber(), "unknown variable '" + node->getName() + "' in type resolution");
            return false;
        }

        typeName = infoIt->second.typeName;
        dimensions = infoIt->second.dimensions;
    } else {
        std::string ownerType;
        std::vector<int> ownerDimensions;
        if (!resolveNodeType(node->getLeft(), ownerType, ownerDimensions)) {
            return false;
        }

        if (!ownerDimensions.empty()) {
            reportError(node->getLineNumber(), "member access requires scalar object owner for '" + node->getName() + "'");
            return false;
        }

        FieldLayoutInfo fieldLayout;
        if (!lookupFieldLayout(ownerType, node->getName(), fieldLayout, node->getLineNumber())) {
            return false;
        }

        typeName = fieldLayout.typeName;
        dimensions = fieldLayout.dimensions;
    }

    if (node->getIndices().size() > dimensions.size()) {
        reportError(node->getLineNumber(), "too many indices for member '" + node->getName() + "' in type resolution");
        return false;
    }

    dimensions.erase(dimensions.begin(), dimensions.begin() + static_cast<long long>(node->getIndices().size()));
    return true;
}

bool CodeGenVisitor::resolveNodeType(const std::shared_ptr<ASTNode>& node, std::string& typeName, std::vector<int>& dimensions) {
    if (node == nullptr) {
        return false;
    }

    if (auto idNode = std::dynamic_pointer_cast<IdNode>(node)) {
        auto infoIt = _stackVarInfo.find(idNode->getName());
        if (infoIt != _stackVarInfo.end()) {
            typeName = infoIt->second.typeName;
            dimensions = infoIt->second.dimensions;
            return true;
        }

        if (!_currentClassName.empty()) {
            FieldLayoutInfo fieldLayout;
            if (lookupFieldLayout(_currentClassName, idNode->getName(), fieldLayout, idNode->getLineNumber())) {
                typeName = fieldLayout.typeName;
                dimensions = fieldLayout.dimensions;
                return true;
            }
        }

        reportError(idNode->getLineNumber(), "unknown identifier '" + idNode->getName() + "' in type resolution");
        return false;
    }

    if (auto dataMember = std::dynamic_pointer_cast<DataMemberNode>(node)) {
        return resolveDataMemberType(dataMember, typeName, dimensions);
    }

    if (std::dynamic_pointer_cast<IntLitNode>(node) != nullptr) {
        typeName = "integer";
        dimensions.clear();
        return true;
    }

    if (std::dynamic_pointer_cast<FloatLitNode>(node) != nullptr) {
        typeName = "float";
        dimensions.clear();
        return true;
    }

    if (auto unaryNode = std::dynamic_pointer_cast<UnaryOpNode>(node)) {
        return resolveNodeType(unaryNode->getLeft(), typeName, dimensions);
    }

    if (auto binaryNode = std::dynamic_pointer_cast<BinaryOpNode>(node)) {
        std::string leftType;
        std::vector<int> leftDims;
        std::string rightType;
        std::vector<int> rightDims;
        if (!resolveNodeType(binaryNode->getLeft(), leftType, leftDims) || !resolveNodeType(binaryNode->getRight(), rightType, rightDims)) {
            return false;
        }

        const std::string op = binaryNode->getOperator();
        if (op == "==" || op == "!=" || op == "<" || op == ">" || op == "<=" || op == ">=" || op == "and" || op == "or" || op == "&&" || op == "||") {
            typeName = "bool";
        } else if (leftType == "float" || rightType == "float") {
            typeName = "float";
        } else {
            typeName = "integer";
        }

        dimensions.clear();
        return true;
    }

    return false;
}

bool CodeGenVisitor::emitIndexOffsetIntoAddress(int addrReg,
                                                const std::vector<std::shared_ptr<ASTNode>>& indices,
                                                const std::vector<int>& declaredDimensions,
                                                long elementSize,
                                                int line) {
    if (indices.empty()) {
        return true;
    }

    if (indices.size() > declaredDimensions.size()) {
        reportError(line, "too many array indices in code generation");
        return false;
    }

    const int linearReg = _regs.acquire();
    if (linearReg < 0) {
        reportError(line, "register exhaustion while generating indexed address");
        return false;
    }

    emit("addi " + regName(linearReg) + ", r0, 0");

    for (size_t i = 0; i < indices.size(); ++i) {
        const int idxReg = evalExpr(indices[i]);
        if (idxReg < 0) {
            _regs.release(linearReg);
            return false;
        }

        long stride = 1;
        for (size_t j = i + 1; j < declaredDimensions.size(); ++j) {
            const int dim = declaredDimensions[j];
            if (dim <= 0) {
                _regs.release(idxReg);
                _regs.release(linearReg);
                reportError(line, "invalid declared array dimension in indexed addressing");
                return false;
            }
            stride *= dim;
        }

        if (stride != 1) {
            emit("muli " + regName(idxReg) + ", " + regName(idxReg) + ", " + std::to_string(stride));
        }

        emit("add " + regName(linearReg) + ", " + regName(linearReg) + ", " + regName(idxReg));
        _regs.release(idxReg);
    }

    if (elementSize != 1) {
        emit("muli " + regName(linearReg) + ", " + regName(linearReg) + ", " + std::to_string(elementSize));
    }

    emit("add " + regName(addrReg) + ", " + regName(addrReg) + ", " + regName(linearReg));
    _regs.release(linearReg);
    return true;
}

int CodeGenVisitor::emitAddressForLValue(const std::shared_ptr<ASTNode>& node, int line) {
    if (node == nullptr) {
        reportError(line, "null l-value in address generation");
        return -1;
    }

    if (auto idNode = std::dynamic_pointer_cast<IdNode>(node)) {
        if (hasOffset(idNode->getName())) {
            const int addrReg = _regs.acquire();
            if (addrReg < 0) {
                reportError(idNode->getLineNumber(), "register exhaustion while generating l-value address");
                return -1;
            }

            const auto infoIt = _stackVarInfo.find(idNode->getName());
            const bool isReferenceParam =
                infoIt != _stackVarInfo.end() && infoIt->second.isReferenceParam;

            if (isReferenceParam) {
                emit("lw " + regName(addrReg) + ", " + std::to_string(lookupOffset(idNode->getName())) + "(r14)");
            } else {
                emit("addi " + regName(addrReg) + ", r14, " + std::to_string(lookupOffset(idNode->getName())));
            }
            return addrReg;
        }

        if (!_currentClassName.empty()) {
            FieldLayoutInfo fieldLayout;
            if (lookupFieldLayout(_currentClassName, idNode->getName(), fieldLayout, idNode->getLineNumber())) {
                const int addrReg = _regs.acquire();
                if (addrReg < 0) {
                    reportError(idNode->getLineNumber(), "register exhaustion while generating field address");
                    return -1;
                }

                if (!loadThisPointerInto(addrReg, idNode->getLineNumber())) {
                    _regs.release(addrReg);
                    return -1;
                }

                if (fieldLayout.offset != 0) {
                    emit("addi " + regName(addrReg) + ", " + regName(addrReg) + ", " + std::to_string(fieldLayout.offset));
                }
                return addrReg;
            }
        }

        reportError(idNode->getLineNumber(), "unknown variable '" + idNode->getName() + "' in code generation");
        return -1;
    }

    if (auto memberNode = std::dynamic_pointer_cast<DataMemberNode>(node)) {
        return emitAddressForDataMember(*memberNode);
    }

    reportError(line, "unsupported l-value expression in address generation");
    return -1;
}

int CodeGenVisitor::emitAddressForDataMember(DataMemberNode& node) {
    if (node.getLeft() == nullptr) {
        if (!hasOffset(node.getName())) {
            reportError(node.getLineNumber(), "unknown variable '" + node.getName() + "' in code generation");
            return -1;
        }

        const int addrReg = _regs.acquire();
        if (addrReg < 0) {
            reportError(node.getLineNumber(), "register exhaustion while generating l-value address");
            return -1;
        }

        std::vector<int> declaredDimensions;
        long elementSize = 4;
        bool isReferenceParam = false;
        auto infoIt = _stackVarInfo.find(node.getName());
        if (infoIt != _stackVarInfo.end()) {
            declaredDimensions = infoIt->second.dimensions;
            elementSize = infoIt->second.elementSize;
            isReferenceParam = infoIt->second.isReferenceParam;
        }

        if (isReferenceParam) {
            emit("lw " + regName(addrReg) + ", " + std::to_string(lookupOffset(node.getName())) + "(r14)");
        } else {
            emit("addi " + regName(addrReg) + ", r14, " + std::to_string(lookupOffset(node.getName())));
        }

        if (!emitIndexOffsetIntoAddress(addrReg, node.getIndices(), declaredDimensions, elementSize, node.getLineNumber())) {
            _regs.release(addrReg);
            return -1;
        }

        return addrReg;
    }

    const int ownerAddrReg = emitAddressForLValue(node.getLeft(), node.getLineNumber());
    if (ownerAddrReg < 0) {
        return -1;
    }

    std::string ownerType;
    std::vector<int> ownerDimensions;
    if (!resolveNodeType(node.getLeft(), ownerType, ownerDimensions)) {
        _regs.release(ownerAddrReg);
        return -1;
    }

    if (!ownerDimensions.empty()) {
        reportError(node.getLineNumber(), "member access requires scalar object owner for '" + node.getName() + "'");
        _regs.release(ownerAddrReg);
        return -1;
    }

    FieldLayoutInfo fieldLayout;
    if (!lookupFieldLayout(ownerType, node.getName(), fieldLayout, node.getLineNumber())) {
        _regs.release(ownerAddrReg);
        return -1;
    }

    if (fieldLayout.offset != 0) {
        emit("addi " + regName(ownerAddrReg) + ", " + regName(ownerAddrReg) + ", " + std::to_string(fieldLayout.offset));
    }

    long elementCount = 1;
    for (int dim : fieldLayout.dimensions) {
        if (dim <= 0) {
            _regs.release(ownerAddrReg);
            reportError(node.getLineNumber(), "invalid declared field array dimension");
            return -1;
        }
        elementCount *= dim;
    }

    long fieldElementSize = fieldLayout.size / elementCount;
    if (fieldElementSize <= 0) {
        fieldElementSize = 4;
    }

    if (!emitIndexOffsetIntoAddress(ownerAddrReg, node.getIndices(), fieldLayout.dimensions, fieldElementSize, node.getLineNumber())) {
        _regs.release(ownerAddrReg);
        return -1;
    }

    return ownerAddrReg;
}

bool CodeGenVisitor::emitStoreTarget(const std::shared_ptr<ASTNode>& target, int valueReg) {
    if (target == nullptr || valueReg < 0) {
        return false;
    }

    if (std::dynamic_pointer_cast<IdNode>(target) == nullptr &&
        std::dynamic_pointer_cast<DataMemberNode>(target) == nullptr) {
        reportError(target->getLineNumber(), "unsupported assignment target in code generation");
        return false;
    }

    const int addrReg = emitAddressForLValue(target, target->getLineNumber());
    if (addrReg < 0) {
        return false;
    }

    emit("sw 0(" + regName(addrReg) + "), " + regName(valueReg));
    _regs.release(addrReg);
    return true;
}

void CodeGenVisitor::emitFunctionBody(const std::shared_ptr<FuncDefNode>& functionNode,
                                      const FunctionLayoutInfo& layout,
                                      bool isMainBody) {
    if (functionNode == nullptr) {
        return;
    }

    resetFunctionState();

    _currentFunction = functionNode->getName();
    _currentClassName = layout.className;
    _currentFrameSize = layout.frameSize;
    _currentThisOffset = layout.thisOffset;
    _currentReturnLabel = layout.label + "_ret";
    _currentReturnType = trimCopy(functionNode->getReturnType());

    _stackOffsets = layout.varOffsets;
    _stackVarInfo = layout.varInfo;

    if (!isMainBody) {
        emit(layout.label);
        emit("sw " + std::to_string(layout.returnLinkOffset) + "(r14), r15");
    }

    emitComment("function " + layout.key + ", frame=" + std::to_string(layout.frameSize));

    if (functionNode->getRight() != nullptr) {
        functionNode->getRight()->accept(*this);
    }

    if (!isMainBody) {
        emit(_currentReturnLabel);
        emit("lw r15, " + std::to_string(layout.returnLinkOffset) + "(r14)");
        emit("jr r15");
    }
}

void CodeGenVisitor::emitRuntimeIntegerIO() {
    emitComment("runtime helper: rt_readInt (returns parsed integer in r1)");
    emit("rt_readInt");
    emit("addi r1, r0, 0");
    emit("addi r2, r0, 1");
    emit("rt_readInt_skip_ws");
    emit("getc r3");
    emit("andi r3, r3, 255");
    emit("ceqi r4, r3, 32");
    emit("bz r4, rt_readInt_check_tab");
    emit("j rt_readInt_skip_ws");
    emit("rt_readInt_check_tab");
    emit("ceqi r4, r3, 9");
    emit("bz r4, rt_readInt_check_lf");
    emit("j rt_readInt_skip_ws");
    emit("rt_readInt_check_lf");
    emit("ceqi r4, r3, 10");
    emit("bz r4, rt_readInt_check_cr");
    emit("j rt_readInt_skip_ws");
    emit("rt_readInt_check_cr");
    emit("ceqi r4, r3, 13");
    emit("bz r4, rt_readInt_check_sign");
    emit("j rt_readInt_skip_ws");
    emit("rt_readInt_check_sign");
    emit("ceqi r4, r3, 45");
    emit("bz r4, rt_readInt_check_plus");
    emit("addi r2, r0, -1");
    emit("getc r3");
    emit("andi r3, r3, 255");
    emit("j rt_readInt_digit_loop");
    emit("rt_readInt_check_plus");
    emit("ceqi r4, r3, 43");
    emit("bz r4, rt_readInt_digit_loop");
    emit("getc r3");
    emit("andi r3, r3, 255");
    emit("rt_readInt_digit_loop");
    emit("addi r6, r0, 48");
    emit("addi r7, r0, 57");
    emit("clt r4, r3, r6");
    emit("bz r4, rt_readInt_check_upper");
    emit("j rt_readInt_apply_sign");
    emit("rt_readInt_check_upper");
    emit("cgt r4, r3, r7");
    emit("bz r4, rt_readInt_consume_digit");
    emit("j rt_readInt_apply_sign");
    emit("rt_readInt_consume_digit");
    emit("muli r1, r1, 10");
    emit("sub r8, r3, r6");
    emit("add r1, r1, r8");
    emit("getc r3");
    emit("andi r3, r3, 255");
    emit("j rt_readInt_digit_loop");
    emit("rt_readInt_apply_sign");
    emit("clt r4, r2, r0");
    emit("bz r4, rt_readInt_ret");
    emit("sub r1, r0, r1");
    emit("rt_readInt_ret");
    emit("jr r15");

    emitComment("runtime helper: rt_readFloat (returns fixed-point float in r1, scale=1000)");
    emit("rt_readFloat");
    emit("addi r1, r0, 0");
    emit("addi r2, r0, 1");
    emit("rt_readFloat_skip_ws");
    emit("getc r3");
    emit("andi r3, r3, 255");
    emit("ceqi r4, r3, 32");
    emit("bz r4, rt_readFloat_check_tab");
    emit("j rt_readFloat_skip_ws");
    emit("rt_readFloat_check_tab");
    emit("ceqi r4, r3, 9");
    emit("bz r4, rt_readFloat_check_lf");
    emit("j rt_readFloat_skip_ws");
    emit("rt_readFloat_check_lf");
    emit("ceqi r4, r3, 10");
    emit("bz r4, rt_readFloat_check_cr");
    emit("j rt_readFloat_skip_ws");
    emit("rt_readFloat_check_cr");
    emit("ceqi r4, r3, 13");
    emit("bz r4, rt_readFloat_check_sign");
    emit("j rt_readFloat_skip_ws");
    emit("rt_readFloat_check_sign");
    emit("ceqi r4, r3, 45");
    emit("bz r4, rt_readFloat_check_plus");
    emit("addi r2, r0, -1");
    emit("getc r3");
    emit("andi r3, r3, 255");
    emit("j rt_readFloat_int_loop");
    emit("rt_readFloat_check_plus");
    emit("ceqi r4, r3, 43");
    emit("bz r4, rt_readFloat_int_loop");
    emit("getc r3");
    emit("andi r3, r3, 255");
    emit("rt_readFloat_int_loop");
    emit("addi r6, r0, 48");
    emit("addi r7, r0, 57");
    emit("clt r4, r3, r6");
    emit("bz r4, rt_readFloat_int_check_upper");
    emit("j rt_readFloat_maybe_frac");
    emit("rt_readFloat_int_check_upper");
    emit("cgt r4, r3, r7");
    emit("bz r4, rt_readFloat_int_consume");
    emit("j rt_readFloat_maybe_frac");
    emit("rt_readFloat_int_consume");
    emit("muli r1, r1, 10");
    emit("sub r8, r3, r6");
    emit("add r1, r1, r8");
    emit("getc r3");
    emit("andi r3, r3, 255");
    emit("j rt_readFloat_int_loop");
    emit("rt_readFloat_maybe_frac");
    emit("addi r11, r0, 0");
    emit("addi r10, r0, 0");
    emit("muli r1, r1, 1000");
    emit("ceqi r4, r3, 46");
    emit("bz r4, rt_readFloat_apply_sign");
    emit("getc r3");
    emit("andi r3, r3, 255");
    emit("addi r11, r0, 100");
    emit("addi r10, r0, 0");
    emit("rt_readFloat_frac_loop");
    emit("clt r4, r3, r6");
    emit("bz r4, rt_readFloat_frac_check_upper");
    emit("j rt_readFloat_apply_sign");
    emit("rt_readFloat_frac_check_upper");
    emit("cgt r4, r3, r7");
    emit("bz r4, rt_readFloat_frac_consume");
    emit("j rt_readFloat_apply_sign");
    emit("rt_readFloat_frac_consume");
    emit("ceqi r4, r11, 0");
    emit("bz r4, rt_readFloat_frac_store");
    emit("getc r3");
    emit("andi r3, r3, 255");
    emit("j rt_readFloat_frac_loop");
    emit("rt_readFloat_frac_store");
    emit("sub r8, r3, r6");
    emit("mul r8, r8, r11");
    emit("add r10, r10, r8");
    emit("ceqi r4, r11, 1");
    emit("bz r4, rt_readFloat_frac_scale_down");
    emit("addi r11, r0, 0");
    emit("j rt_readFloat_frac_next");
    emit("rt_readFloat_frac_scale_down");
    emit("divi r11, r11, 10");
    emit("rt_readFloat_frac_next");
    emit("getc r3");
    emit("andi r3, r3, 255");
    emit("j rt_readFloat_frac_loop");
    emit("rt_readFloat_apply_sign");
    emit("add r1, r1, r10");
    emit("clt r4, r2, r0");
    emit("bz r4, rt_readFloat_ret");
    emit("sub r1, r0, r1");
    emit("rt_readFloat_ret");
    emit("jr r15");

    emitComment("runtime helper: rt_writeInt (prints integer from r1)");
    emit("rt_writeInt");
    emit("add r2, r1, r0");
    emit("ceqi r3, r2, 0");
    emit("bz r3, rt_writeInt_non_zero");
    emit("addi r4, r0, 48");
    emit("putc r4");
    emit("jr r15");
    emit("rt_writeInt_non_zero");
    emit("clt r3, r2, r0");
    emit("bz r3, rt_writeInt_reserve");
    emit("addi r4, r0, 45");
    emit("putc r4");
    emit("sub r2, r0, r2");
    emit("rt_writeInt_reserve");
    emit("subi r14, r14, 64");
    emit("add r5, r14, r0");
    emit("addi r6, r0, 0");
    emit("addi r7, r0, 10");
    emit("rt_writeInt_push_digits");
    emit("mod r8, r2, r7");
    emit("addi r8, r8, 48");
    emit("sw 0(r5), r8");
    emit("addi r5, r5, 4");
    emit("addi r6, r6, 1");
    emit("div r2, r2, r7");
    emit("cgt r9, r2, r0");
    emit("bz r9, rt_writeInt_print_setup");
    emit("j rt_writeInt_push_digits");
    emit("rt_writeInt_print_setup");
    emit("subi r5, r5, 4");
    emit("rt_writeInt_print_loop");
    emit("lw r8, 0(r5)");
    emit("putc r8");
    emit("subi r5, r5, 4");
    emit("subi r6, r6, 1");
    emit("cgt r9, r6, r0");
    emit("bz r9, rt_writeInt_done");
    emit("j rt_writeInt_print_loop");
    emit("rt_writeInt_done");
    emit("addi r14, r14, 64");
    emit("jr r15");

    emitComment("runtime helper: rt_writeFloat (prints fixed-point float from r1, scale=1000)");
    emit("rt_writeFloat");
    emit("add r2, r1, r0");
    emit("clt r3, r2, r0");
    emit("bz r3, rt_writeFloat_abs_ready");
    emit("addi r4, r0, 45");
    emit("putc r4");
    emit("sub r2, r0, r2");
    emit("rt_writeFloat_abs_ready");
    emit("divi r5, r2, 1000");
    emit("modi r6, r2, 1000");
    emit("add r11, r6, r0");
    emit("add r10, r15, r0");
    emit("add r1, r5, r0");
    emit("jl r15, rt_writeInt");
    emit("add r15, r10, r0");
    emit("add r6, r11, r0");
    emit("addi r4, r0, 46");
    emit("putc r4");
    emit("divi r7, r6, 100");
    emit("addi r7, r7, 48");
    emit("putc r7");
    emit("modi r6, r6, 100");
    emit("divi r7, r6, 10");
    emit("addi r7, r7, 48");
    emit("putc r7");
    emit("modi r7, r6, 10");
    emit("addi r7, r7, 48");
    emit("putc r7");
    emit("jr r15");
}

void CodeGenVisitor::visit(IdNode& node) {
    if (hasOffset(node.getName())) {
        int reg = _regs.acquire();
        if (reg < 0) {
            reportError(node.getLineNumber(), "register exhaustion while loading identifier");
            _lastExprReg = -1;
            return;
        }

        emit("lw " + regName(reg) + ", " + std::to_string(lookupOffset(node.getName())) + "(r14)");
        _lastExprReg = reg;
        return;
    }

    if (!_currentClassName.empty()) {
        FieldLayoutInfo fieldLayout;
        if (lookupFieldLayout(_currentClassName, node.getName(), fieldLayout, node.getLineNumber())) {
            const int addrReg = _regs.acquire();
            const int valueReg = _regs.acquire();
            if (addrReg < 0 || valueReg < 0) {
                if (addrReg > 0) {
                    _regs.release(addrReg);
                }
                if (valueReg > 0) {
                    _regs.release(valueReg);
                }
                reportError(node.getLineNumber(), "register exhaustion while loading member field");
                _lastExprReg = -1;
                return;
            }

            if (!loadThisPointerInto(addrReg, node.getLineNumber())) {
                _regs.release(addrReg);
                _regs.release(valueReg);
                _lastExprReg = -1;
                return;
            }

            if (fieldLayout.offset != 0) {
                emit("addi " + regName(addrReg) + ", " + regName(addrReg) + ", " + std::to_string(fieldLayout.offset));
            }

            emit("lw " + regName(valueReg) + ", 0(" + regName(addrReg) + ")");
            _regs.release(addrReg);
            _lastExprReg = valueReg;
            return;
        }
    }

    reportError(node.getLineNumber(), "unknown identifier in code generation: '" + node.getName() + "'");
    _lastExprReg = -1;
}

void CodeGenVisitor::visit(IntLitNode& node) {
    int reg = _regs.acquire();
    if (reg < 0) {
        reportError(node.getLineNumber(), "register exhaustion while loading integer literal");
        _lastExprReg = -1;
        return;
    }

    emit("addi " + regName(reg) + ", r0, " + std::to_string(node.getIntValue()));
    _lastExprReg = reg;
}

void CodeGenVisitor::visit(FloatLitNode& node) {
    int reg = _regs.acquire();
    if (reg < 0) {
        reportError(node.getLineNumber(), "register exhaustion while loading float literal");
        _lastExprReg = -1;
        return;
    }

    const long lowered = static_cast<long>(std::llround(node.getFloatValue() * static_cast<float>(kFloatScale)));
    emitComment("float literal lowered to fixed-point immediate (scale=" + std::to_string(kFloatScale) + ")");
    emit("addi " + regName(reg) + ", r0, " + std::to_string(lowered));
    _lastExprReg = reg;
}

void CodeGenVisitor::visit(TypeNode&) {
    _lastExprReg = -1;
}

void CodeGenVisitor::visit(BinaryOpNode& node) {
    int leftReg = evalExpr(node.getLeft());
    int rightReg = evalExpr(node.getRight());

    if (leftReg < 0 || rightReg < 0) {
        if (leftReg > 0) {
            _regs.release(leftReg);
        }
        if (rightReg > 0) {
            _regs.release(rightReg);
        }
        _lastExprReg = -1;
        return;
    }

    const std::string op = node.getOperator();

    std::string leftType;
    std::vector<int> leftDims;
    std::string rightType;
    std::vector<int> rightDims;
    const bool leftResolved = resolveNodeType(node.getLeft(), leftType, leftDims);
    const bool rightResolved = resolveNodeType(node.getRight(), rightType, rightDims);
    const bool leftIsFloat = leftResolved && leftDims.empty() && trimCopy(leftType) == "float";
    const bool rightIsFloat = rightResolved && rightDims.empty() && trimCopy(rightType) == "float";

    const bool isArithmetic = op == "+" || op == "-" || op == "*" || op == "/" || op == "mod";
    const bool isComparison = op == "==" || op == "!=" || op == "<" || op == "<=" || op == ">" || op == ">=";
    const bool useFloatFixedPoint = (isArithmetic || isComparison) && (leftIsFloat || rightIsFloat);

    if (useFloatFixedPoint) {
        if (!leftIsFloat) {
            emit("muli " + regName(leftReg) + ", " + regName(leftReg) + ", " + std::to_string(kFloatScale));
        }
        if (!rightIsFloat) {
            emit("muli " + regName(rightReg) + ", " + regName(rightReg) + ", " + std::to_string(kFloatScale));
        }
    }

    if (op == "+") {
        emit("add " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == "-") {
        emit("sub " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == "*") {
        emit("mul " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
        if (useFloatFixedPoint) {
            emit("divi " + regName(leftReg) + ", " + regName(leftReg) + ", " + std::to_string(kFloatScale));
        }
    } else if (op == "/") {
        if (useFloatFixedPoint) {
            emit("muli " + regName(leftReg) + ", " + regName(leftReg) + ", " + std::to_string(kFloatScale));
        }
        emit("div " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == "mod") {
        emit("mod " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == "and" || op == "&&") {
        emit("and " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == "or" || op == "||") {
        emit("or " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == "==") {
        emit("ceq " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == "!=") {
        emit("cne " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == "<") {
        emit("clt " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == "<=") {
        emit("cle " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == ">") {
        emit("cgt " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else if (op == ">=") {
        emit("cge " + regName(leftReg) + ", " + regName(leftReg) + ", " + regName(rightReg));
    } else {
        reportError(node.getLineNumber(), "unsupported binary operator in code generation: '" + op + "'");
    }

    _regs.release(rightReg);
    _lastExprReg = leftReg;
}

void CodeGenVisitor::visit(UnaryOpNode& node) {
    int operandReg = evalExpr(node.getLeft());
    if (operandReg < 0) {
        _lastExprReg = -1;
        return;
    }

    const std::string op = node.getOperator();
    if (op == "-") {
        emit("sub " + regName(operandReg) + ", r0, " + regName(operandReg));
    } else if (op == "not") {
        emit("ceqi " + regName(operandReg) + ", " + regName(operandReg) + ", 0");
    } else if (op != "+") {
        reportError(node.getLineNumber(), "unsupported unary operator in code generation: '" + op + "'");
    }

    _lastExprReg = operandReg;
}

void CodeGenVisitor::visit(FuncCallNode& node) {
    const FunctionLayoutInfo* targetLayout = nullptr;
    std::shared_ptr<ASTNode> ownerExpr = nullptr;
    bool explicitMethodCall = false;
    bool implicitMethodCall = false;

    auto calleeMember = std::dynamic_pointer_cast<DataMemberNode>(node.getLeft());
    if (calleeMember != nullptr && calleeMember->getLeft() != nullptr) {
        explicitMethodCall = true;
        ownerExpr = calleeMember->getLeft();

        std::string ownerType;
        std::vector<int> ownerDimensions;
        if (!resolveNodeType(ownerExpr, ownerType, ownerDimensions)) {
            _lastExprReg = -1;
            return;
        }
        if (!ownerDimensions.empty()) {
            reportError(node.getLineNumber(), "method receiver must be a scalar object");
            _lastExprReg = -1;
            return;
        }

        targetLayout = findFunctionLayout(ownerType, node.getFunctionName());
    } else {
        targetLayout = findFunctionLayout("", node.getFunctionName());
        if (targetLayout == nullptr && !_currentClassName.empty()) {
            targetLayout = findFunctionLayout(_currentClassName, node.getFunctionName());
            if (targetLayout != nullptr && targetLayout->isMethod) {
                implicitMethodCall = true;
            }
        }
    }

    if (targetLayout == nullptr) {
        reportError(node.getLineNumber(), "function call code generation target not found: '" + node.getFunctionName() + "'");
        _lastExprReg = -1;
        return;
    }

    if (targetLayout->paramOffsets.size() != node.getArgs().size()) {
        reportError(node.getLineNumber(), "argument count mismatch in call to '" + node.getFunctionName() + "'");
        _lastExprReg = -1;
        return;
    }

    const long callerFrameSize = _currentFrameSize;

    for (size_t i = 0; i < node.getArgs().size(); ++i) {
        std::string expectedType;
        std::vector<int> expectedDims;
        if (i < targetLayout->paramNames.size()) {
            auto paramInfoIt = targetLayout->varInfo.find(targetLayout->paramNames[i]);
            if (paramInfoIt != targetLayout->varInfo.end()) {
                expectedType = trimCopy(paramInfoIt->second.typeName);
                expectedDims = paramInfoIt->second.dimensions;
            }
        }

        const bool expectedIsArray = !expectedDims.empty();

        int argReg = -1;
        if (expectedIsArray) {
            argReg = emitAddressForLValue(node.getArgs()[i], node.getLineNumber());
        } else {
            argReg = evalExpr(node.getArgs()[i]);
        }

        if (argReg < 0) {
            _lastExprReg = -1;
            return;
        }

        std::string actualType;
        std::vector<int> actualDims;
        const bool actualResolved = resolveNodeType(node.getArgs()[i], actualType, actualDims);
        const bool actualIsFloat = actualResolved && actualDims.empty() && trimCopy(actualType) == "float";
        const bool expectedIsFloat = !expectedIsArray && expectedType == "float";

        if (expectedIsFloat && !actualIsFloat) {
            emit("muli " + regName(argReg) + ", " + regName(argReg) + ", " + std::to_string(kFloatScale));
        }

        const long storeOffset = targetLayout->paramOffsets[i] - callerFrameSize;
        emit("sw " + std::to_string(storeOffset) + "(r14), " + regName(argReg));
        _regs.release(argReg);
    }

    if (targetLayout->isMethod) {
        const int thisReg = _regs.acquire();
        if (thisReg < 0) {
            reportError(node.getLineNumber(), "register exhaustion while preparing method receiver");
            _lastExprReg = -1;
            return;
        }

        if (explicitMethodCall) {
            const int ownerAddrReg = emitAddressForLValue(ownerExpr, node.getLineNumber());
            if (ownerAddrReg < 0) {
                _regs.release(thisReg);
                _lastExprReg = -1;
                return;
            }

            emit("add " + regName(thisReg) + ", " + regName(ownerAddrReg) + ", r0");
            _regs.release(ownerAddrReg);
        } else if (implicitMethodCall) {
            if (!loadThisPointerInto(thisReg, node.getLineNumber())) {
                _regs.release(thisReg);
                _lastExprReg = -1;
                return;
            }
        } else {
            reportError(node.getLineNumber(), "method call requires an object receiver");
            _regs.release(thisReg);
            _lastExprReg = -1;
            return;
        }

        const long thisStoreOffset = targetLayout->thisOffset - callerFrameSize;
        emit("sw " + std::to_string(thisStoreOffset) + "(r14), " + regName(thisReg));
        _regs.release(thisReg);
    }

    if (callerFrameSize > 0) {
        emit("subi r14, r14, " + std::to_string(callerFrameSize));
    }
    emit("jl r15, " + targetLayout->label);
    if (callerFrameSize > 0) {
        emit("addi r14, r14, " + std::to_string(callerFrameSize));
    }

    const int resultReg = _regs.acquire();
    if (resultReg < 0) {
        reportError(node.getLineNumber(), "register exhaustion while retrieving function result");
        _lastExprReg = -1;
        return;
    }

    emit("add " + regName(resultReg) + ", r1, r0");
    _lastExprReg = resultReg;
}

void CodeGenVisitor::visit(DataMemberNode& node) {
    const int addrReg = emitAddressForDataMember(node);
    if (addrReg < 0) {
        _lastExprReg = -1;
        return;
    }

    const int valueReg = _regs.acquire();
    if (valueReg < 0) {
        _regs.release(addrReg);
        reportError(node.getLineNumber(), "register exhaustion while loading data member");
        _lastExprReg = -1;
        return;
    }

    emit("lw " + regName(valueReg) + ", 0(" + regName(addrReg) + ")");
    _regs.release(addrReg);
    _lastExprReg = valueReg;
}

void CodeGenVisitor::visit(AssignStmtNode& node) {
    int valueReg = evalExpr(node.getRight());
    if (valueReg < 0) {
        return;
    }

    std::string leftType;
    std::vector<int> leftDims;
    std::string rightType;
    std::vector<int> rightDims;
    const bool leftResolved = resolveNodeType(node.getLeft(), leftType, leftDims);
    const bool rightResolved = resolveNodeType(node.getRight(), rightType, rightDims);
    const bool leftIsFloat = leftResolved && leftDims.empty() && trimCopy(leftType) == "float";
    const bool rightIsFloat = rightResolved && rightDims.empty() && trimCopy(rightType) == "float";

    if (leftIsFloat && !rightIsFloat) {
        emit("muli " + regName(valueReg) + ", " + regName(valueReg) + ", " + std::to_string(kFloatScale));
    }

    if (!emitStoreTarget(node.getLeft(), valueReg)) {
        _regs.release(valueReg);
        return;
    }

    _regs.release(valueReg);
}

void CodeGenVisitor::visit(IfStmtNode& node) {
    int condReg = evalExpr(node.getLeft());
    if (condReg < 0) {
        return;
    }

    const std::string elseLabel = makeLabel("else");
    const std::string endLabel = makeLabel("endif");

    emit("bz " + regName(condReg) + ", " + elseLabel);
    _regs.release(condReg);

    if (node.getRight() != nullptr) {
        node.getRight()->accept(*this);
    }

    emit("j " + endLabel);
    emit(elseLabel);

    if (node.getElseBlock() != nullptr) {
        node.getElseBlock()->accept(*this);
    }

    emit(endLabel);
}

void CodeGenVisitor::visit(WhileStmtNode& node) {
    const std::string startLabel = makeLabel("while_start");
    const std::string endLabel = makeLabel("while_end");

    emit(startLabel);

    int condReg = evalExpr(node.getLeft());
    if (condReg < 0) {
        return;
    }

    emit("bz " + regName(condReg) + ", " + endLabel);
    _regs.release(condReg);

    if (node.getRight() != nullptr) {
        node.getRight()->accept(*this);
    }

    emit("j " + startLabel);
    emit(endLabel);
}

void CodeGenVisitor::visit(IOStmtNode& node) {
    const std::string ioType = node.getValue();

    if (ioType == "read") {
        std::string targetType;
        std::vector<int> targetDims;
        if (!resolveNodeType(node.getLeft(), targetType, targetDims)) {
            return;
        }

        if (!targetDims.empty()) {
            reportError(node.getLineNumber(), "read statement requires scalar target");
            return;
        }

        if (!targetType.empty() && targetType != "integer" && targetType != "float" && targetType != "bool") {
            reportError(node.getLineNumber(), "read statement is only supported for scalar integer/float/bool targets");
            return;
        }

        if (targetType == "float") {
            emitComment("read lowered to decimal float parser (rt_readFloat)");
            emit("jl r15, rt_readFloat");
        } else {
            emitComment("read lowered to decimal integer parser (rt_readInt)");
            emit("jl r15, rt_readInt");
        }

        int inputReg = _regs.acquire();
        if (inputReg < 0) {
            reportError(node.getLineNumber(), "register exhaustion while storing readInt result");
            return;
        }

        emit("add " + regName(inputReg) + ", r1, r0");
        emitStoreTarget(node.getLeft(), inputReg);
        _regs.release(inputReg);
        return;
    }

    if (ioType == "write") {
        int valueReg = evalExpr(node.getLeft());
        if (valueReg < 0) {
            return;
        }

        std::string valueType;
        std::vector<int> valueDims;
        const bool valueResolved = resolveNodeType(node.getLeft(), valueType, valueDims);
        const bool valueIsFloat = valueResolved && valueDims.empty() && trimCopy(valueType) == "float";

        emit("add r1, " + regName(valueReg) + ", r0");
        if (valueIsFloat) {
            emitComment("write lowered to fixed-point float printer (rt_writeFloat)");
            emit("jl r15, rt_writeFloat");
        } else {
            emitComment("write lowered to decimal integer printer (rt_writeInt)");
            emit("jl r15, rt_writeInt");
        }
        _regs.release(valueReg);
        return;
    }

    reportError(node.getLineNumber(), "unknown I/O statement kind in code generation: '" + ioType + "'");
}

void CodeGenVisitor::visit(ReturnStmtNode& node) {
    if (node.getLeft() != nullptr) {
        int retReg = evalExpr(node.getLeft());
        if (retReg >= 0) {
            std::string actualType;
            std::vector<int> actualDims;
            const bool actualResolved = resolveNodeType(node.getLeft(), actualType, actualDims);
            const bool actualIsFloat = actualResolved && actualDims.empty() && trimCopy(actualType) == "float";
            if (_currentReturnType == "float" && !actualIsFloat) {
                emit("muli " + regName(retReg) + ", " + regName(retReg) + ", " + std::to_string(kFloatScale));
            }

            emitComment("return value currently lowered into r1");
            emit("add r1, " + regName(retReg) + ", r0");
            _regs.release(retReg);
        }
    }

    if (_currentFunction != "main") {
        emit("j " + _currentReturnLabel);
    }
}

void CodeGenVisitor::visit(BlockNode& node) {
    for (const auto& stmt : node.getStatements()) {
        if (stmt != nullptr) {
            stmt->accept(*this);
            if (std::dynamic_pointer_cast<FuncCallNode>(stmt) != nullptr && _lastExprReg > 0) {
                _regs.release(_lastExprReg);
                _lastExprReg = -1;
            }
        }
    }
}

void CodeGenVisitor::visit(VarDeclNode&) {
    // Storage is assigned when entering a function frame.
}

void CodeGenVisitor::visit(FuncDefNode& node) {
    (void)node;
    // Function bodies are emitted in visit(ProgNode) with layout-aware call metadata.
}

void CodeGenVisitor::visit(ClassDeclNode& node) {
    emitComment("class code generation not implemented for: " + node.getName());
}

void CodeGenVisitor::visit(ProgNode& node) {
    _classDecls.clear();
    _classLayouts.clear();
    _classSizes.clear();
    _functionLayouts.clear();

    for (const auto& cls : node.getClasses()) {
        if (cls != nullptr) {
            _classDecls[cls->getName()] = cls;
        }
    }

    std::shared_ptr<FuncDefNode> mainFunction = nullptr;
    std::vector<std::shared_ptr<FuncDefNode>> nonMainFunctions;

    for (const auto& fn : node.getFunctions()) {
        if (fn == nullptr || fn->getRight() == nullptr) {
            continue;
        }

        if (!buildFunctionLayout(fn)) {
            continue;
        }

        if (fn->getClassName().empty() && fn->getName() == "main") {
            mainFunction = fn;
        } else {
            nonMainFunctions.push_back(fn);
        }
    }

    if (mainFunction == nullptr) {
        reportError(0, "program has no main function for code generation");
        return;
    }

    const FunctionLayoutInfo* mainLayout = findFunctionLayout("", "main");
    if (mainLayout == nullptr) {
        reportError(mainFunction->getLineNumber(), "failed to build frame layout for main");
        return;
    }

    const std::string programEndLabel = makeLabel("program_end");

    emitFunctionBody(mainFunction, *mainLayout, true);
    emit("j " + programEndLabel);

    for (const auto& fn : nonMainFunctions) {
        const FunctionLayoutInfo* layout = findFunctionLayout(fn->getClassName(), fn->getName());
        if (layout == nullptr) {
            reportError(fn->getLineNumber(), "missing function layout for '" + functionKey(fn->getClassName(), fn->getName()) + "'");
            continue;
        }

        emitFunctionBody(fn, *layout, false);
    }

    emit(programEndLabel);
}

bool generateMoonAssembly(const std::shared_ptr<ProgNode>& root, const std::string& outputPath, std::vector<std::string>* errors) {
    std::ofstream out(outputPath, std::ios::out | std::ios::trunc | std::ios::binary);
    if (!out.is_open()) {
        if (errors != nullptr) {
            errors->push_back("[ERROR][CODEGEN] Failed to open output file: " + outputPath);
        }
        return false;
    }

    CodeGenVisitor generator(out);
    const bool success = generator.generate(root);

    if (errors != nullptr) {
        *errors = generator.getErrors();
    }

    return success;
}
